### PR TITLE
Fix-some-crashes

### LINKED ISSUE #5123: Placeholders in "Default save name"
### Operating System

Windows

### (Linux only) Distribution

_No response_

### (Linux only) Desktop Environment

_No response_

### (Linux Only) Display Server

None

### Installation Method

xournalpp-1.2.1+dev-nightly.20230831-windows.zip

### Xournal++ Version

xournalpp-1.2.1+dev-nightly.20230831-windows

### libgtk Version

3.24.39

### Bug Description

In Preferences->Load/Save->Default Save Name, the placeholders %c, %F, %X and %Z does not work (and %Z crashes Xournalpp)
I work in French but xournal does not take my chosen language when it replaces placehoders ( It writes  in English)

### Expected Behaviour

Possibility of using %c, %F, %X and %Z in "Default save name" and use the right language

### Steps to Reproduce

Use %c, %F, %X and %Z in "Default save name"

### Additional Context

_No response_

### LINKED ISSUE #5126: Crash after clicking on "export as PDF"
### Operating System

Linux

### (Linux only) Distribution

Fedora

### (Linux only) Desktop Environment

GNOME

### (Linux Only) Display Server

Wayland

### Installation Method

official (dnf)

### Xournal++ Version

1.2.0

### libgtk Version

3.24.38

### Bug Description

I clicked on "export as PDF" after adding a png to a pdf. Nothing unusual, nothing I hadn't done 100x before. Doing the same thing after restarting Xournal++ worked just fine, including the export.

This is the log shown by Xournal++ upon the next start of the program:
```
Date: Wed Sep  6 11:45:53 2023
Error: signal 6
Xournal++ version 1.2.0
Gtk version 3.24.38

[bt]: (0) xournalpp(+0xc1d42) [0x5610ab6a8d42]
[bt]: (1) /lib64/libc.so.6(+0x3cb20) [0x7f469c25fb20]
[bt]: (2) /lib64/libc.so.6(+0x8ce8c) [0x7f469c2afe8c]
[bt]: (3) /lib64/libc.so.6(gsignal+0x16) [0x7f469c25fa76]
[bt]: (4) /lib64/libc.so.6(abort+0xd7) [0x7f469c2497fc]
[bt]: (5) /lib64/libc.so.6(+0x2671b) [0x7f469c24971b]
[bt]: (6) /lib64/libc.so.6(+0x35656) [0x7f469c258656]
[bt]: (7) xournalpp(_ZN9RenderJob17rerenderRectangleERKN3xoj4util9RectangleIdEE+0x130) [0x5610ab7c7af0]
[bt]: (8) xournalpp(_ZN9RenderJob3runEv+0xab) [0x5610ab7c7bbb]
[bt]: (9) xournalpp(_ZN9Scheduler17jobThreadCallbackEPS_+0xf8) [0x5610ab6a4bc8]
[bt]: (10) /lib64/libglib-2.0.so.0(+0x85f22) [0x7f469cb14f22]
[bt]: (11) /lib64/libc.so.6(+0x8b15d) [0x7f469c2ae15d]
[bt]: (12) /lib64/libc.so.6(+0x10cc00) [0x7f469c32fc00]


Try to get a better stracktrace...
[bt] #1 xournalpp(+0xc2288) [0x5610ab6a9288]
??:0
[bt] #2 /lib64/libc.so.6(+0x3cb20) [0x7f469c25fb20]
??:0
[bt] #3 /lib64/libc.so.6(+0x8ce8c) [0x7f469c2afe8c]
??:0
[bt] #4 /lib64/libc.so.6(gsignal+0x16) [0x7f469c25fa76]
??:0
[bt] #5 /lib64/libc.so.6(abort+0xd7) [0x7f469c2497fc]
??:0
[bt] #6 /lib64/libc.so.6(+0x2671b) [0x7f469c24971b]
??:0
[bt] #7 /lib64/libc.so.6(+0x35656) [0x7f469c258656]
??:0
[bt] #8 xournalpp(_ZN9RenderJob17rerenderRectangleERKN3xoj4util9RectangleIdEE+0x130) [0x5610ab7c7af0]
??:0
[bt] #9 xournalpp(_ZN9RenderJob3runEv+0xab) [0x5610ab7c7bbb]
??:0
[bt] #10 xournalpp(_ZN9Scheduler17jobThreadCallbackEPS_+0xf8) [0x5610ab6a4bc8]
??:0
[bt] #11 /lib64/libglib-2.0.so.0(+0x85f22) [0x7f469cb14f22]
??:0
[bt] #12 /lib64/libc.so.6(+0x8b15d) [0x7f469c2ae15d]
??:0
[bt] #13 /lib64/libc.so.6(+0x10cc00) [0x7f469c32fc00]
??:0


Execution log:

DEBUG   : GLib-GIO :: Using cross-namespace EXTERNAL authentication (this will deadlock if server is GDBus < 2.73.3)
DEBUG   : GLib-GIO :: _g_io_module_get_default: Found default implementation dconf (DConfSettingsBackend) for ‘gsettings-backend’
DEBUG   : GLib-GIO :: Using cross-namespace EXTERNAL authentication (this will deadlock if server is GDBus < 2.73.3)
DEBUG   : GLib-GIO :: _g_io_module_get_default: Found default implementation gvfs (GDaemonVfs) for ‘gio-vfs’
DEBUG   : GLib :: unsetenv() is not thread-safe and should not be used after threads are created
MESSAGE : xopp :: TEXTDOMAINDIR = (null), Platform-specific locale dir = /usr/share/xournalpp/../locale, chosen directory = /usr/share/xournalpp/../locale
INFO    : xopp :: Loading plugins from: /usr/share/xournalpp/plugins
INFO    : xopp :: Loading plugins from: /home/hoebler/.config/xournalpp/plugins
MESSAGE : xopp :: Plugin "MigrateFontSizes" UI initialized
CRITICAL: Gtk :: gtk_tree_model_iter_children: assertion 'GTK_IS_TREE_MODEL (tree_model)' failed
CRITICAL: GLib-GObject :: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
DEBUG   : GdkPixbuf :: gdk_pixbuf_from_pixdata() called on:
DEBUG   : GdkPixbuf :: 	Encoding raw
DEBUG   : GdkPixbuf :: 	Dimensions: 20 x 25
DEBUG   : GdkPixbuf :: 	Rowstride: 80, Length: 2024
DEBUG   : GdkPixbuf :: 	Copy pixels == false
DEBUG   : GdkPixbuf :: gdk_pixbuf_from_pixdata() called on:
DEBUG   : GdkPixbuf :: 	Encoding raw
DEBUG   : GdkPixbuf :: 	Dimensions: 20 x 25
DEBUG   : GdkPixbuf :: 	Rowstride: 80, Length: 2024
DEBUG   : GdkPixbuf :: 	Copy pixels == false
WARNING : xopp :: [Crash Handler] Crashed with signal 6
WARNING : xopp :: [Crash Handler] Wrote crash log to: /home/hoebler/.cache/xournalpp/errorlogs/errorlog.20230906-114553.log
```

### Expected Behaviour

Export to PDF without crashing

### Steps to Reproduce

Cannot reproduce since this is the first time this happened after doing the same thing many times before...

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by Febbe**
- fixes #5123 partially
- fixes #5126

### CODE REVIEW

File: src/core/model/Document.cpp [hunk 1]
```diff
@@ -152,17 +156,23 @@ auto Document::createSaveFilename(DocumentType type, const std::string& defaultS
 
     const char* format = wildcardString.empty() ? defaultSaveName.c_str() : wildcardString.c_str();
 
+    // Todo (cpp20): use <format>
+    std::ostringstream ss;
+    ss.imbue(std::locale(""));
```
Comment (Febbe) [inline src/core/model/Document.cpp:161]: We probably want to use the configured locale, instead of the systems/users locale, but I don't know how and if this is possible (yet).

File: src/core/model/Document.cpp [hunk 2]
```diff
@@ -152,17 +156,23 @@ auto Document::createSaveFilename(DocumentType type, const std::string& defaultS
...
-    strftime(stime, sizeof(stime), format, localtime(&curtime));
-
-    // Remove the extension, file format is handled by the filter combo box
-    fs::path p = stime;
+    ss << std::put_time(localtime(&curtime), format);
+    auto filename = ss.str();
+    // Todo (cpp20): use <ranges>
+    for (auto& c : filename) {
+        if (forbiddenChars.find(c) != std::string::npos) {
+            c = '_';
```
Comment (Febbe) [inline src/core/model/Document.cpp:168]: Here we must also check, if a character is greater 127 and or any other invisible character like \n/\t

**Review by Febbe — COMMENTED** [review]
Some issues I found while testing.

File: src/core/model/Document.cpp (hunk 2 above)
Comment (bhennion) [reply src/core/model/Document.cpp:168]: This should go into util/PathUtil, I think.

Comment (Febbe) [reply src/core/model/Document.cpp:168]: The thing is, that this function parses the input from a user, we will never need it elsewhere. It also does not work on paths itself, only on filenames. Gtk already does something similar, it just ignores the filename, if wrong.

**Review by bhennion — APPROVED** [review]
