### PR TITLE
Avoid crash when triggering automatic page addition by dragging selection

### LINKED ISSUE #6240: Crash when trying to create new last page by dragging a selection
### Operating System

Linux

### (Linux only) Distribution

Arch Linux

### (Linux only) Desktop Environment

i3wm

### (Linux Only) Display Server

X.Org

### Installation Method

pacman (from the extra repository)

### Xournal++ Version

1.2.5

### libgtk Version

3.24.43

### Bug Description

Xournalpp reliably crashes when moving a selection to the bottom of the last page (only when Edit>Preferences>Drawing Area>Automatically Add Empty Last Page is set to 'when scrolling to end of last page').

### Expected Behaviour

A new page is created that the selection is dragged onto.

### Steps to Reproduce

1. Go to Edit>Preferences>Drawing Area>Automatically Add Empty Last Page and set it to 'when scrolling to end of last page'.
2. Draw/write something.
3. Select it.
4. Drag it downwards.
5. Let it autoscroll down until it would create a new page.

### Additional Context

My error log:
```
Date: Sat Jan 25 21:14:38 2025
Error: signal 11
Xournal++ version 1.2.5
Git commit 9f467a40 from startdir/makepkg
Gtk version 3.24.43

[bt]: (0) xournalpp(+0xb27a6) [0x560e0e9047a6]
[bt]: (1) /usr/lib/libc.so.6(+0x3d1d0) [0x78b05521e1d0]
[bt]: (2) xournalpp(_ZN13EditSelection12updateMatrixEv+0x2d) [0x560e0e9b7d8d]
[bt]: (3) xournalpp(_ZN13EditSelection13moveSelectionEddb+0x4c) [0x560e0e9c17ec]
[bt]: (4) xournalpp(_ZN13EditSelection13handleEdgePanEPS_+0x2da) [0x560e0e9c2a5a]
[bt]: (5) xournalpp(_ZN3xoj4util6detail9wrap_implIXadL_ZN13EditSelection13handleEdgePanEPS3_EEbS4_JEEENSt11conditionalIX9is_same_vIbT0_EEiS6_E4typeEDpT2_Pv+0xe) [0x560e0e9c2c6e]
[bt]: (6) /usr/lib/libglib-2.0.so.0(+0x5ea0a) [0x78b05598ea0a]
[bt]: (7) /usr/lib/libglib-2.0.so.0(+0x5d559) [0x78b05598d559]
[bt]: (8) /usr/lib/libglib-2.0.so.0(+0xc0257) [0x78b0559f0257]
[bt]: (9) /usr/lib/libglib-2.0.so.0(g_main_context_iteration+0x35) [0x78b05598ca55]
[bt]: (10) /usr/lib/libgio-2.0.so.0(g_application_run+0x1f6) [0x78b055eabcb6]
[bt]: (11) xournalpp(_ZN11XournalMain3runEiPPc+0x642) [0x560e0e9010d2]
[bt]: (12) /usr/lib/libc.so.6(+0x25e08) [0x78b055206e08]
[bt]: (13) /usr/lib/libc.so.6(__libc_start_main+0x8c) [0x78b055206ecc]
[bt]: (14) xournalpp(_start+0x25) [0x560e0e8fe995]


Try to get a better stacktrace...
[bt] #0 xournalpp(+0xb2f10) [0x560e0e904f10]
[bt] #1 /usr/lib/libc.so.6(+0x3d1d0) [0x78b05521e1d0]
__sigaction at ??:?
[bt] #2 xournalpp(_ZN13EditSelection12updateMatrixEv+0x2d) [0x560e0e9b7d8d]
[bt] #3 xournalpp(_ZN13EditSelection13moveSelectionEddb+0x4c) [0x560e0e9c17ec]
[bt] #4 xournalpp(_ZN13EditSelection13handleEdgePanEPS_+0x2da) [0x560e0e9c2a5a]
[bt] #5 xournalpp(_ZN3xoj4util6detail9wrap_implIXadL_ZN13EditSelection13handleEdgePanEPS3_EEbS4_JEEENSt11conditionalIX9is_same_vIbT0_EEiS6_E4typeEDpT2_Pv+0xe) [0x560e0e9c2c6e]
[bt] #6 /usr/lib/libglib-2.0.so.0(+0x5ea0a) [0x78b05598ea0a]
g_main_context_check at ??:?
[bt] #7 /usr/lib/libglib-2.0.so.0(+0x5d559) [0x78b05598d559]
g_source_query_unix_fd at ??:?
[bt] #8 /usr/lib/libglib-2.0.so.0(+0xc0257) [0x78b0559f0257]
g_io_channel_new_file at ??:?
[bt] #9 /usr/lib/libglib-2.0.so.0(g_main_context_iteration+0x35) [0x78b05598ca55]
g_main_context_iteration at ??:?
[bt] #10 /usr/lib/libgio-2.0.so.0(g_application_run+0x1f6) [0x78b055eabcb6]
g_application_run at ??:?
[bt] #11 xournalpp(_ZN11XournalMain3runEiPPc+0x642) [0x560e0e9010d2]
[bt] #12 /usr/lib/libc.so.6(+0x25e08) [0x78b055206e08]
__libc_init_first at ??:?
[bt] #13 /usr/lib/libc.so.6(__libc_start_main+0x8c) [0x78b055206ecc]
__libc_start_main at ??:?
[bt] #14 xournalpp(_start+0x25) [0x560e0e8fe995]


Execution log:

DEBUG   : GLib-GIO :: Using cross-namespace EXTERNAL authentication (this will deadlock if server is GDBus < 2.73.3)
DEBUG   : GLib-GIO :: _g_io_module_get_default: Found default implementation local (GLocalVfs) for ‘gio-vfs’
DEBUG   : GLib :: unsetenv() is not thread-safe and should not be used after threads are created
DEBUG   : xopp :: TEXTDOMAINDIR = (null), Platform-specific locale dir = /usr/share/xournalpp/../locale, chosen directory = /usr/share/xournalpp/../locale
INFO    : xopp :: Loading plugins from: /usr/share/xournalpp/plugins
INFO    : xopp :: Loading plugins from: /home/jules/.config/xournalpp/plugins
MESSAGE : xopp :: Plugin "MigrateFontSizes" UI initialized
DEBUG   : xopp :: Extracted theme info: Name = Adwaita, rootname = Adwaita, dark = false
DEBUG   : xopp :: Theme name: Adwaita
DEBUG   : xopp :: Modified in GtkSettings: false
DEBUG   : xopp :: Theme variant: dark
DEBUG   : xopp :: Icon theme: iconsColor
DEBUG   : GdkPixbuf :: gdk_pixbuf_from_pixdata() called on:
DEBUG   : GdkPixbuf :: 	Encoding raw
DEBUG   : GdkPixbuf :: 	Dimensions: 20 x 25
DEBUG   : GdkPixbuf :: 	Rowstride: 80, Length: 2024
DEBUG   : GdkPixbuf :: 	Copy pixels == false
DEBUG   : GdkPixbuf :: gdk_pixbuf_from_pixdata() called on:
DEBUG   : GdkPixbuf :: 	Encoding raw
DEBUG   : GdkPixbuf :: 	Dimensions: 20 x 25
DEBUG   : GdkPixbuf :: 	Rowstride: 80, Length: 2024
DEBUG   : GdkPixbuf :: 	Copy pixels == false
WARNING : xopp :: [Crash Handler] Crashed with signal 11
WARNING : xopp :: [Crash Handler] Wrote crash log to: /home/jules/.cache/xournalpp/errorlogs/errorlog.20250125-211438.log

```

### PR DESCRIPTION
**Pull request by bhennion**
Fix #6240

~~This fixes the crash, but does not really fix the underlying issue with the automatic page addition feature.~~

The crash was caused by the following path. As the user drags the selection downwards, the `EditSelection::edgePanHandler()` callback gets called. It triggers a scrolling (`Layout::scrollRelative()`). This scrolling in turn triggers a call to `Layout::maybeAddPage()`, with then adds a page.
When adding a page, we always clear selections and text edition (see `PageBackgroundController::insertNewPage()`), so the EditSelection instance which triggered all that gets destroyed... We then get the SegFault when the EditSelection instance gets accessed after deletion.

~~Now, this PR fixes the crash, BUT the selected items still often disappear (they are in fact added to a page, but outside its bound and thus get deleted...).
A proper fix would need to have the automatic page addition feature made aware of existing selections, and ensuring that the content stays selected. That would be some work - the code around this feature is a bit scattered and some refactoring would be required.~~

Edit: Stroke out the outdated description. See post below.

### CODE REVIEW

**Comment by bhennion** [comment]
I implemented a much better fix. It wasn't as complicated as I thought.

So now:
1. It doesn't crash anymore
2. The selection stays selected when pages are added automatically (upon scrolling, typically).
3. The automated page insertion is disabled if the inserted page would be a image page. Otherwise (e.g. on master), the dialog would pop up, asking the user to pick an image...

File: src/core/control/tools/EditSelection.cpp [hunk 1]
```diff
@@ -9,8 +9,6 @@
 #include <string>     // for string
 #include <utility>
 
-#include <gdk/gdk.h>  // for gdk_cairo_set_sour...
-
```
Comment (rolandlo) [inline src/core/control/tools/EditSelection.cpp:13]: I guess this include removal should have gone into `Selector.cpp`. We still have `gdk_cairo_set_source_rgba` in `EditSelection.cpp`.

**Comment by bhennion** [comment]
Thanks for the review!
I just realized the PR had target the master branch. Are you ok with me merging this to the release-1.3 branch?

**Comment by rolandlo** [comment]
> Thanks for the review! I just realized the PR had target the master branch. Are you ok with me merging this to the release-1.3 branch?

Yes, sure. I didn't notice that.
