### PR TITLE
Fix #4301

### LINKED ISSUE #4301: Crash when using highlighter with stroke stabilizer (and finish stroke) turned on
(Please complete the following information, and then delete this line)

**Affects versions :**
 - OS: Linux
 - (Linux only) Desktop environment: Wayland
 - Which version of libgtk do you use 3.24.34
 - Version of Xournal++: latest master 
grafik
 - Installation method: PPA

**Describe the bug**
When using the highlighter with the stroke stabilizer turned on Xournal++ crashes (with signal 6) seemingly randomly after a few strokes. In the terminal I see that the assertion `p.z > 0.0` in `xoj::view::StrokeViewHelper::drawWithPressure` is not satisfied.

```
xournalpp: ./src/core/view/StrokeViewHelper.cpp:45: xoj::view::StrokeViewHelper::drawWithPressure(cairo_t*, const std::vector<Point>&, const LineStyle&, double)::<lambda(const Point&, const Point&)>: Zusicherung »p.z > 0.0« nicht erfüllt.

** (xournalpp:40806): WARNING **: 12:46:31.737: [Crash Handler] Crashed with signal 6
```

Crash log:
<details>

```term
Error: signal 6
[bt]: (0) build/xournalpp(+0x30bdfc) [0x5590bba54dfc]
[bt]: (1) /lib/x86_64-linux-gnu/libc.so.6(+0x3bcf0) [0x7f8145e3bcf0]
[bt]: (2) /lib/x86_64-linux-gnu/libc.so.6(pthread_kill+0x11b) [0x7f8145e9210b]
[bt]: (3) /lib/x86_64-linux-gnu/libc.so.6(gsignal+0x16) [0x7f8145e3bc46]
[bt]: (4) /lib/x86_64-linux-gnu/libc.so.6(abort+0xd7) [0x7f8145e227fc]
[bt]: (5) /lib/x86_64-linux-gnu/libc.so.6(+0x2271b) [0x7f8145e2271b]
[bt]: (6) /lib/x86_64-linux-gnu/libc.so.6(+0x33596) [0x7f8145e33596]
[bt]: (7) build/xournalpp(+0x3f3e55) [0x5590bbb3ce55]
[bt]: (8) build/xournalpp(_ZN3xoj4view16StrokeViewHelper16drawWithPressureEP6_cairoRKSt6vectorI5PointSaIS5_EERK9LineStyled+0x22a) [0x5590bbb3d0fd]
[bt]: (9) build/xournalpp(_ZNK3xoj4view10StrokeView4drawERKNS0_7ContextE+0x836) [0x5590bbb3ca82]
[bt]: (10) build/xournalpp(_ZN13StrokeHandler13drawSegmentToERK5Point+0x335) [0x5590bbc62a5d]
[bt]: (11) build/xournalpp(_ZN16StrokeStabilizer6Active17quadraticSplineToERKNS_5EventE+0x4ef) [0x5590bbc65add]
[bt]: (12) build/xournalpp(_ZN16StrokeStabilizer6Active14finalizeStrokeEv+0x73) [0x5590bbc655d7]
[bt]: (13) build/xournalpp(_ZN13StrokeHandler20onButtonReleaseEventERK17PositionInputDatad+0x7f) [0x5590bbc62cad]
[bt]: (14) build/xournalpp(_ZN11XojPageView20onButtonReleaseEventERK17PositionInputData+0xbc) [0x5590bbbcc41a]
[bt]: (15) build/xournalpp(_ZN15PenInputHandler9actionEndERK10InputEvent+0x1dd) [0x5590bbadd24b]
[bt]: (16) build/xournalpp(_ZN18StylusInputHandler10handleImplERK10InputEvent+0x44e) [0x5590bbae31ba]
[bt]: (17) build/xournalpp(_ZN20AbstractInputHandler6handleERK10InputEvent+0x71) [0x5590bbbfd44b]
[bt]: (18) build/xournalpp(_ZN12InputContext6handleEP9_GdkEvent+0x392) [0x5590bbad85a0]
```
</details>

**To Reproduce**
1. Open a new document
2. Use the stylus to draw with the highlighter either using the highlighter from the toolbar or via pen button
3. Wait for the crash

**Expected behavior**
No crash

**Screenshots of Problem**
Here are my stroke stabilizer settings.
grafik
Trying various settings it seems that Xournal++ only crashes if the "Finish stroke" checkbox is activated.

**Additional context**
Possible suspect: #4137, commit https://github.com/xournalpp/xournalpp/commit/553588a4cf858d76b357322e40f50f750ca69794

### PR DESCRIPTION
**Pull request by bhennion**
Fix #4301

### CODE REVIEW

File: src/core/control/tools/StrokeStabilizer.cpp [hunk 1]
```diff
@@ -128,10 +128,9 @@ void StrokeStabilizer::Active::quadraticSplineTo(const Event& ev) {
     Point sp = C.relativeLineTo(Q, 2.0 / 3.0);
 
     /**
-     * Set the pressure values. We assume the tool is pressure sensitive:
-     *      stroke->getToolType() == STROKE_TOOL_PEN
+     * Set the pressure values. Only the usual pen strokes are pressure sensitive
      */
-    bool usePressure = ev.pressure != Point::NO_PRESSURE;
+    bool usePressure = ev.pressure != Point::NO_PRESSURE && stroke->getToolType() == STROKE_TOOL_PEN;
```
Comment (Technius) [inline src/core/control/tools/StrokeStabilizer.cpp:133]: I think it would be better to add and use a method like `canToolTypeHavePressure(toolType)` instead of assuming that only pen is pressure-sensitive, in case we want to add another pressure-sensitive tool in the future.

**Comment by bhennion** [comment]
> I think it would be better to add and use a method like `canToolTypeHavePressure(toolType)` instead of assuming that only pen is pressure-sensitive, in case we want to add another pressure-sensitive tool in the future.

I made StrokeView a class with member functions `isPressureSensitive()` and `hasLineStyle()`, and used those functions anywhere they fit.

Most changes are simple renaming (e.g. STROKE_TOOL_PEN is now StrokeTool::PEN). Other more meaningful changes are in Stroke.h, StrokeHandler.cpp, StrokeStabilizer.cpp and Control.cpp.

**Review by Technius — APPROVED** [review]
LGTM

**Comment by bhennion** [comment]
Merging in 24 hours unless an objection is raised.
