### PR TITLE
Sink floating refs in PreviewEntry

### LINKED ISSUE #5074: SegFault in SidebarPreviewLayerEntry()
Date: Sun Aug 20 21:09:30 2023
Error: signal 11
Xournal++ version 1.2.0
Git commit: 10ed72c9
Gtk version 3.24.38

[bt]: (0) xournalpp(+0xe69ba) [0x5610ef35e9ba]
[bt]: (1) /usr/lib/x86_64-linux-gnu/libc.so.6(+0x3f0c0) [0x7f34802630c0]
[bt]: (2) /usr/lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_widget_destroy+0x25) [0x7f34812f2c85]
[bt]: (3) xournalpp(_ZN24SidebarPreviewLayerEntryD0Ev+0x26) [0x5610ef4e0fa6]
[bt]: (4) xournalpp(_ZN18SidebarPreviewBaseD1Ev+0x87) [0x5610ef4e03f7]
[bt]: (5) xournalpp(_ZN20SidebarPreviewLayersD0Ev+0x7d) [0x5610ef481cad]
[bt]: (6) xournalpp(_ZN7SidebarD1Ev+0x5f) [0x5610ef47ebaf]
[bt]: (7) xournalpp(_ZN7SidebarD0Ev+0x15) [0x5610ef47ec65]
[bt]: (8) xournalpp(_ZN7ControlD2Ev+0x2dd) [0x5610ef3fad6d]
[bt]: (9) xournalpp(_ZN7ControlD0Ev+0x15) [0x5610ef3fb375]
[bt]: (10) xournalpp(_ZN11XournalMain3runEiPPc+0x617) [0x5610ef361c97]
[bt]: (11) /usr/lib/x86_64-linux-gnu/libc.so.6(+0x2954a) [0x7f348024d54a]
[bt]: (12) /usr/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x8b) [0x7f348024d60b]
[bt]: (13) xournalpp(_start+0x25) [0x5610ef35de35]

Try to get a better stracktrace...
[bt] #1 xournalpp(+0xe70a9) [0x5610ef35f0a9]
[bt] #2 /usr/lib/x86_64-linux-gnu/libc.so.6(+0x3f0c0) [0x7f34802630c0]
[bt] #3 /usr/lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_widget_destroy+0x25) [0x7f34812f2c85]
[bt] #4 xournalpp(_ZN24SidebarPreviewLayerEntryD0Ev+0x26) [0x5610ef4e0fa6]
[bt] #5 xournalpp(_ZN18SidebarPreviewBaseD1Ev+0x87) [0x5610ef4e03f7]
[bt] #6 xournalpp(_ZN20SidebarPreviewLayersD0Ev+0x7d) [0x5610ef481cad]
[bt] #7 xournalpp(_ZN7SidebarD1Ev+0x5f) [0x5610ef47ebaf]
[bt] #8 xournalpp(_ZN7SidebarD0Ev+0x15) [0x5610ef47ec65]
[bt] #9 xournalpp(_ZN7ControlD2Ev+0x2dd) [0x5610ef3fad6d]
[bt] #10 xournalpp(_ZN7ControlD0Ev+0x15) [0x5610ef3fb375]
[bt] #11 xournalpp(_ZN11XournalMain3runEiPPc+0x617) [0x5610ef361c97]
[bt] #12 /usr/lib/x86_64-linux-gnu/libc.so.6(+0x2954a) [0x7f348024d54a]
[bt] #13 /usr/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x8b) [0x7f348024d60b]
[bt] #14 xournalpp(_start+0x25) [0x5610ef35de35]

Execution log:

DEBUG   : GLib-GIO :: Using cross-namespace EXTERNAL authentication (this will deadlock if server is GDBus < 2.73.3)
DEBUG   : GLib-GIO :: _g_io_module_get_default: Found default implementation gvfs (GDaemonVfs) for ‘gio-vfs’
DEBUG   : GLib :: unsetenv() is not thread-safe and should not be used after threads are created
MESSAGE : xopp :: TEXTDOMAINDIR = (null), Platform-specific locale dir = /app/share/xournalpp/../locale, chosen directory = /app/share/xournalpp/../locale
INFO    : xopp :: Loading plugins from: /app/share/xournalpp/plugins
INFO    : xopp :: Loading plugins from: /home/sndrbrn/.var/app/com.github.xournalpp.xournalpp/config/xournalpp/plugins
MESSAGE : xopp :: Plugin "MigrateFontSizes" UI initialized
CRITICAL: Gtk :: gtk_tree_model_iter_children: assertion 'GTK_IS_TREE_MODEL (tree_model)' failed
CRITICAL: GLib-GObject :: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
WARNING : xopp :: Could not remove element from layer, it's not on the layer!
MESSAGE : xopp :: Info: autosave document...
MESSAGE : xopp :: Autosaving to /home/sndrbrn/.var/app/com.github.xournalpp.xournalpp/cache/xournalpp/autosaves/2.autosave.xopp
MESSAGE : xopp :: Info: autosave document...
MESSAGE : xopp :: Autosave renamed from /home/sndrbrn/.var/app/com.github.xournalpp.xournalpp/cache/xournalpp/autosaves/2.autosave.xopp to /home/sndrbrn/.var/app/com.github.xournalpp.xournalpp/cache/xournalpp/autosaves/2.old.autosave.xopp
MESSAGE : xopp :: Autosaving to /home/sndrbrn/.var/app/com.github.xournalpp.xournalpp/cache/xournalpp/autosaves/2.autosave.xopp
WARNING : xopp :: [Crash Handler] Crashed with signal 11
WARNING : xopp :: [Crash Handler] Wrote crash log to: /home/sndrbrn/.var/app/com.github.xournalpp.xournalpp/cache/xournalpp/errorlogs/errorlog.20230820-210930.log

### PR DESCRIPTION
**Pull request by bhennion**
Fixes #5074 

The issue was the following: by not sinking the widget's floating ref, the SidebarPreviewLayerEntry did not own a ref to the widget. The floating ref was then sunk by the parent container GtkLayout. So the widget has a ref-count of 1.
When calling `gtk_widget_destroy()` in `~SidebarPreviewLayerEntry()`, two things happen `gtk_container_remove()` is called on the GtkLayout and our widget **and** `g_object_unref()` is called.
As `gtk_container_remove()` also drops the ref-count by one (as the container releases its ref), we call `g_object_unref()` on an already destroyed object.

### CODE REVIEW

**Comment by Febbe** [comment]
LGTM, but the reference should be replaced by our managed containers on the master branch at some time.
It might be desirable, to do this in this PR, since we will forget to fix that later.

File: src/core/gui/sidebar/previews/base/SidebarPreviewBaseEntry.cpp [hunk 1]
```diff
@@ -20,7 +20,7 @@ SidebarPreviewBaseEntry::SidebarPreviewBaseEntry(SidebarPreviewBase* sidebar, co
     this->widget = gtk_button_new();  // re: issue 1072
 
     gtk_widget_show(this->widget);
-    g_object_ref(this->widget);
+    g_object_ref_sink(this->widget);
```
Comment (Febbe) [inline src/core/gui/sidebar/previews/base/SidebarPreviewBaseEntry.cpp:23]: **Nitpick**: 
The reference can be sunk and assigned in one line:

`this->widget = g_object_ref_sink(gtk_button_new());`

File: src/core/gui/sidebar/previews/layer/SidebarPreviewLayerEntry.cpp [hunk 2]
```diff
@@ -17,6 +17,7 @@ SidebarPreviewLayerEntry::SidebarPreviewLayerEntry(SidebarPreviewLayers* sidebar
         layerId(layerId),
         box(gtk_box_new(GTK_ORIENTATION_VERTICAL, 2)),
         stacked(stacked) {
+    g_object_ref_sink(box);
```
Comment (Febbe) [inline src/core/gui/sidebar/previews/layer/SidebarPreviewLayerEntry.cpp:20]: **Nitpick:**

```suggestion
        box(g_object_ref_sink(gtk_box_new(GTK_ORIENTATION_VERTICAL, 2))),
        stacked(stacked) {
```

**Comment by bhennion** [comment]
> LGTM, but the reference should be replaced by our managed containers on the master branch at some time.
> It might be desirable, to do this in this PR, since we will forget to fix that later.

I wanted to do that as well, but the situation is a bit more complicated. This class's destructor calls `gtk_widget_destroy()` and not `g_object_unref()`. `gtk_widget_destroy()` also removes the widget from its parent, and has been removed from gtk4, so we don't have an RAII wrapper for this (and I don't think we should).
Removing the call to `gtk_widget_destroy()` will require a more evolved refactoring.

**Comment by bhennion** [comment]
Merging once the CI checks are passed;
