### PR TITLE
Clear PDF cache when document changes

### LINKED ISSUE #1964: When annotating a PDF and opening new one, the new one won't show on the paper
**Affects versions :**
 - OS: Windows 10
 - Version of Xournal++: 1.0.18
 - Installation method: official release

**Describe the bug**
I grade homework that is submitted as PDF files. After I'm done grading one, I want to open the next one to annotate. When opening the new one, the paper resizes and the old PDF stays on the page. The new PDF won't load in. I have to close the program and open the new PDF again.

**To Reproduce**
1. Open a PDF with `File` > `Annotate PDF`
2. Annotate the PDF (I do it with the pen tool and my graphics tablet).
3. Open a new PDF with `File` > `Annotate PDF`

Reproduction rate: 100%

**Expected behavior**
The new PDF opens just like the first one.

### PR DESCRIPTION
**Pull request by clemdc**
This prevent previous PDF pages being rendered instead of new PDF ones.

Fixes #1964

### CODE REVIEW

File: src/gui/XournalView.cpp [hunk 1]
```diff
@@ -699,6 +699,9 @@ void XournalView::documentChanged(DocumentChangeType type) {
     }
     viewPages.clear();
 
+    delete this->cache;
+    this->cache = new PdfCache(control->getSettings()->getPdfPageCacheSize());
```
Comment (Technius) [inline src/gui/XournalView.cpp:703]: This works, but I think it would be better to make `PdfCache::clearCache` public and call it instead, as it makes the intent clearer.

**Comment by clemdc** [comment]
Would you want me to submit a new PR with the public change and the modification in the side view as well ?

**Comment by Febbe** [comment]
No its better to just do it in this PR.

**Comment by Technius** [comment]
LGTM, thanks for the PR.
