### PR TITLE
Fix confusing behavior of "Apply [page type] to current/all pages"

### LINKED ISSUE #951: Paper background "apply to all pages" strange behavior?
I supposed that "apply to all pages" should be a simple switch --- but it's acting (and looking) quite strange here (recently compiled, says it's 1.0.9): 

recorded

(do not mind the flashing lines, it's a `byzanz` (the gif recorder) artifact.

### PR DESCRIPTION
**Pull request by Technius**
This PR fixes the confusing behavior of the `Apply to current/all pages` buttons. Fixes #951.

* Fixes a bug where the `Journal > Paper background` apply page type button would use the page type from the new page type dropdown. The fix is a bit hacky but it's simple and straightforward.
* Fixes a bug where the selected page type in `Journal > Paper background` would not update after using `Apply to all pages` from the new page type dropdown.
* Removes the confusing check mark next to the Apply to current / all pages button.

Merging in 48 hours if there are no objections.

### CODE REVIEW

File: src/gui/dialog/PageTemplateDialog.cpp [hunk 1]
```diff
@@ -158,8 +156,6 @@ void PageTemplateDialog::showPageSizeDialog() {
 
         updatePageSize();
     }
-
-    delete dlg;
```
Comment (personalizedrefrigerator) [inline src/gui/dialog/PageTemplateDialog.cpp:162]: It looks like dlg is still being allocated with 'new' on line 147... Who is responsible for freeing dlg?

**Review by personalizedrefrigerator — COMMENTED** [review]
Thank you!

File: src/gui/dialog/PageTemplateDialog.cpp (hunk 1 above)
Comment (Technius) [reply src/gui/dialog/PageTemplateDialog.cpp:162]: Nice catch, thanks.

**Comment by Technius** [comment]
Split up the bugfix commit for more granularity and did a little bit more cleanup in `PageTemplateDialog`.
