### PR TITLE
Don't try to zoom on two finger touches if zoom gestures are disabled

### LINKED ISSUE #2509: Instant maximum zoom when pinching with zoom gestures disabled
**Affects versions :**
 - OS: Manjaro Linux
 - Version of Xournal++: 1.1.0+dev (5cf01b77)

**Describe the bug**
When zoom gestures are disabled, pinching with two fingers instantly zooms in to 700%.

**To Reproduce**
1. Start Xournal++.
2. Make sure that "Enable zoom gestures" is unticked.
3. Turn off "Zoom fit to screen".
4. Pinch with two fingers on the screen.

**Input Logs**
Input logs attached according to https://github.com/xournalpp/xournalpp/wiki/How-to-provide-debug-info-for-input-related-bugs.
[debug_input.log](https://github.com/xournalpp/xournalpp/files/5663227/debug_input.log)
[debug_gdk_input.log](https://github.com/xournalpp/xournalpp/files/5663226/debug_gdk_input.log)

**Expected behavior**
Nothing. Zoom gestures are turned off, so the zoom level should stay fixed even if I (accidentally) put two fingers on the screen.

**Screenshots of Problem**
Below is a video showing the instant zooming when I pinch.
zoom-snap

**Additional context**
I frequently trigger this by accident while writing. When I press the "Zoom to 100%" button to return to normal zoom, the document also scrolls back to page 1, which is of course adds to the frustration.

In case it is relevant, the "new input system" is enabled.

### PR DESCRIPTION
**Pull request by eliasrg**
Fixes #2509.

After being annoyed at this bug for a long time and finally reporting it, I decided to poke around in the source and found the bug surprisingly easily. To me, that means that the code is well organised!

To be clear, the bug was that `zoomMotion` and `zoomEnd` were called even if zoom gestures were disabled. The existing check only prevented `zoomStart` from having any effect.

### CODE REVIEW

File: src/gui/inputdevices/TouchInputHandler.cpp [hunk 1]
```diff
@@ -93,10 +94,6 @@ void TouchInputHandler::scrollMotion(InputEvent const& event) {
 }
 
 void TouchInputHandler::zoomStart() {
-    if (!inputContext->getSettings()->isZoomGesturesEnabled()) {
-        return;
-    }
-
```
Comment (eliasrg) [inline src/gui/inputdevices/TouchInputHandler.cpp:99]: Not needed anymore, as the check is now in `handleImpl`.

**Comment by Febbe** [comment]
Thanks for your PR. Looked good to me.

**Comment by Febbe** [comment]
This fix is not portable to v1.0.x.
