### PR TITLE
Fix assertion on selection existence when the stylus tip touches the screen

### LINKED ISSUE #4375: Xournal++ crash when "Select region" and tip touches screen.
When trying to select a region with the stylus while holding **Button 2 (Assigned "Select region")** and making the stylus tip touch the screen, Xournal++ crashes.

It does not crash if holding **Button 2** and selecting a region without touching the screen with the stylus.

I have Xournal++ 1.1.2+dev (Octoboer 29th 2022 release)

### PR DESCRIPTION
**Pull request by rolandlo**
Fixes #4375

Here is what happens in `Merging button events with stylus tip events` mode, when the region selection tool is assigned to a stylus button:

- While hovering, press the stylus button -> a button press event is received and a region selection is created (which is also visible on the screen)
- With the tip of the stylus touch the screen -> a button press event is received again and it is falsely asserted that there is no (region) selection => the app crashes.

So the assertion is wrong in `Merging button events with stylus tip events` mode, which explains the fix.

### CODE REVIEW

**Comment by bhennion** [comment]
It's a nice fix, but I think the real bug lies in the input system: when merging input events, we should not call PageView::OnButtonPressEvent twice (one for the button being pressed, one for the tip touching the tablet).
There may be other symptoms of this weird behaviour (typically a memory leak, but also possibly a segfault).

I'd simply add a `bool actionStarted` flag set (and unset) in `StylusInputHandler::handleImpl`, to avoid calling twice `actionStart()`.

**Comment by rolandlo** [comment]
What to do with twice calling `actionEnd()` then? When `actionStart()` is called twice (and only executed the first time), would you wait for `actionEnd()` to be only executed the second time (when the stylus button is released). Currently the behavior is weird indeed. The action is started when the stylus button is pressed while hovering. It is ended when the stylus tip leaves the screen.

We must keep in mind that the `Merging button events with stylus tip events` mode was only designed for styluses that emit the "short sequences" as described in https://github.com/xournalpp/xournalpp/issues/2316#issuecomment-860083264 with regards to stylus button presses (i.e. when you press the button while hovering, no button press event is emitted. You only get the button press event when the stylus tip hits the screen; there is only one button release event when you leave the screen and none when releasing the stylus button).  The behavior is OS-dependent, on Windows all styluses behave like that, see https://github.com/xournalpp/xournalpp/issues/2316#issuecomment-867621727 
For those styluses there is currently no issue with regards to the assertion. There is only an issue when the stylus emits the "long sequences" and `Merging button events with stylus tip events`  is enabled.  We should consider all 2x2 combinations of input sequences (long/short) and `Merging button events with stylus tip events` (true/false), as we can't rely on users to set the checkbox according to their stylus.

**Comment by bhennion** [comment]
I'd say we treat actionEnd similarly: if the flags actionStarted is false, don't trigger an actionEnd. The goal is that downstream, we are sure that each actionStart is matched with an actionEnd.

Also, this `Merging button events with stylus tip events` has been the subject of a lot of many bug reports. It'd be nice if we could figure out whether or not it's needed automatically. Something like WINDOWS || (X11 && TabletPCButton) (and I don't know for MacOs). We could always leave the setting accessible somewhere hidden (in an expert menu or so).

**Comment by rolandlo** [comment]
Maybe we should still merge the present fix until we come up with a more substantial solution, that is tested properly.
The input system is really complex with regards to styluses and stylus buttons, a hot potato to touch. So many different setups have to be considered.

File: src/core/gui/PageView.cpp [hunk 1]
```diff
@@ -382,15 +382,23 @@ auto XojPageView::onButtonPressEvent(const PositionInputData& pos) -> bool {
...
-            this->selection = std::make_unique<RectSelection>(x, y);
-            this->overlayViews.emplace_back(std::make_unique<xoj::view::SelectionView>(
-                    this->selection.get(), this, this->settings->getSelectionColor()));
+            if (!selection) {
+                this->selection = std::make_unique<RectSelection>(x, y);
+                this->overlayViews.emplace_back(std::make_unique<xoj::view::SelectionView>(
+                        this->selection.get(), this, this->settings->getSelectionColor()));
+            } else {
+                assert(settings->getInputSystemTPCButtonEnabled());
+                // the selection has already been created by a stylus button press while the stylus was hovering
```
Comment (Technius) [inline src/core/gui/PageView.cpp:391]: nit: the comment should be folded into the assertion message to make debugging easier.
```suggestion
                assert(settings->getInputSystemTPCButtonEnabled() &&
                       "the selection has already been created by a stylus button press while the stylus was hovering!");
```

File: src/core/gui/PageView.cpp [hunk 2]
```diff
@@ -382,15 +382,23 @@ auto XojPageView::onButtonPressEvent(const PositionInputData& pos) -> bool {
...
-            this->selection = std::make_unique<RegionSelect>(x, y);
-            this->overlayViews.emplace_back(std::make_unique<xoj::view::SelectionView>(
-                    this->selection.get(), this, this->settings->getSelectionColor()));
+            if (!selection) {
+                this->selection = std::make_unique<RegionSelect>(x, y);
+                this->overlayViews.emplace_back(std::make_unique<xoj::view::SelectionView>(
+                        this->selection.get(), this, this->settings->getSelectionColor()));
+            } else {
+                assert(settings->getInputSystemTPCButtonEnabled());
+                // the selection has already been created by a stylus button press while the stylus was hovering
```
Comment (Technius) [inline src/core/gui/PageView.cpp:400]: nit: same here

File: src/core/gui/PageView.cpp (hunk 1 above)
Comment (rolandlo) [reply src/core/gui/PageView.cpp]: Thanks, I applied your suggestion.

**Review by bhennion — APPROVED** [review]
Go ahead. We should open an issue with this double events business so that we don't forget.

**Comment by rolandlo** [comment]
Ok, I will merge and open an issue.
