### PR TITLE
Fix crash on scroll with sidebar preview open

### LINKED ISSUE #2887: Crash when scrolling through PDF with sidebar open on Layer/Layerstack Preview
**Affects versions** :
* OS: Linux
* Desktop environment: Ubuntu 20.04, Gnome X11
* libtk: libgtk: 3.24.20
* Xournal version: Xournal++ 1.1.0+dev
 * Installation method: From source

**To Reproduce**

1. Open PDF with X++.
2. Open sidebar on **Layer preview**.
3. Scroll through PDF. *Note*: It typically crashes within 1-10 seconds of continuous scrolling.
4. X++ crashes.

Random PDF I found online to test on, but I think this problem occurs on any pdf.
[Report_Writing_Process_principles_and_styles.pdf](https://github.com/xournalpp/xournalpp/files/6057657/Report_Writing_Process_principles_and_styles.pdf)

**Additional Details**
* I've gotten this crash many times in the past but this is the first time I was able to find a reproducible patern for it.
* Don't think it occurs for 1.0.20

### PR DESCRIPTION
**Pull request by personalizedrefrigerator**
## Summary
 * A minor scheduler refactoring to use `std::deque`, `std::mutex`, and `std::condition_variable`.
 * Fixes a crash on scrolling through long PDFs with the sidebar layers preview open.
     * The crash was caused by a `nullptr` (or, possibly sometimes not, we weren't using a `std::atomic` to sync the object that was set to null between threads, but it **did** involve accessing freed memory) de-ref in `PreviewJob.cpp`.  
     * I think a part of this was not waiting for preview jobs to finish, possibly freeing the SidebarPreview (that PreviewJob uses) before letting PreviewJobs finish running.
 
Fixes #2887.
See also #2907.

### CODE REVIEW

File: src/control/jobs/XournalScheduler.cpp [hunk 1]
```diff
@@ -12,51 +12,60 @@ XournalScheduler::XournalScheduler()
 XournalScheduler::~XournalScheduler() = default;
 
 void XournalScheduler::removeSidebar(SidebarPreviewBaseEntry* preview) {
-    // Dont await for tasks, as it completly blocks whole program.
-    // Not sure why.
-    removeSource(preview, JOB_TYPE_PREVIEW, JOB_PRIORITY_HIGH, false);
+    removeSource(preview, JOB_TYPE_PREVIEW, JOB_PRIORITY_HIGH, true);
```
Comment (personalizedrefrigerator) [inline src/control/jobs/XournalScheduler.cpp:15]: This change should fix the crash on scroll -- resources in use by a PreviewJob could be freed before the job finished. SidebarPreviewBaseEntry calls XournalScheduler::removeSidebar in its destructor, so if we don't wait for tasks to finish (the true parameter), the sidebar's destructor continues, freeing resources required by a potentially-still-running PreviewJob.

File: src/control/jobs/XournalScheduler.cpp [hunk 2]
```diff
@@ -12,51 +12,60 @@ XournalScheduler::XournalScheduler()
 XournalScheduler::~XournalScheduler() = default;
 
 void XournalScheduler::removeSidebar(SidebarPreviewBaseEntry* preview) {
-    // Dont await for tasks, as it completly blocks whole program.
```
Comment (personalizedrefrigerator) [inline src/control/jobs/XournalScheduler.cpp:15]: I haven't noticed this blocking after making this change (possibly due to the refactor?), but I don't know how often/what caused this blocking to occur...

File: src/control/jobs/Scheduler.h [hunk 3]
```diff
@@ -111,25 +114,31 @@ class Scheduler {
...
 
-    GQueue queueUrgent{};
-    GQueue queueHigh{};
-    GQueue queueLow{};
-    GQueue queueNone{};
+    /**
+     * Jobs of each priority. New jobs
+     * are added to the back of each queue.
+     */
+    std::deque<Job*> queueUrgent{}, queueHigh{}, queueLow{}, queueNone{};
```
Comment (personalizedrefrigerator) [inline src/control/jobs/Scheduler.h:131]: These are `std::deque`s and not `std::queue`s. This is because we use iteration. See https://stackoverflow.com/questions/1259099/stdqueue-iteration.

File: src/control/jobs/XournalScheduler.cpp [hunk 4]
```diff
@@ -66,28 +75,21 @@ void XournalScheduler::removeSource(void* source, JobType type, JobPriority prio
...
         finishTask();
     }
-
-    g_mutex_unlock(&this->jobQueueMutex);
 }
 
 auto XournalScheduler::existsSource(void* source, JobType type, JobPriority priority) -> bool {
     bool exists = false;
-    g_mutex_lock(&this->jobQueueMutex);
+    std::lock_guard<std::mutex> lock(this->jobQueueMutex);
```
Comment (personalizedrefrigerator) [inline src/control/jobs/XournalScheduler.cpp:82]: We could use `std::scoped_lock` here (and in similar locations), but I think I agree with this post: https://stackoverflow.com/posts/60172828/timeline#history_38bf9e37-80b9-49e6-ba53-299043622aea.

File: src/control/jobs/Scheduler.h (hunk 3 above)
Comment (Febbe) [reply src/control/jobs/Scheduler.h:131]: It's good to use std::deque :+1: 
But please don't declare more than one variable of the same type in one line.

File: src/control/jobs/XournalScheduler.cpp [hunk 5]
```diff
@@ -12,51 +12,60 @@ XournalScheduler::XournalScheduler()
...
-    // Not sure why.
-    removeSource(preview, JOB_TYPE_PREVIEW, JOB_PRIORITY_HIGH, false);
+    removeSource(preview, JOB_TYPE_PREVIEW, JOB_PRIORITY_HIGH, true);
 }
 
 void XournalScheduler::removePage(XojPageView* view) { removeSource(view, JOB_TYPE_RENDER, JOB_PRIORITY_URGENT); }
 
 void XournalScheduler::removeAllJobs() {
-    g_mutex_lock(&this->jobQueueMutex);
+    std::lock_guard<std::mutex> lock(this->jobQueueMutex);
```
Comment (Febbe) [inline src/control/jobs/XournalScheduler.cpp:21]: **nitpick:** Very good change :+1: But it's not required in cpp17 to write the template parameter, also use `{}` to initialize objects.
```suggestion
    std::unique_lock guard{this->jobQueueMutex};
```

File: src/control/jobs/XournalScheduler.cpp [hunk 6]
```diff
@@ -12,51 +12,60 @@ XournalScheduler::XournalScheduler()
...
             if (type == JOB_TYPE_PREVIEW || type == JOB_TYPE_RENDER) {
                 job->deleteJob();
-                g_queue_remove(this->jobQueue[priority], job);
+
+                it = queue.erase(it);
+
                 job->unref();
+                job = nullptr;
+            } else {
+                ++it;
```
Comment (Febbe) [inline src/control/jobs/XournalScheduler.cpp:41]: Use `std::erase` (cpp20) or `std::remove_if` in combination with `container.erase`

File: src/control/jobs/XournalScheduler.cpp [hunk 7]
```diff
@@ -12,51 +12,60 @@ XournalScheduler::XournalScheduler()
...
     }
-
-    g_mutex_unlock(&this->jobQueueMutex);
 }
 
 void XournalScheduler::finishTask() {
-    g_mutex_lock(&this->jobRunningMutex);
-    g_mutex_unlock(&this->jobRunningMutex);
+    this->jobRunningMutex.lock();
+    this->jobRunningMutex.unlock();
```
Comment (Febbe) [inline src/control/jobs/XournalScheduler.cpp:49]: We may want to use `std::condition_variable::wait`

Comment (Febbe) [reply src/control/jobs/XournalScheduler.cpp:49]: also, don't call lock/unlock manually
```suggestion
    std::unique_lock guard g{this->jobRunningMutex};
```

File: src/control/jobs/XournalScheduler.cpp (hunk 4 above)
Comment (Febbe) [reply src/control/jobs/XournalScheduler.cpp:82]: why not using `std::unique_lock`?

File: src/control/jobs/XournalScheduler.cpp [hunk 8]
```diff
@@ -12,51 +12,60 @@ XournalScheduler::XournalScheduler()
...
 }
 
 void XournalScheduler::removeSource(void* source, JobType type, JobPriority priority, bool awaitFinishTask) {
-    g_mutex_lock(&this->jobQueueMutex);
+    {
+        std::lock_guard<std::mutex> lock(this->jobQueueMutex);
```
Comment (Febbe) [inline src/control/jobs/XournalScheduler.cpp:54]:
```suggestion
        std::unique_lock lock{this->jobQueueMutex};
```

File: src/control/jobs/XournalScheduler.cpp [hunk 9]
```diff
@@ -12,51 +12,60 @@ XournalScheduler::XournalScheduler()
...
+        auto it = this->jobQueue[priority]->begin();
 
-    int length = g_queue_get_length(this->jobQueue[priority]);
-    for (int i = 0; i < length; i++) {
-        Job* job = static_cast<Job*>(g_queue_peek_nth(this->jobQueue[priority], i));
+        while (it != this->jobQueue[priority]->end()) {
+            Job* job = *it;
+
+            if (job->getType() == type && job->getSource() == source) {
+                it = this->jobQueue[priority]->erase(it);
```
Comment (Febbe) [inline src/control/jobs/XournalScheduler.cpp:62]: use `std::remove_if` and `container.erase`

File: src/control/jobs/XournalScheduler.cpp [hunk 10]
```diff
@@ -66,28 +75,21 @@ void XournalScheduler::removeSource(void* source, JobType type, JobPriority prio
...
 auto XournalScheduler::existsSource(void* source, JobType type, JobPriority priority) -> bool {
     bool exists = false;
-    g_mutex_lock(&this->jobQueueMutex);
+    std::lock_guard<std::mutex> lock(this->jobQueueMutex);
 
-    int length = g_queue_get_length(this->jobQueue[priority]);
-    for (int i = 0; i < length; i++) {
-        Job* job = static_cast<Job*>(g_queue_peek_nth(this->jobQueue[priority], i));
+    for (auto it = this->jobQueue[priority]->begin(); it != this->jobQueue[priority]->end(); ++it) {
+        Job* job = *it;
```
Comment (Febbe) [inline src/control/jobs/XournalScheduler.cpp:85]:
```suggestion
    for(Job* job:this->jobQueue[priority]){
```

Comment (Febbe) [reply src/control/jobs/XournalScheduler.cpp:85]: You could also use `std::find_if` and remove the complete forloop.

**Review by Febbe — CHANGES_REQUESTED** [review]

File: src/control/jobs/Scheduler.cpp [hunk 11]
```diff
@@ -179,78 +170,83 @@ auto g_time_val_diff(GTimeVal* t1, GTimeVal* t2) -> glong {
...
+        SDEBUG("do job: %" PRId64, (uint64_t)job);
         job->execute();
-
         job->unref();
-        g_mutex_unlock(&scheduler->jobRunningMutex);
+        scheduler->jobRunningMutex.unlock();
 
         // unlock the whole scheduler
-        g_mutex_unlock(&scheduler->schedulerMutex);
+        scheduler->schedulerMutex.unlock();
```
Comment (Febbe) [inline src/control/jobs/Scheduler.cpp:249]: only lock mutexes over guards

File: src/control/jobs/XournalScheduler.cpp (hunk 6 above)
Comment (personalizedrefrigerator) [reply src/control/jobs/XournalScheduler.cpp:41]: To me,
```c++
        queue.erase(std::remove_if(queue.begin(), queue.end(),
            [&](Job* job) {
                if (job->getType() == type && job->getSource() == source) {
                    job->deleteJob();
                    job->unref();

                    return true;
                }   

                return false;
            }), queue.end());
```

makes less sense than

```c++
        auto it = this->jobQueue[priority]->begin();

        while (it != this->jobQueue[priority]->end()) {
            Job* job = *it;

            if (job->getType() == type && job->getSource() == source) {
                it = this->jobQueue[priority]->erase(it);

                job->deleteJob();
                job->unref();
                job = nullptr;
            } else {
                ++it;
            }   
        } 
```

because we're calling `job->unref()` in the predicate given to `std::remove_if`. I'm willing to change it to the `queue.erase(std::remove_if(...))` version, if you disagree, though.

File: src/control/jobs/XournalScheduler.cpp (hunk 7 above)
Comment (personalizedrefrigerator) [reply src/control/jobs/XournalScheduler.cpp]: I think locking on the `jobRunningMutex` is better here; we don't want this to block when a job isn't already running.

I made the suggested change, though!

File: src/control/jobs/XournalScheduler.cpp (hunk 5 above)
Comment (personalizedrefrigerator) [reply src/control/jobs/XournalScheduler.cpp]: Nice catch!

File: src/control/jobs/XournalScheduler.cpp (hunk 9 above)
Comment (personalizedrefrigerator) [reply src/control/jobs/XournalScheduler.cpp]: Same comment as above!

File: src/control/jobs/XournalScheduler.cpp (hunk 2 above)
Comment (Febbe) [reply src/control/jobs/XournalScheduler.cpp:15]: Maybe, because u started to use "lock guards" which will automatically unlock the mutex when the guard is destroyed.

File: src/control/jobs/XournalScheduler.cpp (hunk 6 above)
Comment (Febbe) [reply src/control/jobs/XournalScheduler.cpp:41]: We need a refactor of the job system. It should use `std::shared_ptr`s. The actions executed here have to be done for each destruction of Jobs, so they should be moved into the destructor.
Basically `Job::deleteJob()` must be removed. And `Job::unref` has to be handled by a `shared_ptr`.

Comment (Febbe) [reply src/control/jobs/XournalScheduler.cpp:41]: Regarding the while over `remove_if` question. This is indeed ideological. 
In my opinion, a loop whether `while` or `for` does not tell anything about what happens there.

`remove_if` exactly tells the reader, that you want to erase objects from the container.
Also, removing elements from the list while iterating is first prone to bugs, second it can be slow for some containers. (Not in case of deque's).

> I would very much like the Job* job parameter to be a const Job* job in the lambda
Yes, I agree, that the parameter should be `const`, but that's not possible, because the `Job`s are designed wrongly.

> I don't think remove_if guarantees that the predicate will be called exactly once for each job

Even if not: 2*O(1) is still O(1) and 2*O(n) is still O(n) (2*O(n²) = O(n²))...
So the disadvantage would be minimal, but the `erase(remove_if` is designed to make deleting many objects from the list as optimal as possible. It works by moving all the objects to be removed to the end of the list. Then the complete end is removed at once.

File: src/control/jobs/XournalScheduler.cpp (hunk 9 above)
Comment (Febbe) [reply src/control/jobs/XournalScheduler.cpp]: >                     `// I think the best solution would be to use shared_ptrs to track`
                   `// jobs, but I think this is out of the scope of this PR.`

haha lol: exactly what I said above :D

File: src/control/jobs/Scheduler.cpp [hunk 12]
```diff
@@ -77,38 +65,42 @@ void Scheduler::stop() {
...
+
         if (onlyNotRender) {
-            for (GList* l = this->jobQueue[i]->head; l != nullptr; l = l->next) {
-                job = static_cast<Job*>(l->data);
+            for (auto it = queue.begin(); it != queue.end(); ++it) {
+                job = *it;
 
                 if (job->getType() != JOB_TYPE_RENDER) {
-                    g_queue_delete_link(this->jobQueue[i], l);
+                    queue.erase(it);
```
Comment (Febbe) [inline src/control/jobs/Scheduler.cpp:90]: This is a bug, the iterators are invalidated here, so `it` has to be reassigned.

File: src/control/jobs/Scheduler.h [hunk 13]
```diff
@@ -111,25 +114,34 @@ class Scheduler {
...
+    std::deque<Job*> queueLow{};
+    std::deque<Job*> queueNone{};
 
-    GQueue* jobQueue[JOB_N_PRIORITIES]{};
+    /**
+     * Map (JobPriority) -> queue of that priority.
+     * For example,
+     *   jobQueue[JOB_PRIORITY_URGENT] is &queueUrgent.
+     */
+    std::deque<Job*>* jobQueue[JOB_N_PRIORITIES]{};
```
Comment (Febbe) [inline src/control/jobs/Scheduler.h:141]: **nitpick:** use std::array here

File: src/control/jobs/XournalScheduler.cpp (hunk 6 above)
Comment (Febbe) [reply src/control/jobs/XournalScheduler.cpp:41]: Ok just read the [documentation](https://en.cppreference.com/w/cpp/algorithm/remove): You are right, 
```

p | - | unary predicate which returns ​true  if the element should be removed.  The expression p(v) must be convertible to bool for every argument v of type (possibly const) VT, where VT is the value type of ForwardIt, regardless of value category, and must not modify v. Thus, a parameter type of VT&is not allowed, nor is VT unless for VT a move is equivalent to a copy (since C++11). ​
-- | -- | --
```

File: src/control/jobs/XournalScheduler.cpp (hunk 1 above)
Comment (Febbe) [reply src/control/jobs/XournalScheduler.cpp:15]: If it is fixed yet, can this change be reverted?

Comment (personalizedrefrigerator) [reply src/control/jobs/XournalScheduler.cpp:15]: Reverting this should make the issue re-appear. 

In its destructor, `SidebarPreviewBaseEntry` calls `removeSidebar` **before freeing other resources**. **PreviewJobs** expect these resources to be available until they finish. If we return before all jobs using the preview have finished, we have potential use-after-frees -- the preview jobs expect the preview to still exist.

I'm adding a comment to the docstring for `removeSidebar`. Additionally, `removePage` already acts like this -- it waits for running jobs to finish.

File: src/control/jobs/Scheduler.h (hunk 13 above)
Comment (personalizedrefrigerator) [reply src/control/jobs/Scheduler.h:141]: Good idea!

File: src/control/jobs/XournalScheduler.cpp (hunk 1 above)
Comment (personalizedrefrigerator) [reply src/control/jobs/XournalScheduler.cpp]: Reverting the change does break the fix, but it (at least on my machine) isn't causing a crash.
All pages say "Loading..." in the document and in the preview.
The scheduler blocks indefinitely after scrolling through a large PDF with layer preview or layerstack preview open.

I think this is happening because we're trying to lock a freed mutex (line 36):
```c++
 35 void PreviewJob::finishPaint() {
 36     g_mutex_lock(&this->sidebarPreview->drawingMutex);
 37 
 38     if (this->sidebarPreview->crBuffer) {
 39         cairo_surface_destroy(this->sidebarPreview->crBuffer);
 40     }
 41     this->sidebarPreview->crBuffer = crBuffer;
 42 
 43     // The preview widget can be referenced after this is deleted.
 44     // Only it should be referenced in the callback.
 45     GtkWidget* previewWidget = this->sidebarPreview->widget;
 46     g_object_ref(previewWidget);
 47 
 48     Util::execInUiThread([previewWidget]() {
 49         gtk_widget_queue_draw(previewWidget);
 50         g_object_unref(previewWidget);
 51     });
 52 
 53     g_mutex_unlock(&this->sidebarPreview->drawingMutex);
 54 }

```

```c++
 30 SidebarPreviewBaseEntry::~SidebarPreviewBaseEntry() {
 31     this->sidebar->getControl()->getScheduler()->removeSidebar(this);
 32     this->page = nullptr;
 33 
 34     gtk_widget_destroy(this->widget);
 35     this->widget = nullptr;
 36 
 37     if (this->crBuffer) {
 38         cairo_surface_destroy(this->crBuffer);
 39         this->crBuffer = nullptr;
 40     }
 41 }
```

If we don't block on line 31, the SidebarPreviewBaseEntry, and its `drawingMutex`, are freed. This can happen in the middle of a `PreviewJob`, before we attempt to `g_mutex_lock(&this->sidebarPreview->drawingMutex)` the freed mutex.

**Comment by Febbe** [comment]
I think we can add this to 1.1.0 Since it is more a bugfix, than a refactoring.
@personalizedrefrigerator can you add this fix to the changelog and add the refactor of jobs to use `shared_ptr`s to the todo list.

File: src/control/jobs/Job.h [hunk 14]
```diff
@@ -72,6 +72,12 @@ class Job {
      */
     virtual void afterRun();
 
+    /**
+     * Called when the job is to be removed from the
+     * scheduler.
+     */
+    virtual void onDelete();
+
```
Comment (Febbe) [inline src/control/jobs/Job.h:80]: Is this necessary? It violates https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rc-ctor-virtual

**Comment by personalizedrefrigerator** [comment]
> can you add this fix to the changelog

This problem doesn't seem to have been present in 1.0.20 (or was, at least, much harder to trigger). `v1.0.20` only updates the layerstack preview after a user has stopped scrolling and interacted with the current page, and, as such, this crash doesn't seem to happen when quickly scrolling through a document.

> add the refactor of jobs to use `shared_ptr`s to the todo list.

> * [ ] Rework Job system

is already on the to-do list. @Febbe can you edit it (maybe a sub-task) to reflect the refactor to use `shared_ptr`s? (I don't think I can edit the to-do list.)

File: src/control/jobs/Scheduler.cpp [hunk 15]
```diff
@@ -118,41 +110,40 @@ auto Scheduler::getNextJobUnlocked(bool onlyNotRender, bool* hasRenderJobs) -> J
 /**
  * Locks the complete scheduler
  */
-void Scheduler::lock() { g_mutex_lock(&this->schedulerMutex); }
+void Scheduler::lock() { this->schedulerMutex.lock(); }
```
Comment (Febbe) [inline src/control/jobs/Scheduler.cpp:113]: I think this function should return a unique_lock

Comment (Febbe) [reply src/control/jobs/Scheduler.cpp:113]: I think, we also could defer that. I'll add this to the to-do list :)
