### PR TITLE
Fix 1659

### LINKED ISSUE #1659: Crash with many colors
**Affects versions :**
 - `Arch Linux`
 - `X11`
 - `extra/gtk3` `1:3.24.13-1`
 - `extra/xournalpp` `1.0.16-1`

**Describe the bug**
`SEGFAULT`

**To Reproduce**
1. Append the following to `~/.xournalpp/toolbar.ini`

```
[Right hand Pencil Note Taking]
toolbarTop1=NEW,OPEN,SEPARATOR,IMAGE,TEXT,MATH_TEX,SEPARATOR,AUDIO_RECORDING,AUDIO_PAUSE_PLAYBACK,AUDIO_STOP_PLAYBACK,PLAY_OBJECT,SEPARATOR,PRESENTATION_MODE,PAIRED_PAGES,FULLSCREEN,SEPARATOR,ZOOM_FIT,ZOOM_100,ZOOM_SLIDER,ZOOM_OUT,ZOOM_IN,SEPARATOR,DELETE_CURRENT_PAGE,INSERT_NEW_PAGE,SEPARATOR,GOTO_FIRST,GOTO_PAGE,GOTO_NEXT_ANNOTATED_PAGE,GOTO_LAST,PAGE_SPIN,GOTO_BACK,GOTO_NEXT
toolbarTop2=DEFAULT_TOOL,COLOR_SELECT,TOOL_FILL,SEPARATOR,DRAW_CIRCLE,DRAW_COORDINATE_SYSTEM,DRAW_RECTANGLE,DRAW_ARROW,SHAPE_RECOGNIZER,RULER,SEPARATOR,ROTATION_SNAPPING,GRID_SNAPPING,SEPARATOR,VERTICAL_SPACE,SELECT_REGION,SELECT_RECTANGLE,SELECT_OBJECT,SEPARATOR,CUT,COPY,PASTE,SEPARATOR,VERY_THICK,VERY_FINE,FINE,THICK,MEDIUM,SEPARATOR,HILIGHTER,ERASER,PEN,SEPARATOR,SAVE,SEPARATOR,REDO,UNDO
toolbarLeft1=COLOR(0x000000),COLOR(0x500000),COLOR(0x111312),COLOR(0x31302f),COLOR(0x3b3737),COLOR(0x300000),COLOR(0x792929),COLOR(0x44393d),COLOR(0x59636d),COLOR(0x52504e),COLOR(0x234d20),COLOR(0x36802d),COLOR(0x00ff00),COLOR(0x77ab59),COLOR(0xfec52d),COLOR(0xf6cd11),COLOR(0xffff00),COLOR(0xcaff42),COLOR(0xedc951),COLOR(0xf7a541),COLOR(0xeab146),COLOR(0xda825f),COLOR(0xc4975c),COLOR(0xff9b4a),COLOR(0xf38630),COLOR(0xff8000),COLOR(0xf37c00),COLOR(0xfa6900),COLOR(0xe76f3d),COLOR(0xfa5534)
toolbarLeft2=COLOR(0xff0000),COLOR(0xde1300),COLOR(0xd2b028),COLOR(0xcc333f),COLOR(0x991818),COLOR(0x8c2328),COLOR(0x9c3c3e),COLOR(0x96596b),COLOR(0xff3d7f),COLOR(0xff3d7f),COLOR(0xfe4365),COLOR(0xc25264),COLOR(0xff4e50),COLOR(0xec5c56),COLOR(0xf45d4c),COLOR(0xeb6841),COLOR(0xf1754d),COLOR(0xff637d),COLOR(0xf06d61),COLOR(0xa800a8),COLOR(0xff00ff),COLOR(0x00c0ff),COLOR(0x13e6cb),COLOR(0x3fb8af),COLOR(0x3fb8af),COLOR(0x14a888),COLOR(0x00a8d8),COLOR(0x49708a),COLOR(0xf04c81)
name=Right hand Pencil Note Taking
```

2. Run `xournalpp`
3. Use the new toolbar setting `View > Toolbars > Right hand Pencil Note Taking`
4. Select fifth color in `toolbarLeft1`

**Expected behavior**
The color is selected for use with the current tool.

### PR DESCRIPTION
**Pull request by lehmanju**
Closes #1659 

Removes code that used to reset colors when they don't differ much.

### CODE REVIEW

File: src/gui/toolbarMenubar/ColorToolItem.cpp [hunk 1]
```diff
@@ -64,24 +64,13 @@ void ColorToolItem::enableColor(int color) {
...
-            gtk_toggle_tool_button_set_active(GTK_TOGGLE_TOOL_BUTTON(this->item), active);
-        }
-
-        if (active) {
-            this->toolHandler->setColorFound();
-
-            // Only equals more ore less, so we will set it exact to the default color
-            if (this->color != color) {
-                this->toolHandler->setColor(this->color, true);
-            }
```
Comment (Febbe) [inline src/gui/toolbarMenubar/ColorToolItem.cpp]: the function ToolHandler::setColorFound() is not used anymore.
Remove it with the know obsolete colorFound variable.

**Comment by Febbe** [comment]
Maybe make a complete rebase and squash all commits together.
