### PR TITLE
Ensure timeouts are cancelled on exit

### LINKED ISSUE #5942: a bug
### Operating System

Linux

### (Linux only) Distribution

_No response_

### (Linux only) Desktop Environment

_No response_

### (Linux Only) Display Server

X.Org

### Installation Method

PPA

### Xournal++ Version

1.2.3

### libgtk Version

3.24.41

### Bug Description

Date: Mon Oct 14 17:02:59 2024
Error: signal 11
Xournal++ version 1.2.3
Git commit c6970f47 from xournalpp/HEAD
Gtk version 3.24.41

[bt]: (0) /usr/bin/xournalpp(+0xde020) [0x59aac46f0020]
[bt]: (1) /lib/x86_64-linux-gnu/libc.so.6(+0x45320) [0x73214c245320]
[bt]: (2) /lib/x86_64-linux-gnu/libc.so.6(pthread_mutex_lock+0x4) [0x73214c29ffe4]
[bt]: (3) /usr/bin/xournalpp(_ZNK6Layout16getMinimalHeightEv+0x17) [0x59aac47dc847]
[bt]: (4) /usr/bin/xournalpp(+0x14983e) [0x59aac475b83e]
[bt]: (5) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x2a7765) [0x73214d4a7765]
[bt]: (6) /lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_widget_get_preferred_height+0x69) [0x73214d4a7cb9]
[bt]: (7) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x352d2e) [0x73214d552d2e]
[bt]: (8) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x3530de) [0x73214d5530de]
[bt]: (9) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(+0x26360) [0x73214ce8d360]
[bt]: (10) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_object_set_valist+0x1e6) [0x73214ce904b6]
[bt]: (11) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_object_set+0xbd) [0x73214ce9092d]
[bt]: (12) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x293ff3) [0x73214d493ff3]
[bt]: (13) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_cclosure_marshal_VOID__OBJECTv+0x77) [0x73214ce7acf7]
[bt]: (14) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(+0x356bd) [0x73214ce9c6bd]
[bt]: (15) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit_valist+0x41) [0x73214ce9c7c1]
[bt]: (16) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit+0x93) [0x73214ce9c883]
[bt]: (17) /lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_container_remove+0x97) [0x73214d3189d7]
[bt]: (18) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x366270) [0x73214d566270]
[bt]: (19) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_object_run_dispose+0x34) [0x73214ce8b6c4]
[bt]: (20) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x29508e) [0x73214d49508e]
[bt]: (21) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_closure_invoke+0xac) [0x73214ce7c25c]
[bt]: (22) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(+0x44f05) [0x73214ceabf05]
[bt]: (23) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(+0x35591) [0x73214ce9c591]
[bt]: (24) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit_valist+0x41) [0x73214ce9c7c1]
[bt]: (25) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit+0x93) [0x73214ce9c883]
[bt]: (26) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x3662a2) [0x73214d5662a2]
[bt]: (27) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_object_run_dispose+0x34) [0x73214ce8b6c4]
[bt]: (28) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0xc8158) [0x73214d2c8158]
[bt]: (29) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x117293) [0x73214d317293]
[bt]: (30) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_closure_invoke+0xac) [0x73214ce7c25c]
[bt]: (31) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(+0x44f05) [0x73214ceabf05]
[bt]: (32) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(+0x35591) [0x73214ce9c591]
[bt]: (33) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit_valist+0x41) [0x73214ce9c7c1]
[bt]: (34) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit+0x93) [0x73214ce9c883]
[bt]: (35) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x3662a2) [0x73214d5662a2]
[bt]: (36) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_object_run_dispose+0x34) [0x73214ce8b6c4]
[bt]: (37) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0xc8158) [0x73214d2c8158]
[bt]: (38) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x117293) [0x73214d317293]
[bt]: (39) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_closure_invoke+0xac) [0x73214ce7c25c]
[bt]: (40) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(+0x44f05) [0x73214ceabf05]
[bt]: (41) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(+0x35591) [0x73214ce9c591]
[bt]: (42) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit_valist+0x41) [0x73214ce9c7c1]
[bt]: (43) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit+0x93) [0x73214ce9c883]
[bt]: (44) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x3662a2) [0x73214d5662a2]
[bt]: (45) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_object_run_dispose+0x34) [0x73214ce8b6c4]
[bt]: (46) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0xc8158) [0x73214d2c8158]
[bt]: (47) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x117293) [0x73214d317293]
[bt]: (48) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_closure_invoke+0xac) [0x73214ce7c25c]
[bt]: (49) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(+0x44f05) [0x73214ceabf05]
[bt]: (50) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(+0x35591) [0x73214ce9c591]
[bt]: (51) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit_valist+0x41) [0x73214ce9c7c1]
[bt]: (52) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit+0x93) [0x73214ce9c883]
[bt]: (53) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x3662a2) [0x73214d5662a2]
[bt]: (54) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_object_run_dispose+0x34) [0x73214ce8b6c4]
[bt]: (55) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0xc8158) [0x73214d2c8158]
[bt]: (56) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x117293) [0x73214d317293]
[bt]: (57) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_closure_invoke+0xac) [0x73214ce7c25c]
[bt]: (58) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(+0x44f05) [0x73214ceabf05]
[bt]: (59) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(+0x35591) [0x73214ce9c591]
[bt]: (60) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit_valist+0x41) [0x73214ce9c7c1]
[bt]: (61) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit+0x93) [0x73214ce9c883]
[bt]: (62) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x3662a2) [0x73214d5662a2]
[bt]: (63) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_object_run_dispose+0x34) [0x73214ce8b6c4]
[bt]: (64) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x2320be) [0x73214d4320be]
[bt]: (65) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x117293) [0x73214d317293]
[bt]: (66) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_closure_invoke+0xac) [0x73214ce7c25c]
[bt]: (67) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(+0x44f05) [0x73214ceabf05]
[bt]: (68) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(+0x35591) [0x73214ce9c591]
[bt]: (69) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit_valist+0x41) [0x73214ce9c7c1]
[bt]: (70) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit+0x93) [0x73214ce9c883]
[bt]: (71) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x3662a2) [0x73214d5662a2]
[bt]: (72) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_object_run_dispose+0x34) [0x73214ce8b6c4]
[bt]: (73) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x3781d1) [0x73214d5781d1]
[bt]: (74) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x117293) [0x73214d317293]
[bt]: (75) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_closure_invoke+0x14a) [0x73214ce7c2fa]
[bt]: (76) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(+0x44f05) [0x73214ceabf05]
[bt]: (77) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(+0x35591) [0x73214ce9c591]
[bt]: (78) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit_valist+0x41) [0x73214ce9c7c1]
[bt]: (79) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit+0x93) [0x73214ce9c883]
[bt]: (80) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x3662a2) [0x73214d5662a2]
[bt]: (81) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x3730be) [0x73214d5730be]
[bt]: (82) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0xbef0b) [0x73214d2bef0b]
[bt]: (83) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_object_run_dispose+0x34) [0x73214ce8b6c4]
[bt]: (84) /usr/bin/xournalpp(_ZN8GladeGuiD1Ev+0x39) [0x59aac47307f9]
[bt]: (85) /usr/bin/xournalpp(_ZN10MainWindowD0Ev+0xd) [0x59aac473215d]
[bt]: (86) /usr/bin/xournalpp(_ZN11XournalMain3runEiPPc+0x680) [0x59aac46f3630]
[bt]: (87) /lib/x86_64-linux-gnu/libc.so.6(+0x2a1ca) [0x73214c22a1ca]
[bt]: (88) /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x8b) [0x73214c22a28b]
[bt]: (89) /usr/bin/xournalpp(_start+0x25) [0x59aac46ef045]

Try to get a better stacktrace...
[bt] #0 /usr/bin/xournalpp(+0xde6a7) [0x59aac46f06a7]
emergencySave() at ??:?
[bt] #1 /lib/x86_64-linux-gnu/libc.so.6(+0x45320) [0x73214c245320]
__restore_rt at libc_sigaction.c:?
[bt] #2 /lib/x86_64-linux-gnu/libc.so.6(pthread_mutex_lock+0x4) [0x73214c29ffe4]
___pthread_mutex_lock at ./nptl/./nptl/pthread_mutex_lock.c:80 (discriminator 3)
[bt] #3 /usr/bin/xournalpp(_ZNK6Layout16getMinimalHeightEv+0x17) [0x59aac47dc847]
Layout::getMinimalHeight() const at ??:?
[bt] #4 /usr/bin/xournalpp(+0x14983e) [0x59aac475b83e]
int xoj::util::detail::callback_once_impl<&SpinPageAdapter::pageNrSpinChangedTimerCallback, SpinPageAdapter*>(, void*) at ??:?
[bt] #5 /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x2a7765) [0x73214d4a7765]
gtk_size_group_remove_widget at ??:?
[bt] #6 /lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_widget_get_preferred_height+0x69) [0x73214d4a7cb9]
gtk_widget_get_preferred_height at ??:?
[bt] #7 /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x352d2e) [0x73214d552d2e]
gtk_viewport_get_view_window at ??:?
[bt] #8 /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x3530de) [0x73214d5530de]
gtk_viewport_get_view_window at ??:?
[bt] #9 /lib/x86_64-linux-gnu/libgobject-2.0.so.0(+0x26360) [0x73214ce8d360]
g_param_value_validate at ??:?
[bt] #10 /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_object_set_valist+0x1e6) [0x73214ce904b6]
g_object_set_valist at ??:?
[bt] #11 /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_object_set+0xbd) [0x73214ce9092d]
g_object_set at ??:?
[bt] #12 /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x293ff3) [0x73214d493ff3]
gtk_separator_menu_item_new at ??:?
[bt] #13 /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_cclosure_marshal_VOID__OBJECTv+0x77) [0x73214ce7acf7]
g_cclosure_marshal_VOID__OBJECTv at ??:?
[bt] #14 /lib/x86_64-linux-gnu/libgobject-2.0.so.0(+0x356bd) [0x73214ce9c6bd]
g_signal_handlers_destroy at ??:?
[bt] #15 /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit_valist+0x41) [0x73214ce9c7c1]
g_signal_emit_valist at ??:?
[bt] #16 /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit+0x93) [0x73214ce9c883]
g_signal_emit at ??:?
[bt] #17 /lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_container_remove+0x97) [0x73214d3189d7]
gtk_container_remove at ??:?
[bt] #18 /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x366270) [0x73214d566270]
gtk_widget_set_default_direction at ??:?
[bt] #19 /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_object_run_dispose+0x34) [0x73214ce8b6c4]
g_object_run_dispose at ??:?
[bt] #20 /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x29508e) [0x73214d49508e]
gtk_scrolled_window_add_with_viewport at ??:?
[bt] #21 /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_closure_invoke+0xac) [0x73214ce7c25c]
g_closure_invoke at ??:?
[bt] #22 /lib/x86_64-linux-gnu/libgobject-2.0.so.0(+0x44f05) [0x73214ceabf05]
g_pointer_type_register_static at ??:?
[bt] #23 /lib/x86_64-linux-gnu/libgobject-2.0.so.0(+0x35591) [0x73214ce9c591]
g_signal_handlers_destroy at ??:?
[bt] #24 /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit_valist+0x41) [0x73214ce9c7c1]
g_signal_emit_valist at ??:?
[bt] #25 /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit+0x93) [0x73214ce9c883]
g_signal_emit at ??:?
[bt] #26 /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x3662a2) [0x73214d5662a2]
gtk_widget_set_default_direction at ??:?
[bt] #27 /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_object_run_dispose+0x34) [0x73214ce8b6c4]
g_object_run_dispose at ??:?
[bt] #28 /lib/x86_64-linux-gnu/libgtk-3.so.0(+0xc8158) [0x73214d2c8158]
gtk_border_copy at ??:?
[bt] #29 /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x117293) [0x73214d317293]
gtk_container_unset_focus_chain at ??:?
[bt] #30 /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_closure_invoke+0xac) [0x73214ce7c25c]
g_closure_invoke at ??:?

Execution log:

DEBUG   : GLib-GIO :: Using cross-namespace EXTERNAL authentication (this will deadlock if server is GDBus < 2.73.3)
DEBUG   : GLib-GIO :: _g_io_module_get_default: Found default implementation dconf (DConfSettingsBackend) for ‘gsettings-backend’
DEBUG   : GLib-GIO :: _g_io_module_get_default: Found default implementation gvfs (GDaemonVfs) for ‘gio-vfs’
DEBUG   : GLib :: unsetenv() is not thread-safe and should not be used after threads are created
MESSAGE : xopp :: TEXTDOMAINDIR = (null), Platform-specific locale dir = /usr/share/xournalpp/../locale, chosen directory = /usr/share/xournalpp/../locale
INFO    : xopp :: Loading plugins from: /usr/share/xournalpp/plugins
INFO    : xopp :: Loading plugins from: /home/jex/.config/xournalpp/plugins
MESSAGE : xopp :: Plugin "MigrateFontSizes" UI initialized
DEBUG   : -- :: Name com.canonical.AppMenu.Registrar does not exist on the session bus

MESSAGE : xopp :: Autosaving to /home/jex/Dropbox/HS-J/.J-math-框架.autosave.xopp
MESSAGE : xopp :: Autosaving to /home/jex/Dropbox/HS-J/.J-math-框架.autosave.xopp
MESSAGE : xopp :: Autosaving to /home/jex/Dropbox/HS-J/.J-math-框架.autosave.xopp
MESSAGE : xopp :: Autosaving to /home/jex/Dropbox/HS-J/.J-math-框架.autosave.xopp
MESSAGE : xopp :: Autosaving to /home/jex/Dropbox/HS-J/.J-math-框架.autosave.xopp
MESSAGE : xopp :: Autosaving to /home/jex/Dropbox/HS-J/.J-math-框架.autosave.xopp
MESSAGE : xopp :: Autosaving to /home/jex/Dropbox/HS-J/.J-math-框架.autosave.xopp
MESSAGE : xopp :: Autosaving to /home/jex/Dropbox/HS-J/.J-math-框架.autosave.xopp
MESSAGE : xopp :: Autosaving to /home/jex/Dropbox/HS-J/.J-math-框架.autosave.xopp
DEBUG   : xopp :: Pressure-sensitive device omitted pressure this time
DEBUG   : xopp :: Pressure-sensitive device omitted pressure this time
MESSAGE : xopp :: Autosaving to /home/jex/Dropbox/HS-J/.J-math-框架.autosave.xopp
MESSAGE : xopp :: Autosaving to /home/jex/Dropbox/HS-J/.J-math-框架.autosave.xopp
MESSAGE : xopp :: Autosaving to /home/jex/Dropbox/HS-J/.J-math-框架.autosave.xopp
MESSAGE : xopp :: Autosaving to /home/jex/Dropbox/HS-J/.J-math-框架.autosave.xopp
MESSAGE : xopp :: Autosaving to /home/jex/Dropbox/HS-J/.J-math-框架.autosave.xopp
MESSAGE : xopp :: Autosaving to /home/jex/Dropbox/HS-J/.J-math-框架.autosave.xopp
WARNING : xopp :: [Crash Handler] Crashed with signal 11
WARNING : xopp :: [Crash Handler] Wrote crash log to: /home/jex/.cache/xournalpp/errorlogs/errorlog.20241014-170259.log

### Expected Behaviour

hope it will help to make the app better.

### Steps to Reproduce

1

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by bhennion**
Timers started in PageSpinAdaptor and HandRecognition where not cancelled upon exit. This PR fixes that (using RAII).
Possibly fixes #5942 and other cryptic crashlogs with only glib/gtk entries in the backtrace.

I check the other timeouts in the code and they seem to be cancelled properly (I did not refactor them to use RAII).

### CODE REVIEW

File: src/core/gui/widgets/SpinPageAdapter.h [hunk 1]
```diff
@@ -51,7 +53,7 @@ class SpinPageAdapter {
     gulong pageNrSpinChangedHandlerId = 0;
     size_t page = 0;
 
-    guint lastTimeoutId = 0;
+    xoj::util::GSourceURef timout;
```
Comment (rolandlo) [inline src/core/gui/widgets/SpinPageAdapter.h:56]: I guess you intended to call this variable `timeout` here and elsewhere.
```suggestion
    xoj::util::GSourceURef timeout;
```

File: src/core/gui/inputdevices/HandRecognition.cpp [hunk 2]
```diff
@@ -99,6 +100,7 @@ void HandRecognition::reload() {
  * @return true to call again
  */
 auto HandRecognition::enableTimeout(HandRecognition* self) -> bool {
+    self->timer.consume();
```
Comment (rolandlo) [inline src/core/gui/inputdevices/HandRecognition.cpp:103]: Is this really correct (in case `lastPenActionTime < 20`)?

**Review by rolandlo — APPROVED** [review]
LGTM
