### PR TITLE
Fix crash when button pressed while vertical space tool active

### LINKED ISSUE #3967: Assert failing when using vertical space tool
**Affects versions :** latest master, on Archlinux with KDE X11:
```
$ ./install/bin/xournalpp --version
xournalpp 1.1.1+dev
└──libgtk: 3.24.33
```

**Describe the bug**
Failing assert when using (in a weird way, see below) the vertical space tool. This is most likely the symptome of a deeper evil.

```
ERROR:/home/benjamin/xournalpp-fork/src/core/gui/PageView.cpp:320:bool XojPageView::onButtonPressEvent(const PositionInputData&): 'this->verticalSpace' should be nullptr
Bail out! ERROR:/home/benjamin/xournalpp-fork/src/core/gui/PageView.cpp:320:bool XojPageView::onButtonPressEvent(const PositionInputData&): 'this->verticalSpace' should be nullptr

** (xournalpp:78511): WARNING **: 08:30:49.406: [Crash Handler] Crashed with signal 6

** (xournalpp:78511): WARNING **: 08:30:49.407: [Crash Handler] Wrote crash log to: /home/benjamin/.cache/xournalpp/errorlogs/errorlog.20220419-083049.log
```

**To Reproduce**
1. Open a new document (optionally draw a couple of strokes on it)
2. Zoom in
3. With the vertical space tool selected, do
    1. Press the mouse button anywhere on the sheet. NEVER RELEASE THE BUTTON
    2. Press `CTRL`. NEVER RELEASE THE BUTTON
    3. Move up and down a little.
    4. Zoom out (with `CTRL` already down, the scrolling wheel or the `-` key should do it)
    5. Move up and down a little.
    6. Observe the crash.

It works every time here, provided I zoomed enough in at the beginning.
It may be relevant: I'm using a touchpad for those tests.

### PR DESCRIPTION
**Pull request by Technius**
Fixes #3967.

### CODE REVIEW

File: src/core/gui/PageView.cpp [hunk 1]
```diff
@@ -317,7 +317,11 @@ auto XojPageView::onButtonPressEvent(const PositionInputData& pos) -> bool {
         this->eraser->erase(x, y);
         this->inEraser = true;
     } else if (h->getToolType() == TOOL_VERTICAL_SPACE) {
-        g_assert_null(this->verticalSpace);
+        if (this->verticalSpace) {
+            control->getUndoRedoHandler()->addUndoAction(this->verticalSpace->finalize());
+            this->getXournal()->getControl()->getZoomControl()->removeZoomListener(this->verticalSpace);
+            delete this->verticalSpace;
```
Comment (Technius) [inline src/core/gui/PageView.cpp:323]: I copied and pasted this to get the bug fixed, but this should be refactored in a followup PR.

**Review by bhennion — APPROVED** [review]
LGTM! Merge whenever you want
