### PR TITLE
Split geometric shape handlers into Controller-View

### LINKED ISSUE #3579: Possible data race in `StrokeHandler`, `BaseStrokeHandler`, `SplineHandler` (possible others)
In each of the classes `StrokeHandler`, `BaseStrokeHandler` and `SplineHandler`, two parallel accesses to a stroke might trigger SegFaults:

- `draw()` reads to the stroke's point vector
- `onMotionNotifyEvent()` can push new points to the stroke's point vector.

Those functions are not called by the same thread (you can test this with `g_thread_self`).
A writing operation in `onMotionNotifyEvent()` could then trggier a `std::vector` reallocation, thus invalidating iterators used in `draw()`. This could lead to SegFaults

### PR DESCRIPTION
**Pull request by bhennion**
This PR is a proposed first step towards splitting gui/PageView into a view and a controller.
Before this split could be possible, we need to split every tool handler: gui/PageView owns tool handlers which will need to be split into a view, owned by a future view/PageView, and a handler, owned by a future control/PageController.

In this PR, we split the derived classes of BaseStrokeHandler (i.e. the handlers for all geometric shapes -- Rectangle, ellipse, arrow and so on -- but not StrokeHandler). A lot of planning has gone into this PR. I'll try my best to describe the plan, stop me if you object to any parts of it.

- The gui/PageView has a pool of `OverlayView`'s, which should, in time, contain what I call overlays: everything that needs to be painted but is not actually in the page model (e.g. current tools, selections, search results highlighting). For now, this pool contains at most 1 element, corresponding, if there is one, to the active BaseStrokeHandler.
- In order to be able, in a distant future, to have several views of the current document (e.g. to implement #1638 or #2020), each BaseStrokeHandler now has a pool of views, and dispatches repaint requests to the entire pool. Similar things should be implemented for other tools (and other overlays) in the future.
- The OverlayView's inherit from a base class Repaintable, which should, in due time, take over gui/Redrawable. ~~The class Repaintable includes a possible change of coordinates, so that repaint request are always expressed in local coordinates, and transfered up to a parent Repaintable after changing from child coordinates to parent coordinates (think of selections, pages in a layout, or maybe one day, subpages #3684).~~ Edit: This was removed in an iteration of the PR.
- Once this strategy is applied to all other tool handlers (at least StrokeHandler, SplineHandler, SetsquareHandler, Selection, EditSelection, PdfElemSelection, VerticalToolHandler, SearchControl), then we can actually split gui/PageView into a view and a controller. The view view/PageView would inherit from Repaintable, and control/PageController would have a pool of view/PageView's to send repaint/rerender/change requests to.

More specific implementation comments:
- To accomodate the various dispatch needs, a very generic DispatchPool class is implemented. (I'd love feedback on the implementation here)
- ~~The data of the BaseStrokeHandler's is also now protected by a mutex, to address #3579, at least for those tools.~~
    **Edit:** this is actually not necessary, see #3579.
- The class BaseStrokeHandler is renamed to BaseShapeHandler in order to fix its confusing name.

### CODE REVIEW

**Comment by bhennion** [comment]
> I'll have to take a closer look at the last commit. That is quite big and needs some time to focus on all parts.

Of course! No hurry there.

> Regarding the dispatch pool: Please avoid macros whenever possible. They lead to really complex bugs that are amazingly hard to debug.

Yeah. My first attempt had no macro, creating a listener base class, but I failed to make something satisfactory.
The issue is the following. Consider the following code
```
template<class T> class DispatchPool {
    template <typename... Args>
    void dispatch(Args&&... args) const {
        for (auto* v: this->pool) {
            v->on(std::forward<Args>(args)...);
        }
    }
    std::vector<T*> pool;
};
template<class T> class Listener {
    void addToPool(DispatchPool<T>*);
    void removeFromPool();
    DispatchPool<T>* pool;
};

class MyClass: public Listener<MyClass>{
   void on(const MyEventType& event);
};
```
This works fine, except `Listener<T>::addToPool` has to recast its `this` to a `T*` in order to add it to the pool. 
This is unsafe unless there is a way (say a static_assert) to make sure that any instantiation of `Listener<T>` is actually of type `T`. Is there such a way?
Of course, I could resolve to a dynamic_cast, but I'd like to get rid of the oveheads.

**Comment by bhennion** [comment]
I think I found an ok solution for getting rid of the macro DispatchPool.

File: src/core/control/tools/InputHandler.cpp [hunk 1]
```diff
@@ -16,47 +16,44 @@
...
-        xournal(xournal), redrawable(redrawable), page(page), stroke(nullptr) {}
+InputHandler::InputHandler(XournalView* xournal, const PageRef& page): xournal(xournal), page(page) {}
 
 InputHandler::~InputHandler() = default;
 
-/**
- * @return Current editing stroke
- */
-auto InputHandler::getStroke() -> Stroke* { return stroke; }
+auto InputHandler::getStroke() const -> Stroke* { return stroke.get(); }
```
Comment (Febbe) [inline src/core/control/tools/InputHandler.cpp:23]: It looks like, that stroke will never be initialized anymore, how about removing this then?

File: src/util/Range.cpp [hunk 2]
```diff
@@ -1,33 +1,47 @@
...
-    this->y1 = y;
-    this->y2 = y;
-}
+Range::Range():
+        minX(std::numeric_limits<double>::max()),
+        minY(std::numeric_limits<double>::max()),
+        maxX(std::numeric_limits<double>::lowest()),
+        maxY(std::numeric_limits<double>::lowest()) {}
+
+Range::Range(double x, double y): minX(x), minY(y), maxX(x), maxY(y) {}
```
Comment (Febbe) [inline src/util/Range.cpp:14]: Move to header, since this does not rely on another header file (faster compile time).
```suggestion
```

File: src/util/include/util/Range.h [hunk 3]
```diff
@@ -11,11 +11,18 @@
...
+class Rectangle;
+};
 
-class Range {
+class Range final {
 public:
+    Range();  // Empty range
     Range(double x, double y);
-    virtual ~Range();
+    Range(double minX, double minY, double maxX, double maxY);
```
Comment (Febbe) [inline src/util/include/util/Range.h:23]:
```suggestion
    Range(double minX, double minY, double maxX, double maxY): minX(minX), minY(minY), maxX(maxX), maxY(maxY) {}
```

File: src/util/include/util/Range.h [hunk 4]
```diff
@@ -11,11 +11,18 @@
...
+namespace xoj::util {
+template <typename Float>
+class Rectangle;
+};
 
-class Range {
+class Range final {
 public:
+    Range();  // Empty range
     Range(double x, double y);
```
Comment (Febbe) [inline src/util/include/util/Range.h:22]:
```suggestion
    Range(double x, double y): minX(x), minY(y), maxX(x), maxY(y) {}
```

File: src/util/include/util/DispatchPool.h [hunk 5]
```diff
@@ -0,0 +1,83 @@
...
+template <class T>
+class DispatchPool {
+public:
+    using listener_type = T;
+    DispatchPool() = default;
+    DispatchPool(DispatchPool&&) = default;
+    DispatchPool(const DispatchPool&) = default;
+    DispatchPool& operator=(DispatchPool&&) = default;
+    DispatchPool& operator=(const DispatchPool&) = default;
+
```
Comment (Febbe) [inline src/util/include/util/DispatchPool.h:29]: Either make this class final *and* remove all default special member functions, or add a defaulted virtual destructor

File: src/core/view/overlays/ShapeToolView.h [hunk 6]
```diff
@@ -0,0 +1,56 @@
...
+
+namespace xoj::view {
+struct Context;
+class StrokeView;
+
+class ShapeToolView: public OverlayView, public Repaintable, public xoj::util::Listener<ShapeToolView> {
+
+public:
+    ShapeToolView(BaseShapeHandler* toolHandler, const Repaintable* parent);
+    virtual ~ShapeToolView() noexcept;
```
Comment (Febbe) [inline src/core/view/overlays/ShapeToolView.h:32]: Use override instead of virtual. Also, can this class be defined final?
```suggestion
    ~ShapeToolView() override noexcept;
```

File: src/core/view/overlays/ShapeToolView.h [hunk 7]
```diff
@@ -0,0 +1,56 @@
...
+     * @brief Draws the overlay to the given context
+     */
+    void draw(const Context& ctx) const override;
+
+    bool isViewOf(const OverlayBase* overlay) const override;
+
+    /**
+     * Listener interface
+     */
+    static constexpr struct PAINT_REQUEST_t {
```
Comment (Febbe) [inline src/core/view/overlays/ShapeToolView.h:44]: Please use snake_case or PascalCase for types. `snake_case` for STL like/mimic structures. `PascalCase` for Xournal internal classes.

File: src/core/model/OverlayBase.h [hunk 8]
```diff
@@ -0,0 +1,17 @@
...
+ *
+ * @license GNU GPLv2 or later
+ */
+
+#pragma once
+
+class OverlayBase {
+public:
+    virtual ~OverlayBase() = default;
+};
```
Comment (Febbe) [inline src/core/model/OverlayBase.h:17]: What's the use case of an empty base class, without virtual functions to call?

File: src/core/gui/PageView.h [hunk 9]
```diff
@@ -39,8 +41,9 @@ class Element;
 class PositionInputData;
 class Range;
 class TexImage;
+class OverlayBase;
 
-class XojPageView: public Redrawable, public PageListener {
+class XojPageView: public Redrawable, public PageListener, public xoj::view::Repaintable {
```
Comment (Febbe) [inline src/core/gui/PageView.h:46]: We already have Redrawable, why we need an additional Repaintable.

File: src/core/gui/PageView.cpp [hunk 10]
```diff
@@ -302,26 +306,43 @@ auto XojPageView::onButtonPressEvent(const PositionInputData& pos) -> bool {
...
+                break;
+            case DRAWING_TYPE_COORDINATE_SYSTEM:
+                shapeHandler = new CoordinateSystemHandler(this->xournal, this, getPage());
+                break;
+            default:
+                this->inputHandler = new StrokeHandler(this->xournal, this, getPage());
+        }
+        if (shapeHandler) {
+            this->inputHandler = shapeHandler;
+            this->overlayViews.emplace_back(std::make_unique<xoj::view::ShapeToolView>(shapeHandler, this));
```
Comment (Febbe) [inline src/core/gui/PageView.cpp:341]: It really feels bad that we recreate all Handlers, when a button is pressed. This looks like a huge performance loss.
It would be better to either have a std::variant, containing all. Or have them all pre-allocated and only std::exchange them in.

**Review by Febbe — CHANGES_REQUESTED** [review]
I mostly gave language related feedback, since @LittleHuba is the code owner of this part. So he can give you the best feedback on this.

But I have also a question, did you look at the gtk4 drawing-API? They want to replace Cairo with a node based, approach. Therefore, your changes should not increase the porting effort.

File: src/util/Range.cpp [hunk 11]
```diff
@@ -1,33 +1,47 @@
...
+
+void Range::addPadding(double padding) {
+    this->minX -= padding;
+    this->maxX += 2.0 * padding;
+    this->minY -= padding;
+    this->maxY += 2.0 * padding;
+}
 
-auto Range::getY2() const -> double { return this->y2; }
+auto Range::empty() const -> bool { return this->minX > this->maxX || this->minY > this->maxY; }
```
[the remark this answers is not in the document]
Comment (bhennion) [reply src/util/Range.cpp:41]: I'm confused. First, is could be `invalid`, maybe, but certainly not `valid`.
Secondly, a Range corresponds to the area of points (x,y) such that minX <= x <= maX and minY <= y <= maxY, right?
So if minX > maxX then the range represents an empty area of the plane (and the same with y's).
Also, as soon as `range.addPoint` has been called at least once, then `range.empty` will return false (whatever the previous state was).

How is `empty` not a good description then?

File: src/core/model/OverlayBase.h (hunk 8 above)
Comment (bhennion) [reply src/core/model/OverlayBase.h]: Wait no! There was a use case: see `XojPageView::deleteViewOf(OverlayBase*)`. I just needed a common pointer type for everything that will be an overlay (for now, only InputHandler, but more should come).

**Comment by bhennion** [comment]
> But I have also a question, did you look at the gtk4 drawing-API? They want to replace Cairo with a node based, approach. Therefore, your changes should not increase the porting effort.

I don't think this PR influences (in any direction) the difficulty of porting to GTK4. Basically, this just regroups all the drawing operations in view/, but does not change anything to how the painting is done.

There will be more reflection to do when it'll be time to refactor XojPageView itself. I don't quite get how to replace the current buffer (a cairo_surface_t) when passing to GTK4.

File: src/core/model/OverlayBase.h (hunk 8 above)
Comment (Febbe) [reply src/core/model/OverlayBase.h:17]: Then OverlayBase should named ViewBase, and it should require all view functions defined from Repaintable.

File: src/core/view/CoordinateChange.h [hunk 12]
```diff
@@ -0,0 +1,38 @@
...
+
+class Range;
+
+namespace xoj::view {
+
+class CoordinateChange final {
+public:
+    CoordinateChange() = default;
+    CoordinateChange(const utl::Point<double> origin, double scaleFactor);
+    ~CoordinateChange() = default;
```
Comment (Febbe) [inline src/core/view/CoordinateChange.h:24]: Remove default destructor for finalized type
```suggestion
```

**Comment by Febbe** [comment]
For now, Cairo still exist in gtk4, it just requires an extra indirection and must be added as node into the drawing tree. But it might get deprecated some time.   
The larger problem is, that gtk4 globalized input. Now every input is caught globally and is fed into gtk-input-controlers, which then determine, if they have to accept the event. Multiple Controllers can accept the same event, and it is also incompatible with the current approach. The old approach to get events from a widget does not work anymore. Widgets don't emit events.

File: src/core/gui/PageView.cpp (hunk 10 above)
Comment (Febbe) [reply src/core/gui/PageView.cpp:341]: It's often safer to recreate, than to reset a structure, but I would just call something like this:

`*handler = Handler{};`
instead of `handler = new Handler{};`
or `new(handler) Handler{};`

File: src/core/gui/PageView.h (hunk 9 above)
Comment (Febbe) [reply src/core/gui/PageView.h:46]: Ok, how about renaming `Redrawable` -> `LegacyRedrawable` and `Repaintable` -> `Redrawable` ? :D

Comment (Febbe) [reply src/core/gui/PageView.h:46]: At least the name wouldn't be "stupid" and the other name states, that the type is about to replaced some time.

File: src/core/model/OverlayBase.h (hunk 8 above)
Comment (bhennion) [reply src/core/model/OverlayBase.h:17]: No, it's not a view. It's a base for some controllers: those controllers which can have one or more views. This includes all the tool controllers (by that I mean things in control/tools), but also SearchControl for instance (to highlight the search results).

It is obviously not clear or we wouldn't be having this discussion, so something needs to be done to clarify the situation. Not sure what yet.

**Comment by bhennion** [comment]
> For now, Cairo still exist in gtk4, it just requires an extra indirection and must be added as node into the drawing tree. But it might get deprecated some time.

As long as [GtkDrawingArea](https://docs.gtk.org/gtk4/class.DrawingArea.html) relies on cairo for its draw function, we are safe.

> The larger problem is, that gtk4 globalized input. Now every input is caught globally and is fed into gtk-input-controlers, which then determine, if they have to accept the event. Multiple Controllers can accept the same event, and it is also incompatible with the current approach. The old approach to get events from a widget does not work anymore. Widgets don't emit events.

This seems like a problem for the input system rather then for our tool handlers, does it not?

**Comment by Febbe** [comment]
> This seems like a problem for the input system rather then for our tool handlers, does it not?

Those tool handlers rely on, or are part of, the input system.

**Comment by bhennion** [comment]
> Those tool handlers rely on, or are part of, the input system.

Of course they rely on it. My point was: whatever is in gui/inputdevices should play the role of an abstraction layer, so that whatever relies on it should not be touched by any changes in the library.

**Comment by bhennion** [comment]
I refactored the view classes a little bit, for better code sharing between this and the classes to come in #4158.

**Comment by Technius** [comment]
This is rather large, so I'll take a look over the week.

**Comment by bhennion** [comment]
Just rebased after the preliminary code cleanups were merged into master. I also added some documentation in the code.
@Technius Thanks a lot!
I think some files deserve more attention than the rest of them: namely util/DispatchPool, core/control/BaseShapeHandler and core/view/overlays/*. This is where the actual View-Controller stplitting happens.

**Comment by bhennion** [comment]
To help with the reviewing of this PR, as well as #4158, #4159 and future PR's, here is a very coarse diagram of the intended structure:
ViewRefactor

This PR, and #4158 and #4159 concern only the blue (OverlayView's) and green (Overlay's, including InputHandler -- which IMO should be renamed) portions.


Now, in the last commit [e85c908](https://github.com/xournalpp/xournalpp/pull/4137/commits/e85c908690ba31d743d156fd98d11b5013d985ca), I fixed a blinking problem upon shape finalization. I do not like the way this is done, so I'd be delighted if someone had a better idea. I'll describe the issue in detail in a second post.

**Comment by bhennion** [comment]
@xournalpp/core As I explained in #3579, I made a mistake then and never rechecked. Let it be a lesson for me.

In any case, I need to remove the mutexes from this PR. Don't review it just yet... I'm sorry about that.

**Comment by bhennion** [comment]
> In any case, I need to remove the mutexes from this PR. Don't review it just yet... I'm sorry about that.

Well... Maybe I should not remove the mutexes just yet. There may be multiple threads involved if and when we allow several views of the same document.

File: src/core/view/overlays/BaseShapeOrSplineToolView.cpp [hunk 13]
```diff
@@ -0,0 +1,84 @@
...
+        return mask.cr;
+    } else {
+        cairo_set_line_cap(cr, CAIRO_LINE_CAP_ROUND);
+        cairo_set_line_join(cr, CAIRO_LINE_JOIN_ROUND);
+        cairo_set_line_width(cr, this->strokeWidth);
+
+        const double* dashes = nullptr;
+        int dashCount = 0;
+        this->lineStyle.getDashes(dashes, dashCount);
+        assert((dashCount == 0 && dashes == nullptr) || (dashCount != 0 && dashes != nullptr));
```
Comment (Technius) [inline src/core/view/overlays/BaseShapeOrSplineToolView.cpp:59]: Same concern here about the assertion.

File: src/core/view/overlays/BaseStrokeToolView.h [hunk 14]
```diff
@@ -0,0 +1,61 @@
...
+#include "model/LineStyle.h"
+#include "util/Color.h"
+#include "view/overlays/OverlayView.h"
+
+class Stroke;
+
+namespace xoj::view {
+class Repaintable;
+
+class BaseStrokeToolView: public OverlayView {
```
Comment (Technius) [inline src/core/view/overlays/BaseStrokeToolView.h:25]: Needs a doc comment.

What are intended subclasses of `BaseStrokeToolView` other than the `BaseShapeOrSpineToolView` family?

File: src/core/view/overlays/BaseStrokeToolView.h [hunk 15]
```diff
@@ -0,0 +1,61 @@
...
+    /**
+     * @brief All that's required to draw a stroke in cairo
+     */
+    cairo_operator_t cairoOp;
+    Color strokeColor;
+    LineStyle lineStyle;
+    double strokeWidth;
+
+
+    class Mask {
```
Comment (Technius) [inline src/core/view/overlays/BaseStrokeToolView.h:45]: Needs a doc comment.

File: src/core/view/overlays/BaseStrokeToolView.cpp [hunk 16]
```diff
@@ -0,0 +1,64 @@
...
+    const int xOffset = -static_cast<int>(std::floor(visibleRange.minX * scale));
+    const int yOffset = -static_cast<int>(std::floor(visibleRange.minY * scale));
+    const int width = static_cast<int>(std::ceil(visibleRange.maxX * scale)) + xOffset;
+    const int height = static_cast<int>(std::ceil(visibleRange.maxY * scale)) + yOffset;
+
+    return Mask(width, height, xOffset, yOffset, scale);
+}
+
+BaseStrokeToolView::Mask::Mask(int width, int height, int xOffset, int yOffset, double scale) {
+    cairo_surface_t* surf = cairo_image_surface_create(CAIRO_FORMAT_A8, width, height);
```
Comment (Technius) [inline src/core/view/overlays/BaseStrokeToolView.cpp:47]: For performance reasons, we might want to make it possible to use something like [`cairo_surface_create_similar()`](https://www.cairographics.org/manual/cairo-cairo-surface-t.html#cairo-surface-create-similar), otherwise we might be forcing the image buffer to be allocated in Xournal++'s heap instead of e.g. the display server or VRAM etc.

File: src/util/include/util/DispatchPool.h [hunk 17]
```diff
@@ -0,0 +1,80 @@
...
+class Listener {
+private:
+    // Keep the constructor private: only T can inherit Listener<T>
+    Listener() = default;
+    friend T;
+
+    using pool_type = xoj::util::DispatchPool<T>;
+
+public:
+    void registerToPool(const std::shared_ptr<pool_type>& newpool) {
```
Comment (Technius) [inline src/util/include/util/DispatchPool.h:62]: Doc comment should mention that this will remove it from the current pool.

File: src/util/include/util/DispatchPool.h [hunk 18]
```diff
@@ -0,0 +1,80 @@
...
+    }
+
+    bool empty() const { return pool.empty(); }
+
+private:
+    std::vector<listener_type*> pool;
+};
+
+template <class T>
+class Listener {
```
Comment (Technius) [inline src/util/include/util/DispatchPool.h:53]: Needs a doc comment.

Is my understanding of this correct: Listener is a CRTP style class. An example implementation would be `class MyListener : public Listener<MyListener> { ... }`. Subclasses of Listener are required to implement `on()` (which can potentially be overloaded), which can then be invoked by calling the `DispatchPool<MyListener>::dispatch()` method. The fun part is that because this is templated, we can abuse types like `std::enable_if_t`.

However, it seems like a concrete subclass can only implement `Listener<...>` once. Is this a problem, or do you think the overlays/views will each only be implementing one listener?

File: src/util/include/util/DispatchPool.h [hunk 19]
```diff
@@ -0,0 +1,80 @@
...
+#pragma once
+
+#include <algorithm>
+#include <cassert>
+#include <memory>
+#include <vector>
+
+namespace xoj::util {
+template <class T>
+class DispatchPool final {
```
Comment (Technius) [inline src/util/include/util/DispatchPool.h:21]: Needs a doc comment.

I initially found the type parameter name `T` to be confusing, until I saw the `using listener_type = T` line below. I would suggest renaming `T` to something more understandable like `ListenerT`.

**Review by Technius — COMMENTED** [review]
Thanks for the work, this is sorely needed. I think the overall design looks reasonable. I haven't checked everything thoroughly, but I did look over most of the major parts.

* I have a few questions about the DispatchPool/Listener thing, as well as some of the overlay code (see below).
* I mentioned some spots that I think need doc comments, but it would probably be better to defer writing those until the overall design is finalized.

File: src/core/view/overlays/BaseShapeOrSplineToolView.cpp [hunk 20]
```diff
@@ -0,0 +1,84 @@
...
+        BaseStrokeToolView(parent, safeGetStroke(toolHandler)),
+        fillingAlpha(getFillingAlpha(toolHandler)),
+        mask(this->fillingAlpha != 0.0 && safeGetStroke(toolHandler).getToolType() == STROKE_TOOL_HIGHLIGHTER ?
+                     createMask() :
+                     Mask()) {
+    if (mask) {
+        const double* dashes = nullptr;
+        int dashCount = 0;
+        this->lineStyle.getDashes(dashes, dashCount);
+        assert((dashCount == 0 && dashes == nullptr) || (dashCount != 0 && dashes != nullptr));
```
[the remark this answers is not in the document]
Comment (bhennion) [reply src/core/view/overlays/BaseShapeOrSplineToolView.cpp:33]: Yes to everything!

File: src/core/view/overlays/BaseStrokeToolView.h (hunk 14 above)
Comment (bhennion) [reply src/core/view/overlays/BaseStrokeToolView.h:25]: There will be StrokeToolView, in #4158

File: src/util/include/util/DispatchPool.h (hunk 18 above)
Comment (bhennion) [reply src/util/include/util/DispatchPool.h:53]: > Is my understanding of this correct: Listener is a CRTP style class. An example implementation would be `class MyListener : public Listener<MyListener> { ... }`. Subclasses of Listener are required to implement `on()` (which can potentially be overloaded), which can then be invoked by calling the `DispatchPool<MyListener>::dispatch()` method. The fun part is that because this is templated, we can abuse types like `std::enable_if_t`.

Yes, you are correct.

> However, it seems like a concrete subclass can only implement `Listener<...>` once. Is this a problem, or do you think the overlays/views will each only be implementing one listener?

If a class needs to be two kinds of listeners, you can do that
```
class A : public Listener<A> {...};  // define virtual functions void on(...); in here
class B : pulbic Listener<B> {...};  // define virtual functions void on(...); in here - types must differ from the ones in A
class C : public A, public B {...};    // overload everything here
```
This ain't a big deal, because both `A` and `B` should be also used separately elsewhere (otherwise, don't split...).

File: src/core/view/overlays/BaseStrokeToolView.cpp (hunk 16 above)
Comment (bhennion) [reply src/core/view/overlays/BaseStrokeToolView.cpp:47]: TBH, I have no idea which of cairo's surfaces are stored where. The documentation does not mention this at all.
They also do not mention performance differences. Do you have a source (or benchmarks, or so) that shows a difference?
In an ideal world, I agree that `cairo_surface_create_similar` should give us the best surface for the job...

Performance aside, the downside of `cairo_surface_create_similar` is that we need a cairo_surface_t instance upon creation of the mask.
I guess this can be done, by initializing the mask during the first call to ShapeToolView::draw.

File: src/core/control/tools/RectangleHandler.cpp [hunk 21]
```diff
@@ -4,72 +4,66 @@
...
+    shape.emplace_back(p1);
+    shape.emplace_back(p1.x, p2.y);
+    shape.emplace_back(p2);
+    shape.emplace_back(p2.x, p1.y);
+    shape.emplace_back(p1);
+
+    Range rg(p1.x, p1.y);
+    rg.addPoint(p2.x, p2.y);
+
+    return {shape, rg};
```
[the remark this answers is not in the document]
Comment (bhennion) [reply src/core/control/tools/RectangleHandler.cpp:68]: I was counting on some (hypothetical) copy elision kind of compiler optimisation here. I assumed that an `std::move` would block such optimisation.
I can always make the pair before, and emplace points into `first`, but that's definitely less readable.

File: src/core/control/tools/EllipseHandler.cpp [hunk 22]
```diff
@@ -2,95 +2,84 @@
...
+        radiusY = height;
+        center_x = this->startPoint.x;
+        center_y = this->startPoint.y;
+    }
+
+    // set resolution proportional to radius
+    auto npts = static_cast<size_t>(std::round((std::abs(radiusX) + std::abs(radiusY)) * 2.0));
+    if (npts < 24) {
+        npts = 24;  // min. number of points
+    }
```
[the remark this answers is not in the document]
Comment (bhennion) [reply src/core/control/tools/EllipseHandler.cpp:71]: Changed by an optimal formula for the number of points.

File: src/core/view/overlays/BaseStrokeToolView.cpp (hunk 16 above)
Comment (bhennion) [reply src/core/view/overlays/BaseStrokeToolView.cpp]: I just pushed a commit making the masks through `cairo_surface_create_similar` and printing out the surface type in a terminal.
FYI, on my laptop: KDE X11 gives xlib surfaces while KDE Wayland gives image surfaces.

I'd be interested if you get different kind of surfaces depending on the OS, DE and x11 or wayland. To get this information in a terminal, you need to draw a filled highlighter shape (e.g. highlighter, with filling, rectangle).

Comment (rolandlo) [reply src/core/view/overlays/BaseStrokeToolView.cpp]: On Ubuntu 22.04 wayland I get `Creating mask of type: image`

Comment (rolandlo) [reply src/core/view/overlays/BaseStrokeToolView.cpp]: On Ubuntu 22.04 x11 I get `Creating mask of type: xlib`

Comment (rolandlo) [reply src/core/view/overlays/BaseStrokeToolView.cpp]: On MS Windows 10 I get `Creating mask of type: win32`

Comment (rolandlo) [reply src/core/view/overlays/BaseStrokeToolView.cpp]: On MacOS Catalina I get `Creating mask of type: quartz`
This may change when Gtk 3.24.35 is released and updated in `gtk-osx`.

Comment (bhennion) [reply src/core/view/overlays/BaseStrokeToolView.cpp]: Thanks a lot @rolandlo for the data!

I run some benchmarks I found [here](https://openbenchmarking.org/test/pts/cairo-demos) (only relevant for X11, I think), and toyed around. It turns out, the benefits of using `cairo_surface_create_similar` over `cairo_surface_create_similar_image` (on xlib surfaces) are enormous. For instance
```
$./flower-demo-xlib --benchmark
flowers: 125.03 fps
```
vs
```
$./flower-demo-image --benchmark
flowers: 14.42 fps
```
I don't quite know where things get so much slower, probably the under-use of graphics acceleration.

Anyway, this seems to be saying that we need to replace most occurences of `cairo_image_surface_create` by a `cairo_surface_create_similar`, as @Technius was suggesting. It will be pretty complicated to know the kind of surfaces we need in all the places we use image surfaces though.

I'm getting out of the PR's scope :)

**Comment by bhennion** [comment]
Here are the last changes I made:

1. Split off the mask class to a dedicated file. Then, in future PR's, we can use it for every mask or surface buffer (e.g. in StrokeView, PageView, VerticalToolHandler).
2. I removed the mutex. As I mentionned above, there is actually oly one thread involved. The structure is not changed, so putting the mutex back in if we need to later won't be hard at all.

This is ready for another round of review, for whoever feels like it :)

File: src/core/view/StrokeViewHelper.cpp [hunk 23]
```diff
@@ -0,0 +1,64 @@
...
+ */
+double xoj::view::StrokeViewHelper::drawWithPressure(cairo_t* cr, const std::vector<Point>& pts,
+                                                     const LineStyle& lineStyle, double dashOffset) {
+    const double* dashes = nullptr;
+    int dashCount = 0;
+    lineStyle.getDashes(dashes, dashCount);
+    assert((dashCount == 0 && dashes == nullptr) || (dashCount != 0 && dashes != nullptr));
+
+    if (dashes) {
+        for (const auto& [p, q]: PairView(pts)) {
```
[the remark this answers is not in the document]
Comment (Technius) [reply src/core/view/StrokeViewHelper.cpp:53]: Makes sense. Although for the branching issue, the pattern seems simple enough that modern CPU branch predictors should be able to optimize it.

File: src/util/include/util/DispatchPool.h [hunk 24]
```diff
@@ -0,0 +1,111 @@
...
+
+#include <algorithm>
+#include <cassert>
+#include <memory>
+#include <vector>
+
+namespace xoj::util {
+
+/**
+ * @brief Generic template for dispatchers.
```
Comment (Technius) [inline src/util/include/util/DispatchPool.h:22]:
```suggestion
 * @brief Utility class for dispatching a method call to multiple "listeners".
```

File: src/util/include/util/DispatchPool.h [hunk 25]
```diff
@@ -0,0 +1,111 @@
...
+ * The listeners must implement functions
+ *      void on(Arg&&...);
+ * that the dispatcher will call through dispatch().
+ */
+template <class ListenerT>
+class DispatchPool final {
+public:
+    using listener_type = ListenerT;
+
+    template <typename... Args>
```
Comment (Technius) [inline src/util/include/util/DispatchPool.h:33]: Needs a doc comment.
```suggestion
    /**
     * @brief Invokes the `on()` method of all registered `ListenerT`s.
     */
    template <typename... Args>
```

File: src/util/include/util/DispatchPool.h [hunk 26]
```diff
@@ -0,0 +1,111 @@
...
+    void dispatch(Args&&... args) const {
+        for (auto* v: this->pool) {
+            v->on(std::forward<Args>(args)...);
+        }
+    }
+
+    void add(listener_type* v) {
```
Comment (Technius) [inline src/util/include/util/DispatchPool.h:40]:
```suggestion
    /**
     * The listener cannot already be registered.
     */
    void add(listener_type* v) {
```

File: src/util/include/util/DispatchPool.h [hunk 27]
```diff
@@ -0,0 +1,111 @@
...
+
+/**
+ * @brief CRTP-style class for listener
+ * Usage:
+ *  class A: Listener<A> {
+ *      (virtual) ~A() { unregisterFromPool(); }
+ *      void on(...);  // Signal receiver
+ *  };
+ *
+ * WARNING: Always unregisterFromPool() in derived class destructor.
```
Comment (Technius) [inline src/util/include/util/DispatchPool.h:68]: This seems like a pretty big caveat. Would it be a big problem to add a virtual destructor in Listener that automatically does this?

File: src/core/view/Mask.cpp [hunk 28]
```diff
@@ -0,0 +1,148 @@
...
+#include <cassert>
+#include <cmath>
+
+#include <cairo.h>
+
+#include "util/Range.h"
+
+using namespace xoj::view;
+
+// #define DEBUG_MASKS
```
Comment (Technius) [inline src/core/view/Mask.cpp:12]:
```suggestion
```

File: src/core/view/Mask.h [hunk 29]
```diff
@@ -0,0 +1,34 @@
...
+#pragma once
+
+#include <cairo.h>
+
+#include "util/Range.h"
+#include "util/raii/CairoWrappers.h"
+
+namespace xoj::view {
+
+class Mask {
```
Comment (Technius) [inline src/core/view/Mask.h:21]: Needs doc comments.

Thanks for adding this, we could probably simplify several of the tool handlers with this.

In a follow-up: it would also be useful to have the ability to resize the cairo_surface (such as is done in VerticalToolHandler).

File: src/util/include/util/DispatchPool.h (hunk 27 above)
Comment (bhennion) [reply src/util/include/util/DispatchPool.h:68]: I'd rather not impose a vtable on every listener type.
More importantly, this would open a data race upon destruction:
the base class gets destroyed last, so in a multithreading situation, a function on() of the derived class could be called (by the dispatcher) between the destruction of the derived class and before the destruction of the base (hence the call to unregisterFromPool()).

I don't have a proper solution for this.

File: src/core/view/Mask.h (hunk 29 above)
Comment (bhennion) [reply src/core/view/Mask.h:21]: > In a follow-up: it would also be useful to have the ability to resize the cairo_surface (such as is done in VerticalToolHandler).

Yes I agree. Also in the other tools handlers actually: the tool handlers should listen to zoom or scroll events and adapt their masks accordingly, like the VerticalToolHandler does.

Comment (bhennion) [reply src/core/view/Mask.h:21]: Also: This class could be placed in util rather than core/view. Not sure which makes more sense.

File: src/core/model/Stroke.cpp [hunk 30]
```diff
@@ -302,6 +302,22 @@ Point Stroke::getPoint(PathParameter parameter) const {
 
 auto Stroke::getPoints() const -> const Point* { return this->points.data(); }
 
+void Stroke::setPointVector(const std::vector<Point>& other, const Range* const snappingBox) {
+    this->points = other;
+    if (!snappingBox || this->points.empty() || this->points.front().z != Point::NO_PRESSURE) {
+        // We cannot deduce the bounding box from the snapping box if the stroke has pressure values
+        this->sizeCalculated = false;
+    } else {
+        assert(snappingBox->isValid());
```
Comment (rolandlo) [inline src/core/model/Stroke.cpp:311]: This assertion is not satisfied for a horizontal or vertical straight line (drawn with the "Line" drawing type, with grid snapping on) and the app crashes.

Comment (bhennion) [reply src/core/model/Stroke.cpp:311]: Thanks for the catch! I'll get back to this PR in a moment.

**Comment by bhennion** [comment]
Hey there!

I cleaned up the includes here and there, and tidied the commit tree. @Technius @Febbe @LittleHuba: would any of you give this another review or do you think/trust it is good to go?

File: src/core/gui/PageView.h [hunk 31]
```diff
@@ -61,12 +61,19 @@ class XojPageView: public LegacyRedrawable, public PageListener, public xoj::vie
...
+     */
+    void drawAndDeleteToolView(xoj::view::ToolView* v, const Range& rg) override;
+
     int getDPIScaling() const override;
     double getZoom() const override;
     Range getVisiblePart() const override;
 
     double getWidth() const override;
     double getHeight() const override;
+    //
```
Comment (Technius) [inline src/core/gui/PageView.h:76]: nit: unnecessary comment

File: src/core/view/Repaintable.h [hunk 32]
```diff
@@ -41,5 +42,11 @@ class Repaintable {
      * @brief Flag a region as dirty. Dirty regions will get redrawn at the next screen refresh.
      */
     virtual void flagDirtyRegion(const Range& rg) const = 0;
+
+    /**
+     * @brief Remove a tool view repaint the given range
```
Comment (Technius) [inline src/core/view/Repaintable.h:47]:
```suggestion
     * @brief Remove a tool view and repaint the given range
```

File: src/core/view/overlays/ShapeToolView.h [hunk 33]
```diff
@@ -43,6 +43,14 @@ class ShapeToolView final: public BaseShapeOrSplineToolView, public xoj::util::L
     } FLAG_DIRTY_REGION = {};
     void on(FlagDirtyRegionRequest, const Range& rg);
 
+    /**
+     * @brief Called before the corresponding BaseShapeHandler's destruction
+     * @param rg The bounding box of the entire stroke
+     */
```
Comment (Technius) [inline src/core/view/overlays/ShapeToolView.h:49]: Shouldn't the doc comment go on the function? Also, I think the `Finalization` struct itself also needs a doc comment.

File: src/util/include/util/DispatchPool.h [hunk 34]
```diff
@@ -39,6 +39,21 @@ class DispatchPool final {
...
+     * The deleteOn() is supposed to delete the listener
+     * (or at the very least remove any reference to the dispatcher in the listener)
+     */
+    template <typename... Args>
+    void dispatchAndClear(Args&&... args) const {
+        // We cannot iterate on the this->pool: the listener's deletion would trigger calls to DispatchPool::remove()
+        // leading to possible segfaults.
+        auto p = std::move(this->pool);
+        for (auto* v: p) {
+            v->deleteOn(std::forward<Args>(args)...);
```
Comment (Technius) [inline src/util/include/util/DispatchPool.h:54]: Unless I'm missing something, shouldn't `deleteOn` also be on the list of required methods in the class's doc comment?

**Review by Technius — APPROVED** [review]
I assume that you didn't modify anything when you rebased and only looked at the last too commits. LGTM if so, besides one small assert issue + some minor documentation issues.

**Comment by bhennion** [comment]
> I assume that you didn't modify anything when you rebased

That is correct!

I pushed a fixup commit with your comments. Thanks for the review!!

Should we plan on merging this then?

**Comment by Technius** [comment]
Yes, I think this can be merged unless other people have any objections.

**Comment by bhennion** [comment]
Merging this in 5 days, unless someone objects.
