### PR TITLE
Check device hash for input sequences

### LINKED ISSUE #5116: Crash when drawing pen and mouse triggered at the same time.
### Operating System

Linux

### (Linux only) Distribution

Arch

### (Linux only) Desktop Environment

GNOME

### (Linux Only) Display Server

X.Org

### Installation Method

Aur

### Xournal++ Version

xournalpp 1.2.1

### libgtk Version

xournalpp 1.2.1

### Bug Description

If I press down with a drawing tablet pen at the same time as pressing down with a mouse pen, it causes the software to crash.

### Expected Behaviour

To ignore the input of the mouse and not crash.

### Steps to Reproduce

1. Get your tablet pen and mouse
2. Click on the mouse at the same time as pressing down with the drawing pen

### Additional Context

DEBUG   : GLib-GIO :: Using cross-namespace EXTERNAL authentication (this will deadlock if server is GDBus < 2.73.3)
DEBUG   : GLib-GIO :: _g_io_module_get_default: Found default implementation gvfs (GDaemonVfs) for â€˜gio-vfsâ€™
DEBUG   : GLib :: unsetenv() is not thread-safe and should not be used after threads are created
MESSAGE : xopp :: TEXTDOMAINDIR = (null), Platform-specific locale dir = /usr/share/xournalpp/../locale, chosen directory = /usr/share/xournalpp/../locale
INFO    : xopp :: Loading plugins from: /usr/share/xournalpp/plugins
INFO    : xopp :: Loading plugins from: /home/samio/.config/xournalpp/plugins
MESSAGE : xopp :: Plugin "MigrateFontSizes" UI initialized
DEBUG   : GdkPixbuf :: gdk_pixbuf_from_pixdata() called on:
DEBUG   : GdkPixbuf :: 	Encoding raw
DEBUG   : GdkPixbuf :: 	Dimensions: 20 x 25
DEBUG   : GdkPixbuf :: 	Rowstride: 80, Length: 2024
DEBUG   : GdkPixbuf :: 	Copy pixels == false
DEBUG   : GdkPixbuf :: gdk_pixbuf_from_pixdata() called on:
DEBUG   : GdkPixbuf :: 	Encoding raw
DEBUG   : GdkPixbuf :: 	Dimensions: 20 x 25
DEBUG   : GdkPixbuf :: 	Rowstride: 80, Length: 2024
DEBUG   : GdkPixbuf :: 	Copy pixels == false
WARNING : xopp :: Found a stroke with some non-positive pressure values. Removing the affected points.

### PR DESCRIPTION
**Pull request by bhennion**
This PR adds a device hash and rejects input events that have not been issued by the pointing device that started a sequence.
Fixes #5116, possibly #5087 if this was the only source of negative pressure values.

This deserves some testing on various devices.

### CODE REVIEW

**Comment by Febbe** [comment]
Pretty weird, I checked the device name and it's class on my laptop and they were the same for both events with and without pressure

**Comment by bhennion** [comment]
So you still get a negative pressure assertion failure with this patch?

**Comment by Febbe** [comment]
Not yet, but at the time I tried to debug it, all events passed to the PenInputhandler were from the same device.

**Comment by bhennion** [comment]
There may be another source for #5087 then.
Another test may be: are the events processed by the same instance of PenInputHandler? (there are several of them)

**Comment by Febbe** [comment]
Another thing is, that generating the hash for each event is most likely slower than just comparing the char pointer and the event type.
Probably, we can just store the pointer / increase ref count of the name without a copy (shouldn't be freed, since the device will exist, until it's plugged out).

**Comment by bhennion** [comment]
Or, assuming that Gdk only allocates one GdkDevice per physical device, test the address. I can't find any documentation on that though

File: src/core/gui/inputdevices/DeviceId.h [hunk 1]
```diff
@@ -0,0 +1,22 @@
...
+ *
+ * @license GNU GPLv2 or later
+ */
+
+#pragma once
+
+struct DeviceId {
+    DeviceId() = default;
+    explicit DeviceId(const void* id): id(id) {}
+    void clear() { id = nullptr; }
```
Comment (Febbe) [inline src/core/gui/inputdevices/DeviceId.h:17]: Dunno, if we might need this anytime:
```suggestion
    void reset(void const* id = nullptr) { this->id = id; }
```

File: src/core/gui/inputdevices/DeviceId.h [hunk 2]
```diff
@@ -0,0 +1,22 @@
...
+    operator bool() const { return id != nullptr; }
```
Comment (Febbe) [inline src/core/gui/inputdevices/DeviceId.h:18]: Conversion operators, should be marked "explicit", especially boolean conversions. 
Also, the equality and inequality operator is missing; the code only compiles, because `lhs != rhs` is implicitly converted to: `(lhs.id != nullptr) != (rhs.id != nullptr)` which will most likely be `false != false`

```suggestion
    constexpr explicit operator bool() const { return id != nullptr; }
    constexpr auto operator==(DeviceId rhs) -> bool { return id == rhs.id; }
    constexpr auto operator!=(DeviceId rhs) -> bool { return id == rhs.id; }
```

**Review by Febbe — CHANGES_REQUESTED** [review]
Looks good, but it must be tested, if the device pointers are unique and persistent.
Also the implicit cast bug must be fixed.

**Comment by Febbe** [comment]
> Looks good, but it must be tested, if the device pointers are unique and persistent.

I found a lot of descriptions which always state that:
A GdkDevice with pointer capabilities. This object is owned by GTK and must not be freed.

**Comment by bhennion** [comment]
Thanks for the catch. Of course the version I had pushed did not work...
This new version seems to work on my devices.

File: src/core/gui/inputdevices/DeviceId.h [hunk 3]
```diff
@@ -0,0 +1,24 @@
...
+ *
+ * @license GNU GPLv2 or later
+ */
+
+#pragma once
+
+struct DeviceId {
+    constexpr DeviceId() = default;
+    explicit constexpr DeviceId(const void* id): id(id) {}
+    void reset(const void* id = nullptr) { this->id = id; }
```
Comment (Febbe) [inline src/core/gui/inputdevices/DeviceId.h:17]: Nit: can also be constexpr

**Review by Febbe — APPROVED** [review]
LGTM, just rebase and merge.

File: src/core/gui/inputdevices/DeviceId.h (hunk 3 above)
Comment (bhennion) [reply src/core/gui/inputdevices/DeviceId.h:17]:
```suggestion
    constexpr void reset(const void* id = nullptr) { this->id = id; }
```

**Comment by MikuChan03** [comment]
This breaks my workflow at least. I have a thinkpad that has both a touchpad and one of those red trackpoints. Like this:

sef

The thing is, the buttons above and below the touchpad belong to the two different devices. The above two buttons are for the trackpoint, the below for the touchpad. I used to be able to press whichever, if I wanted to draw a line in xournal++. Now the above two don't work, for it's a different device. What do?
Many thanks

**Comment by rolandlo** [comment]
I can confirm the issue on my Lenovo Thinkpad.
