### PR TITLE
Fix PDF linear text selection on "improper" rectangles

### LINKED ISSUE #3790: Wrong selection in new 'select linear text' tool
**Affects versions :**
 - OS: Arch Linux
 - (Linux only) Desktop environment: Wayland
 - Which version of libgtk do you use: 3.24.31
 - Version of Xournal++: 7f6f107e
 - Installation method: AUR xournalpp-git package

**Describe the bug**
When using the 'select linear text tool' too much text is selected when the selection is longer than one line and the start of the selection on the first line is further to the right than the end of the selection on the last line. In the screenshot below I (tried) selecting the text from the beginning of the word 'Around' to the end of the word 'age'.

**To Reproduce**
1. Using the 'select linear text tool' make a selection that spans multiple lines, making sure that the beginning of the selection on the first line is further to the right than the end of the selection on the last line.
2. As soon the mouse button is let go and the toolbox appears, additional text is selected.

**Expected behavior**
Only the text from beginning to end of selection is selected.

**Screenshots of Problem**
20220208_19h16m28s_grim

### PR DESCRIPTION
**Pull request by Technius**
Fixes #3790. See commit message for details.

### CODE REVIEW

File: src/core/pdf/popplerapi/PopplerGlibPage.cpp [hunk 1]
```diff
@@ -172,12 +172,20 @@ cairo_rectangle_int_t cairoRectFromDouble(double x1, double y1, double width, do
...
 }  // namespace
 
-auto PopplerGlibPage::selectTextLines(const XojPdfRectangle& rect, XojPdfPageSelectionStyle style) -> TextSelection {
+auto PopplerGlibPage::selectTextLines(const XojPdfRectangle& selectRect, XojPdfPageSelectionStyle style)
+        -> TextSelection {
     std::vector<XojPdfRectangle> textRects;
 
+    // The selection rectangle may be "improper" by having x2 <= x1 or y1 <= y2 (e.g., if user
+    // selects from right to left or from bottom to top). This is incompatible with cairo, so
+    // construct a proper rectangle satisfying x1 <= x2 and y1 <= x2.
```
Comment (Technius) [inline src/core/pdf/popplerapi/PopplerGlibPage.cpp:181]: Oops, there's a typo in the comment here.

**Comment by Technius** [comment]
Merging in 24 hours unless there are any objections.
