### PR TITLE
Fix coordinate precision to 8 decimal places to reduce file size

### LINKED ISSUE #1277: Too much precision in xopp files.
Low priority.. but do we really need 14 digits of precision in the xopp file?

example page coordinates:
168.71782794981516 503.4808047927973

cutting down to 4 would reduce file size substantially before and after compression.
168.7178 503.4808

Should be a setting ... and it might be good to have it keep accuracy for files loaded with more accuracy.

### PR DESCRIPTION
**Pull request by siliconninja**
Fixes #1277.
If you decide to close this PR because you decide not to have fixed coordinate precision, that is OK with me. I'm just opening this pull request since the code is complete, and it's ready for review.

### CODE REVIEW

File: src/util/Util.cpp [hunk 1]
```diff
@@ -165,3 +166,17 @@ gboolean Util::paintBackgroundWhite(GtkWidget* widget, cairo_t* cr, void* unused
...
 }
 
+char* Util::getCoordinateString(double xVal, double yVal)
+{
+	char tmpX[G_ASCII_DTOSTR_BUF_SIZE];
+	g_ascii_formatd(tmpX, G_ASCII_DTOSTR_BUF_SIZE, Util::getFormatdPrecisionString(), xVal);
+	char tmpY[G_ASCII_DTOSTR_BUF_SIZE];
+	g_ascii_formatd(tmpY, G_ASCII_DTOSTR_BUF_SIZE, Util::getFormatdPrecisionString(), yVal);
+
+	return g_strdup_printf("%s %s", tmpX, tmpY);
```
Comment (JJones780) [inline src/util/Util.cpp]: g_strdup_printf allocates memory that needs to be freed.  Our function should also mention this in a doxygen type comment block ( some IDE's will pop this up on mouseover).

**Better yet,**   use g_snprintf () instead and require the caller to allocate and pass us a buffer to use
 ( so that it becomes `getCoordinateString(gchar*buff, gulong buffLen, double xVal, double yVal) `    ) 
I see two benefits to using g_snprintf:  1) no hidden allocations, 2) Can re-use the buffer when calling this function repeatedly in a loop ( _although I see the original code misses this optimization.. maybe the compiler did it ;)_  )

One could also consider using a c++ object that free's in the destructor... but I think that's overkill here.

File: src/util/Util.cpp [hunk 2]
```diff
@@ -165,3 +166,17 @@ gboolean Util::paintBackgroundWhite(GtkWidget* widget, cairo_t* cr, void* unused
...
+}
+
+char* Util::getFormatdPrecisionString()
+{
+	return g_strdup_printf("%%.%df", PRECISION_DECIMAL_PLACES);
```
Comment (JJones780) [inline src/util/Util.cpp]: Avoid rebuilding this format string every time.
The only use of  PRECISON_DECIMAL_PLACES seems to be to build this string.  So it makes sense to define a char* constant instead.

Declare it in the header but you have to initialize it here:
`const char* Util::PRECISION_FORMAT_STRING = "%.8f";   //use 8 digits of precision   https://m.xkcd.com/2170/ `

File: src/util/Util.h [hunk 3]
```diff
@@ -56,7 +56,12 @@ class Util
...
 
+	static char* getCoordinateString(double xVal, double yVal);
+	
+	static char* getFormatdPrecisionString();
 };
 
 static const size_t size_t_npos = static_cast<size_t>(-1);
 // for 64b systems it's 18446744073709551615 and for 32b – 4294967295
+
+static const int PRECISION_DECIMAL_PLACES = 8;
```
Comment (JJones780) [inline src/util/Util.h]: Intead of int, I suggest you create a 
`static const char* PRECISION_FORMAT_STRING;`
and initialize it in .cpp

**Comment by siliconninja** [comment]
Okay. I understand -- the change is so small that the commits could be combined into one, and trying/reverting ideas isn't worth including in the PR.

I will combine the commits later today. I would've replied earlier but GitHub was down.

**Comment by siliconninja** [comment]
I will rebase and then squash the earlier commits after I have made those changes in the code review since that would be easier. I agree with the proposed changes -- for the first one, I think I'll just use `g_snprintf` because of those benefits that you mentioned.

File: src/util/Util.cpp (hunk 1 above)
Comment (siliconninja) [reply src/util/Util.cpp]: I plan to use `g_snprintf` because of those benefits that you mentioned.

File: src/util/Util.cpp (hunk 2 above)
Comment (siliconninja) [reply src/util/Util.cpp]: The xkcd link in the comment is also a nice easter egg :smile:

**Comment by siliconninja** [comment]
I have made those changes and fixed the formatting with clang-format.

**Comment by JJones780** [comment]
Oops, Do you have the non-squashed version still?  The clang format makes it very hard for someone to see what was done to implement the feature - either to learn from, review or to do regression testing.  You should only apply clang-format to lines you've changed ( using git-clang-format - see [ Xournal++ wiki on clang-format ](https://github.com/xournalpp/xournalpp/wiki/Coding-conventions#use-clang-format)) or for cases where you've made a lot of changes to one file do the clang-format as a separate commit.  Once we get the whole project reformatted with clang this shouldn't be an issue.
 If you've lost the pre-clang format version let me know and I can help.

**Comment by siliconninja** [comment]
Yes, I have the non-squashed version. I saved it on a different branch in my fork called `issue_1277_archive`. I have run that command (`diff -U0 --no-color 583a317ff1d63b8d65d4019b75fb27801e5c0098 HEAD | clang-format-diff-8 -i -p1`) that you linked to in the documentation. I made further commits on that branch just in case I wanted to look at them later. I've now squashed my fork's `issue_1277` branch after I ran that command.

**Comment by siliconninja** [comment]
CI has failed :(
I think there were more merge conflicts or extra code that didn't get added in properly.
I tried rebasing my `issue_1277_archive` branch and it's a mess of merge conflicts. In this case I think it's just easier to merge the final commit with upstream/master and resolve the conflicts on just that commit, then squash that onto my other `issue_1277` branch.
I'll try to get back to a working build later today. (I live in the US, so my timezone is very different from yours)

**Comment by siliconninja** [comment]
Don't worry about the last comment, I was able to get everything up to date and built properly :relieved: 
Is this ready to be merged in?

**Comment by siliconninja** [comment]
Btw, did a quick micro-note test w/ 8 decimal place precision. Everything seems good.

Output of `compare -verbose -metric PSNR 2019-07-24-Note-21-59.png 2019-07-24-Note-21-59-8dp.png diff.png`:

diff
Note how there's no dark red at the top (even though the ink is in red).
The only difference is at the bottom which I think is the new version of the page template in a newer version of Xournal++.

**Comment by JJones780** [comment]
Hi @siliconninja ,

  I've been away lately.

  This is looking great. Very clean and understandable.

 What do you think about making getCoordinateString work the same way as g_ascii_formatd ( i.e. passing in a buffer to fill )?  It would let you re-use already allocated scratch buffer space and also use stack-allocated memory which we won't need to ( worry about it not being ) freed manually.
i.e. `getCoordinateString(gchar*buff, gulong buffLen, double xVal, double yVal) `


Thanks for doing the detective work on this. It's great to know we can shave off those digits without affecting image quality one bit ( pun intended ).

**Comment by siliconninja** [comment]
Hi @JJones780,

Thank you! I think that making getCoordinateString like g_ascii_formatd is a good idea. I'll start working on that later today because I don't have much time right now.

**Comment by siliconninja** [comment]
Alrighty, I've made those changes, and I'm ready for another look.

**Comment by JJones780** [comment]
Looks good. You just missed one call to g_free after the allocation by g_strconcat().
But instead.... 
I'd recommend you just define another format string for '%.8f %.8f'.  _It avoids running code to rebuild that format string repeatedly._ I understand wanting to keep to one format string definition but in this case the second can be right beneath and is straightforward and easily maintained.

You can also do stuff like:
```
#define PFS "%.8f"
// then using it like:
constexpr const gchar* PRECISION_FORMAT_STRING    = PFS;
constexpr const gchar* PRECISION_FORMAT_STRING_XY = PFS " " PFS;
```
but as suggested, I'd just stick with :
```
constexpr const gchar* PRECISION_FORMAT_STRING    =  "%.8f";
constexpr const gchar* PRECISION_FORMAT_STRING_XY =  "%.8f %.8f";  //note space delimeter
```

**Comment by siliconninja** [comment]
Thanks! I've made those changes. I agree, that makes the most sense. It's better not to rebuild the string and just have some duplication in this case.
Off-topic: The tip for concatenating strings using `#define` and spaces is pretty cool - I hadn't seen that before.

**Comment by JJones780** [comment]
Looks great.
A few extra includes in Util.cpp leftover but that won't cause any problems.
I (or someone ) will be merging this soon... just heading out the door now though.

**Comment by siliconninja** [comment]
To whoever's merging -- I've removed those imports (it still compiles fine without them). I forgot to do that, I had it planned though, thanks 🙂

**Comment by JJones780** [comment]
Thanks for the code and sharing the research you did.
