### PR TITLE
Detect .PDF as pdf

### LINKED ISSUE #3548: Unable to open PDF with capitalized extension "foo.PDF"
**Affects versions :**
 - OS: Linux openSuse Tumbleweed
 - (Linux only) Desktop environment: KDE X11
 - Which version of libgtk do you use: 3.24.30
 - Version of Xournal++: 1.1.0
 - Installation method: official release

**Describe the bug**
Cannot open an otherwise perfectly working PDF.
This PDF (attached) can be opened without problem with Okular and with Master PDF Editor 5.
Opening with Xournal++ I get an xmlparser error (see screenshot below).

**To Reproduce**
1. Open the attached PDF file with Xournal++

**Expected behavior**
The file should be opened and shown by Xournal++

**Screenshots of Problem**
image

[Dichiarazione sostitutiva certificato di morte pdf_9 T.PDF](https://github.com/xournalpp/xournalpp/files/7491392/Dichiarazione.sostitutiva.certificato.di.morte.pdf_9.T.PDF)

### PR DESCRIPTION
**Pull request by fabian-thomas**
Closes #3548

### CODE REVIEW

File: src/util/PathUtil.cpp [hunk 1]
```diff
@@ -72,7 +73,14 @@ auto Util::hasXournalFileExt(const fs::path& path) -> bool {
     return extension == ".xoj" || extension == ".xopp";
 }
 
-auto Util::clearExtensions(fs::path& path, const std::string& ext) -> void {
+auto Util::hasPdfFileExt(const fs::path& path) -> bool {
+    return std::find(Util::PDF_EXTENSIONS.begin(), Util::PDF_EXTENSIONS.end(), path.extension()) !=
+           Util::PDF_EXTENSIONS.end();
+}
```
Comment (bhennion) [inline src/util/PathUtil.cpp:79]: Would it not be simpler to just add a `StringUtils::toLowerCase` as is done in the lambda `rm_ext` below? This would also cover all the cases like `.Pdf` an so on.

File: src/util/PathUtil.cpp [hunk 2]
```diff
@@ -72,7 +73,14 @@ auto Util::hasXournalFileExt(const fs::path& path) -> bool {
...
+
+auto Util::clearExtensions(fs::path& path) -> void { clearExtensions(path, std::vector<std::string>()); }
+
+auto Util::clearExtensions(fs::path& path, const std::vector<std::string>& extensions) -> void {
     auto rm_ext = [&path](const std::string ext) {
         if (StringUtils::toLowerCase(path.extension().string()) == StringUtils::toLowerCase(ext)) {
             path.replace_extension("");
```
Comment (bhennion) [inline src/util/PathUtil.cpp:86]: See here for the lambda `rm_ext`

File: src/util/PathUtil.cpp (hunk 1 above)
Comment (fabian-thomas) [reply src/util/PathUtil.cpp:79]: Yeah, I thought about that before implementing this with a list of pdf extensions. At that point I thought it would be cleaner to do it like I did. I'm gonna change that.

**Review by personalizedrefrigerator — COMMENTED** [review]
I haven't tested this yet, but from a quick look through the changes, this looks good to me!

**Comment by LittleHuba** [comment]
@fabian-thomas please rebase to `release-1.1`. See https://github.com/xournalpp/xournalpp/blob/master/readme/Releases.md#branching-strategy

**Comment by fabian-thomas** [comment]
That helped a little bit with understanding the different branches and tags. Although I'm not totally sure if I understood that release_helper script correctly. Is this something I should usually use/use in this case?

As I understand this I should just rebase this branch on release-1.1 so that it can be merged into that branch.

**Comment by LittleHuba** [comment]
No that script is solely for us maintainers. You should never have to use it.

**Comment by LittleHuba** [comment]
> As I understand this I should just rebase this branch on release-1.1 so that it can be merged into that branch.

Yes exactly.

**Comment by fabian-thomas** [comment]
@LittleHuba Have I done this correctly? I decided to cherry-pick the commits since rebasing looked like it would not make sense.

**Comment by LittleHuba** [comment]
Yes cherry-picking is also a valid solution. Your changes seem to be okay. 

Why did you remove the test case though?

**Comment by fabian-thomas** [comment]
I accidently included it while cherry-picking the changes. It came from master. Should I include it again?

**Comment by Febbe** [comment]
Thanks for the PR.
