### PR TITLE
Fix calculation of stroke's bounding rectangle

### LINKED ISSUE #1425: Improper item selection bounds and clipping
**Affects versions :**
 All

**Describe the bug**
Strokes with thick lines are clipped on top and left but extra space on bottom and right sides

**To Reproduce**
Use a thick highlighter to draw a stroke then select it.

Also happens when selecting multiple strokes.

**Expected behavior**
bounding box evenly surrounds selected stroke(s).

image

### PR DESCRIPTION
**Pull request by JJones780**
fixes #1425 
Now properly centered
and takes into account variable (pressure) width strokes.

### CODE REVIEW

File: src/model/Stroke.cpp [hunk 1]
```diff
@@ -565,35 +565,44 @@ void Stroke::calcSize()
...
+	bool hasPressure = points[0].z != Point::NO_PRESSURE;
+	double halfThick = this->width / 2.0;  //  accommodate for pen width
+
+	for (int i = 0; i < this->pointCount; i++)
 	{
-		if (minX > points[i].x)
+		if (hasPressure) halfThick = points[i].z / 2.0;
+
+		double edge = points[i].x - halfThick;
+		if (minX > edge)
```
Comment (Technius) [inline src/model/Stroke.cpp]: You can make this cleaner and clearer by using `std::min` and `std::max`:
```suggestion
		minX = std::min(minX, points[i].x - halfThick);
		minY = std::min(minY, points[i].y - halfThick);
		maxX = std::max(maxX, points[i].x + halfThick);
		maxY = std::max(maxY, points[i].y + halfThick);						
```

Comment (JJones780) [reply src/model/Stroke.cpp]: Gee.. why didn't I see that!  Thanks!
