### PR TITLE
Fix crash in Settings->Input panel

### LINKED ISSUE #6913: App crashes when stylus is used in the "edit/preferences/input system" menu
### Operating System/Distribution

Debian GNU/Linux 12 (bookworm)

### (Linux only) Desktop Environment

gnome-xorg x11

### (Linux Only) Display Server

X11

### Installation Method

Official Release

### Xournal++ Version

xournalpp 1.3.0

### libgtk Version

3.24.38

### Steps to Reproduce

1. Open edit/preferences/input system
2. hover with the stylus on the page

### Crash log

Executing "/usr/bin/xournalpp"
Xournal++ started with PID: 7698
Crashed with signal: 11
    Date: Fri Dec 19 15:29:50 2025

xournalpp 1.3.0
├──libgtk: 3.24.38
├──glib: 2.74.6
├──cairo:  1.16.0
└──OS info: Debian GNU/Linux 12 (bookworm)
  (The GDK backend is probably printed out below)

*** Output: ***

(com.github.xournalpp.xournalpp:7698): Gtk-WARNING **: 15:28:00.660: Failed to parse /home/giacomo/.config/gtk-3.0/settings.ini: Key file does not start with a group
(com.github.xournalpp.xournalpp:7698): xopp-DEBUG: 15:28:00.685: TEXTDOMAINDIR = (null), Platform-specific locale dir = /usr/share/xournalpp/../locale, chosen directory = /usr/share/xournalpp/../locale
ALSA lib pcm.c:2666:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2666:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2666:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_route.c:877:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:877:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:877:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:877:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_oss.c:397:(_snd_pcm_oss_open) Cannot open device /dev/dsp
ALSA lib pcm_oss.c:397:(_snd_pcm_oss_open) Cannot open device /dev/dsp
ALSA lib pcm_a52.c:1001:(_snd_pcm_a52_open) a52 is only for playback
ALSA lib confmisc.c:160:(snd_config_get_card) Invalid field card
ALSA lib pcm_usb_stream.c:482:(_snd_pcm_usb_stream_open) Invalid card 'card'
ALSA lib confmisc.c:160:(snd_config_get_card) Invalid field card
ALSA lib pcm_usb_stream.c:482:(_snd_pcm_usb_stream_open) Invalid card 'card'
xopp-INFO: 15:28:00.895: Loading plugins from: /usr/share/xournalpp/plugins
xopp-INFO: 15:28:00.896: Loading plugins from: /home/giacomo/.config/xournalpp/plugins
xopp-Message: 15:28:00.917: X11 Touch disabler active for device "IPTS 045E:099F Touchscreen"
(com.github.xournalpp.xournalpp:7698): xopp-DEBUG: 15:28:00.917: Extracted theme info: Name = Adwaita, rootname = Adwaita, dark = false
(com.github.xournalpp.xournalpp:7698): xopp-DEBUG: 15:28:00.934: Theme name: Adwaita
(com.github.xournalpp.xournalpp:7698): xopp-DEBUG: 15:28:00.934: Modified in GtkSettings: false
(com.github.xournalpp.xournalpp:7698): xopp-DEBUG: 15:28:00.934: Theme variant: light
(com.github.xournalpp.xournalpp:7698): xopp-DEBUG: 15:28:00.934: Icon theme: iconsColor
(com.github.xournalpp.xournalpp:7698): xopp-DEBUG: 15:28:01.053: Window moved to monitor "eDP-1"
(com.github.xournalpp.xournalpp:7698): xopp-DEBUG: 15:28:06.968: TEXTDOMAINDIR = (null), Platform-specific locale dir = /usr/share/xournalpp/../locale, chosen directory = /usr/share/xournalpp/../locale
xopp-Message: 15:28:07.025: X11 Touch disabler active for device "IPTS 045E:099F Touchscreen"

*************************************************************************

[Crash Handler] Crashed 1 time(s) with signal 11
xournalpp 1.3.0
├──libgtk: 3.24.38
├──glib: 2.74.6
├──cairo:  1.16.0
├──GDK backend: X11
└──OS info: Debian GNU/Linux 12 (bookworm)

Try to get a stacktrace...
Stack trace (most recent call first):
#0  0x000065013b3503d7 in Stacktrace::printStacktrace(std::ostream&) at /usr/bin/xournalpp
#1  0x000065013b17deb1 in crashHandler at /usr/bin/xournalpp
#2  0x000076649445a04f at /lib/x86_64-linux-gnu/libc.so.6
#3  0x000065013b2b3760 in AbstractInputHandler::block(bool) at /usr/bin/xournalpp
#4  0x000065013b1c915d in InputContext::blockDevice(InputContext::DeviceType) at /usr/bin/xournalpp
#5  0x000065013b2b3ea2 in HandRecognition::penEvent() at /usr/bin/xournalpp
#6  0x000065013b1c9bab in InputContext::handle(_GdkEvent*) at /usr/bin/xournalpp
#7  0x0000766495690cb3 at /lib/x86_64-linux-gnu/libgtk-3.so.0
#8  0x00007664952365a8 at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#9  0x000076649524f05d in g_signal_emit_valist at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#10 0x000076649524fdbe in g_signal_emit at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#11 0x00007664959696e7 at /lib/x86_64-linux-gnu/libgtk-3.so.0
#12 0x000076649580783d at /lib/x86_64-linux-gnu/libgtk-3.so.0
#13 0x00007664958092f5 in gtk_main_do_event at /lib/x86_64-linux-gnu/libgtk-3.so.0
#14 0x0000766495532814 at /lib/x86_64-linux-gnu/libgdk-3.so.0
#15 0x000076649558c7a1 at /lib/x86_64-linux-gnu/libgdk-3.so.0
#16 0x000076649513c708 in g_main_context_dispatch at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#17 0x000076649513c997 at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#18 0x000076649513ca2b in g_main_context_iteration at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#19 0x000076649538a65c in g_application_run at /lib/x86_64-linux-gnu/libgio-2.0.so.0
#20 0x000065013b180038 in XournalMain::run(int, char**) at /usr/bin/xournalpp
#21 0x0000766494445249 at /lib/x86_64-linux-gnu/libc.so.6
#22 0x0000766494445304 in __libc_start_main at /lib/x86_64-linux-gnu/libc.so.6
#23 0x000065013b17d630 in _start at /usr/bin/xournalpp

Trying to emergency save the current open document...
Successfully saved document to "/home/giacomo/.config/xournalpp/emergencysave.xopp"

### Additional Context

I am on a microsoft surface pro 7. I upgraded from xpp 1.2.7, where this bug never manifested.

### PR DESCRIPTION
**Pull request by bhennion**
Fix #6913

### CODE REVIEW

**Comment by bhennion** [comment]
\action create-installers debian

File: src/core/gui/inputdevices/InputContext.cpp [hunk 1]
```diff
@@ -249,7 +249,9 @@ void InputContext::blockDevice(InputContext::DeviceType deviceType) {
             this->stylusHandler->block(true);
             break;
         case TOUCHSCREEN:
-            this->touchDrawingHandler->block(true);
+            if (this->touchDrawingHandler) {
+                this->touchDrawingHandler->block(true);
+            }
```
Comment (rolandlo) [inline src/core/gui/inputdevices/InputContext.cpp:254]: If this is a problem, shouldn't the same fix applied to
`InputContext::unblockDevice`?

Comment (bhennion) [reply src/core/gui/inputdevices/InputContext.cpp:254]: Indeed. I had missed a couple of spots! Thanks!

**Comment by bhennion** [comment]
Thnaks a lot!
