### PR TITLE
Fix "nan"s as pressure values.

### LINKED ISSUE #4381: Pen strokes disappear problem in "export as PDF".
(Please complete the following information, and then delete this line)

**Affects versions :**
 - OS: Linux Pop!_OS 22.04
 - Desktop environment: X11
 - Version of libgtk: 3.24.33
 - Version of Xournal++: 1.1.2
 - Installation method: ppa:apandada1/xournalpp-stable

**Describe the bug**
This bug only happened when using a stylus pen. In stroke recognizer mode, some strokes recognization will be failed. After this failure, any new drawing on the same page will not be shown in the exported PDF.

**To Reproduce**
1. Setting "Input System -> Input stabilization -> Averaging method" as "Velocity based Gaussian weight".
2. Turn on stroke recognizer mode.
3. Draw a " Ↄ " with stylus pen (in order to make the shape be recognized as a circle). Sometimes the shape just drawn will disappear.
4. Draw any new stroke on the same page.
5. Export as PDF.
6. Check the exported PDF file will discover that, any new drawing after disappearance on the same page just gone.

**Expected behavior**
The exported PDF should be completed.

**Screenshots of Problem**
Screenshot from 2022-11-04 18-35-07

**Additional context**
Add any other information or context about the problem here.

### PR DESCRIPTION
**Pull request by rolandlo**
Fixes  #4381
This is an attempted fixup/follow-up of #4354

The aim is to filter out `nan`s from pressure values. 
The condition `v<0` and `v>0` are both false when `std::isnan(v)` is true, e.g. when `v=0./0.` Therefore currently `fixNullPressureValues` which aims to guarantee pressure values being `>0`, does not do its job for `nan`s.

With the PR, the document in https://github.com/xournalpp/xournalpp/issues/4381#issuecomment-1305130423 opens and exports fine.

There must also be a problem in either the Gaussian weights stroke stabilizer or in the stroke recognizer leading to `nan`s (under unknown conditions). That should be fixed as well.

~Moreover the `testStrokeWidthRecovery` should be extended to test for `nan`s as well.~ <- Done!

### CODE REVIEW

**Comment by rolandlo** [comment]
I have added a new stroke:
```xml
<stroke tool="pen" ts="0ll" fn="" color="#00ff00ff" width="1.41 nan 0.20 0.30 0.10 -nan 0.25 0.30 0.40 nan">210.00 420.00 220.00 425.00 230.00 427.00 240.00 429.15 250.00 432.95 260.00 420.55 270.00 418.74 280.00 413.05 290.0 411.4 300.0 413.5</stroke>
```
to `width_recovery.xopp`. As the modified `testStrokeWidthRecovery` test shows, it is correctly split into two strokes (without `nan`s).

**Comment by LittleHuba** [comment]
The requested installers were generated successfully. The installers are available at:

- [Windows](https://artprodsu6weu.artifacts.visualstudio.com/A4bb312fe-95d7-456e-96fb-7669bb27c94b/ce85de88-4b71-44a0-8a57-2707c0b9a6e7/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL3hvdXJuYWxwcC9wcm9qZWN0SWQvY2U4NWRlODgtNGI3MS00NGEwLThhNTctMjcwN2MwYjlhNmU3L2J1aWxkSWQvMjI0NzYvYXJ0aWZhY3ROYW1lL3dpbmRvd3M1/content?format=zip)
- [macOS](https://artprodsu6weu.artifacts.visualstudio.com/A4bb312fe-95d7-456e-96fb-7669bb27c94b/ce85de88-4b71-44a0-8a57-2707c0b9a6e7/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL3hvdXJuYWxwcC9wcm9qZWN0SWQvY2U4NWRlODgtNGI3MS00NGEwLThhNTctMjcwN2MwYjlhNmU3L2J1aWxkSWQvMjI0NzYvYXJ0aWZhY3ROYW1lL21hY09T0/content?format=zip)
- [Debian](https://artprodsu6weu.artifacts.visualstudio.com/A4bb312fe-95d7-456e-96fb-7669bb27c94b/ce85de88-4b71-44a0-8a57-2707c0b9a6e7/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL3hvdXJuYWxwcC9wcm9qZWN0SWQvY2U4NWRlODgtNGI3MS00NGEwLThhNTctMjcwN2MwYjlhNmU3L2J1aWxkSWQvMjI0NzYvYXJ0aWZhY3ROYW1lL2xpbnV4LWRlYmlhbi1wYWNrYWdlcw2/content?format=zip)
- [Ubuntu 18.04](https://artprodsu6weu.artifacts.visualstudio.com/A4bb312fe-95d7-456e-96fb-7669bb27c94b/ce85de88-4b71-44a0-8a57-2707c0b9a6e7/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL3hvdXJuYWxwcC9wcm9qZWN0SWQvY2U4NWRlODgtNGI3MS00NGEwLThhNTctMjcwN2MwYjlhNmU3L2J1aWxkSWQvMjI0NzYvYXJ0aWZhY3ROYW1lL2xpbnV4LXVidW50dS0xOC4wNC1wYWNrYWdlcw2/content?format=zip)
- [Ubuntu 20.04](https://artprodsu6weu.artifacts.visualstudio.com/A4bb312fe-95d7-456e-96fb-7669bb27c94b/ce85de88-4b71-44a0-8a57-2707c0b9a6e7/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL3hvdXJuYWxwcC9wcm9qZWN0SWQvY2U4NWRlODgtNGI3MS00NGEwLThhNTctMjcwN2MwYjlhNmU3L2J1aWxkSWQvMjI0NzYvYXJ0aWZhY3ROYW1lL2xpbnV4LXVidW50dS0yMC4wNC1wYWNrYWdlcw2/content?format=zip)

Please be aware that these links are only valid for a limited time (~30 days).

**Comment by rolandlo** [comment]
Merging in 24 hours if no objections are raised.

File: src/core/control/xojfile/LoadHandler.cpp [hunk 1]
```diff
@@ -950,7 +950,8 @@ void LoadHandler::fixNullPressureValues() {
 
     std::vector<std::vector<Point>> strokePortions;
     while (nextPositive != pressureBuffer.end()) {
-        auto nextNonPositive = std::find_if(nextPositive, pressureBuffer.end(), [](double v) { return v <= 0; });
+        auto nextNonPositive =
+                std::find_if(nextPositive, pressureBuffer.end(), [](double v) { return v <= 0 || v != v; });
```
Comment (bhennion) [inline src/core/control/xojfile/LoadHandler.cpp:954]: I'd make the variable name more explicit, and use std::isnan rather than v != v.

```suggestion
        auto nextInvalid =
                std::find_if(nextPositive, pressureBuffer.end(), [](double v) { return v <= 0 || std::isnan(v); });
```

File: src/core/control/xojfile/LoadHandler.cpp [hunk 2]
```diff
@@ -1035,7 +1036,7 @@ void LoadHandler::parserText(GMarkupParseContext* context, const gchar* text, gs
         if (!handler->pressureBuffer.empty()) {
             if (handler->pressureBuffer.size() + 1 >= handler->stroke->getPointCount()) {
                 auto firstNonPositive = std::find_if(handler->pressureBuffer.begin(), handler->pressureBuffer.end(),
-                                                     [](double v) { return v <= 0; });
+                                                     [](double v) { return v <= 0 || v != v; });
```
Comment (bhennion) [inline src/core/control/xojfile/LoadHandler.cpp:1039]: Same here

**Review by bhennion — APPROVED** [review]
Just two nitpicks for better readability

File: src/core/control/xojfile/LoadHandler.cpp (hunk 2 above)
Comment (rolandlo) [reply src/core/control/xojfile/LoadHandler.cpp]: Thanks for the review. I amended these changes to the corresponding commit.

**Comment by bhennion** [comment]
There seems to be a `#include <cmath>` missing for the CI builds to go through. After that, merge at will!

**Comment by rolandlo** [comment]
> There seems to be a `#include <cmath>` missing for the CI builds to go through. After that, merge at will!

Thanks for the catch!
