### PR TITLE
Fix Font and Color chooser dialogs not working

### LINKED ISSUE #5857: Font not changing
### Operating System

Linux

### (Linux only) Distribution

Mint

### (Linux only) Desktop Environment

Cinnamon

### (Linux Only) Display Server

X.Org

### Installation Method

PPA

### Xournal++ Version

1.2.3+dev

### libgtk Version

3.24.33

### Bug Description

In a previous update, I changed the font of my text tool to Chilanka Bold (don't ask). In updates since, however, I have been unable to change my font within the app (e.g. by going to Tools > Text Font or by adding the font tool to my toolbar). No matter what I try, my font when using the text tool in Xournal++ remains Chilanka Bold.

I can change the font by manually editing the settings.xml file, but I'm unable to change the font from within the app.

### Expected Behaviour

Changing the font should change the font.

### Steps to Reproduce

1. Go to Tools > Text Font. Change the font to a font of your choice.
2. Use the text tool to type some text.
3. Observe that the font is not what you expected.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by bhennion**
Fix #5857 

Thanks to @tmoerschell for figuring out what the issue was https://github.com/xournalpp/xournalpp/issues/5857#issuecomment-2350978764

Nb: I also remove in this PR the unused class XojColor. This is unrelated and I'm sorry about it.

### CODE REVIEW

**Review by rolandlo — APPROVED** [review]
LGTM. It works fine.
Thanks @bhennion and @tmoerschell for debugging and fixing this issue.

File: src/util/include/util/XojMsgBox.h [hunk 1]
```diff
@@ -23,7 +23,10 @@
 
 class XojMsgBox final {
 public:
-    XojMsgBox(GtkDialog* dialog, xoj::util::move_only_function<void(int)> callback = [](int) {});
+    enum CallbackPolicy { IMMEDIAT, POSTPONED };
```
Comment (tmoerschell) [inline src/util/include/util/XojMsgBox.h:26]: Shouldn't this be spelled `IMMEDIATE`?

**Review by tmoerschell — COMMENTED** [review]
I can confirm it works well. I only found a potential typo.
