### PR TITLE
Fix zero inertia

### LINKED ISSUE #6717: Stroke recognizer produces NaN values
As mentionned in https://github.com/xournalpp/xournalpp/issues/6641#issuecomment-3352885851_ , it can happen that the stroke recognizer produces NaN coordinates.

Here's a file containing only the stroke that caused the issue. It should be easier to reproduce it from there.

```xml
<?xml version="1.0" standalone="no"?>
<xournal creator="tmoerschell" fileversion="4">
<title>Xournal++ document - see https://xournalpp.github.io/</title>
<page width="595.27559" height="841.88976">
<background type="solid" color="#ffffffff" style="plain"/>
<layer>
<stroke tool="pen" color="#000000ff" width="1.41 0.39551431 0.44422477 0.46369604 0.48211307 0.50610254 0.53876265 0.59573495 0.65896818 0.71594049 0.76385489 0.78713436 0.80346441 0.81736324 0.83091783 0.84410666 0.85383154 0.85662852 0.85731701 0.85488579 0.85002335 0.84376242 0.82883085 0.78922133 0.72461112" capStyle="round">545.60001 178.93587 545.17845 179.25054 544.78512 179.72455 544.25866 180.53944 543.73423 181.82633 543.28644 183.58723 542.94555 185.82012 542.68334 188.42012 542.52399 191.1008 542.47154 193.67659 542.52399 195.85704 542.65711 197.48481 542.81444 198.5357 543.02422 198.82616 543.15533 198.48325 543.23399 197.48481 543.39133 195.98814 543.5769 194.12236 543.89156 192.07302 544.41801 189.97124 545.09978 188.13168 546.01956 186.7399 547.04625 185.95123 548.09714 185.87256 549.09559 186.34456</stroke>
</layer>
</page>
</xournal>
```

### PR DESCRIPTION
**Pull request by tmoerschell**
Fixes #6717

This is a different approach than #6737. I believe this fixes the source of the issue, rather than catching it later.

`Inertia::calc()` received two indices from `findPolygon()` that were both inclusive. This isn't the same as we usually know from iterators, and not the way it was intended to initially in `Inertia::calc()` as well as its usage in `CircleRecognizer::recognize()`. There's two ways of fixing that:
* Align `Inertia::calc()` with the usage of `findPolygon()` and `RecoSegment::calcSegmentGeometry()` (first commit)
* Use `std::span` as argument to `Inertia::calc()` (squash of both commits)

I think modifying the used pattern in `findPolygon()` is more risky than it should be. I find that `std::span` fits well here, as it is more expressive than `first, last` pointers, which was the cause of the issue at hand.

There is _technically_ a change in how the strokes are recognized, but since it only includes one more point in the initial detection, it shouldn't really change much.

### CODE REVIEW

File: src/core/control/shaperecognizer/ShapeRecognizer.cpp [hunk 1]
```diff
@@ -197,7 +198,7 @@ auto ShapeRecognizer::findPolygonal(const Point* pt, int start, int end, int nsi
     for (; k < nsides; k++) {
         i1 = start + (k * (end - start)) / nsides;
         i2 = start + ((k + 1) * (end - start)) / nsides;
-        s.calc(pt, i1, i2);
+        s.calc(std::span<const Point>(pt + i1, pt + i2 + 1));
```
Comment (bhennion) [inline src/core/control/shaperecognizer/ShapeRecognizer.cpp:203]: Is it guaranteed that pt + it2 + 1 is not past-the-end?

Comment (tmoerschell) [reply src/core/control/shaperecognizer/ShapeRecognizer.cpp:203]: `pt + i2 + 1` is precisely past-the-end, which is what the constructor of `std::span` requires. We could use the pointer + size constructor as well, but I thought a size of `i2 - i1 + 1` would be even more confusing.

`findPolygonal` is called the first time with `start` and `end` as inclusive indices:
https://github.com/xournalpp/xournalpp/blob/e504ec3ac2faf27fb45fa19f36506427f6ee73fc/src/core/control/shaperecognizer/ShapeRecognizer.cpp#L345-L346

`i2` is at most `start + (nsides * (end - start) / nsides)`, with `k == nsides - 1`, i.e. `i2 = end`.

Comment (bhennion) [reply src/core/control/shaperecognizer/ShapeRecognizer.cpp:203]: I see, then maybe `end` should be renamed (e.g. to `last`) for better readability.

Comment (tmoerschell) [reply src/core/control/shaperecognizer/ShapeRecognizer.cpp:203]: `std::algorithm` uses `first` and `last` iterators. I'll rename it to `finish`

**Comment by tmoerschell** [comment]
Added comment, renamed variable `end` -> `finish`, and squashed commits
