### PR TITLE
Make MacOS Finder open xopp-files

### LINKED ISSUE #5229: Cannot open any file using `open with` on mac
### Operating System

Mac OS

### (Linux only) Distribution

_No response_

### (Linux only) Desktop Environment

_No response_

### (Linux Only) Display Server

None

### Installation Method

Official release

### Xournal++ Version

1.2.1

### libgtk Version

3.24.38

### Bug Description

On a mac (using Sonoma with a M2 processor), even after giving full disk access to xournal++, files cannot be opened using finder. They can only be opened when navigating to the file using the `open file` menu.

Opening any xopp file will result in this error 
image

### Expected Behaviour

The file is opened and no spurrious error of the type "incompatible file type" should appear.

### Steps to Reproduce

1. Have a valid `.xopp` file
2. Open the file with `xournal++` from finder
3. See an error message 

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by rolandlo**
Finder uses Launch Services to identify Xournal++ as the preferred app for xopp-files as declared in the Info.plist, to launch it and send it an "Open Documents" event. Gtk receives the event and uses g_application_open to make the handler for the "open" signal react to it. See gtkapplication-quartz.c.

Fixes #5229.

### CODE REVIEW

**Comment by rolandlo** [comment]
@Doublonmousse Please test the MacOS app-bundle generated below. It should open xopp-files in Finder.

**Comment by LittleHuba** [comment]
The requested installers were generated successfully. The installers are available at:

- [Windows](https://artprodsu6weu.artifacts.visualstudio.com/A4bb312fe-95d7-456e-96fb-7669bb27c94b/ce85de88-4b71-44a0-8a57-2707c0b9a6e7/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL3hvdXJuYWxwcC9wcm9qZWN0SWQvY2U4NWRlODgtNGI3MS00NGEwLThhNTctMjcwN2MwYjlhNmU3L2J1aWxkSWQvMjg2OTcvYXJ0aWZhY3ROYW1lL3dpbmRvd3M1/content?format=zip)
- [macOS](https://artprodsu6weu.artifacts.visualstudio.com/A4bb312fe-95d7-456e-96fb-7669bb27c94b/ce85de88-4b71-44a0-8a57-2707c0b9a6e7/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL3hvdXJuYWxwcC9wcm9qZWN0SWQvY2U4NWRlODgtNGI3MS00NGEwLThhNTctMjcwN2MwYjlhNmU3L2J1aWxkSWQvMjg2OTcvYXJ0aWZhY3ROYW1lL21hY09T0/content?format=zip)
- [Debian](https://artprodsu6weu.artifacts.visualstudio.com/A4bb312fe-95d7-456e-96fb-7669bb27c94b/ce85de88-4b71-44a0-8a57-2707c0b9a6e7/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL3hvdXJuYWxwcC9wcm9qZWN0SWQvY2U4NWRlODgtNGI3MS00NGEwLThhNTctMjcwN2MwYjlhNmU3L2J1aWxkSWQvMjg2OTcvYXJ0aWZhY3ROYW1lL2xpbnV4LWRlYmlhbi1wYWNrYWdlcw2/content?format=zip)
- [Ubuntu 20.04](https://artprodsu6weu.artifacts.visualstudio.com/A4bb312fe-95d7-456e-96fb-7669bb27c94b/ce85de88-4b71-44a0-8a57-2707c0b9a6e7/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL3hvdXJuYWxwcC9wcm9qZWN0SWQvY2U4NWRlODgtNGI3MS00NGEwLThhNTctMjcwN2MwYjlhNmU3L2J1aWxkSWQvMjg2OTcvYXJ0aWZhY3ROYW1lL2xpbnV4LXVidW50dS0yMC4wNC1wYWNrYWdlcw2/content?format=zip)
- [Ubuntu 22.04](https://artprodsu6weu.artifacts.visualstudio.com/A4bb312fe-95d7-456e-96fb-7669bb27c94b/ce85de88-4b71-44a0-8a57-2707c0b9a6e7/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL3hvdXJuYWxwcC9wcm9qZWN0SWQvY2U4NWRlODgtNGI3MS00NGEwLThhNTctMjcwN2MwYjlhNmU3L2J1aWxkSWQvMjg2OTcvYXJ0aWZhY3ROYW1lL2xpbnV4LXVidW50dS0yMi4wNC1wYWNrYWdlcw2/content?format=zip)

Please be aware that these links are only valid for a limited time (~30 days).

**Comment by Doublonmousse** [comment]
Yes, it fixes the issue.

Somehow it also fixes #4431 as well on my machine ...

File: src/core/control/XournalMain.cpp [hunk 1]
```diff
@@ -424,10 +425,29 @@ void on_command_line(GApplication*, GApplicationCommandLine*, XMPtr) {
...
+            app_data->control->openFile(p);
+        } else {
+            const std::string msg = FS(_F("File {1} does not exist.") % p.u8string());
+            XojMsgBox::showErrorToUser(GTK_WINDOW(app_data->win->getWindow()), msg);
+        }
+    } catch (const fs::filesystem_error& e) {
+        const std::string msg = FS(_F("Sorry, Xournal++ cannot open remote files at the moment.\n"
+                                      "You have to copy the file to a local directory.") %
+                                   p.u8string() % e.what());
+        XojMsgBox::showErrorToUser(GTK_WINDOW(app_data->win->getWindow()), msg);
```
Comment (Febbe) [inline src/core/control/XournalMain.cpp:448]: I would use a more generic error message.

I think, `std::filesystem` should handle remote files over any NFS like SMB/CIFS. So when we can't open it, it should fail because of some GIO stuff. The second is, that there are many other filesystem errors.

**Review by Febbe — COMMENTED** [review]
This should also change the behavior on other operating systems. For now I can only test this on windows. Linux should be tested also.

**Comment by Febbe** [comment]
> Yes, it fixes the issue.
> 
> Somehow it also fixes #4431 as well on my machine ...

Should not be the reason. I think it could be the UB I fixed in a previous commit. Some eventhandlers returned a bool but were casted to a function returning a gboolean, which is UB.

**Comment by Doublonmousse** [comment]
I did a quick test on pop os 22.04 and did not encounter any issue opening files (neither from the app menu nor from nautilus)

**Comment by rolandlo** [comment]
> This should also change the behavior on other operating systems. For now I can only test this on windows. Linux should be tested also.

The only place in the Gtk sources, where `g_application_open` is called, is in `gtkapplication-quartz.c`. This only affects MacOS.
The only place in the Glib sources, where `g_application_open` is called, is in `g_application_real_local_command_line`, but only in the case when there are unparsed remaining command line options (otherwise `g_application_activate` is called). Since we already parse remaining command line options in
https://github.com/xournalpp/xournalpp/blob/7f5cd26c751e5e02006792121f80d23d3c26abb9/src/core/control/XournalMain.cpp#L636-L637
we never get `g_application_open` through `g_application_real_local_command_line` for Xournal++.

So I don't think that other OS'es are affected.

Opening files on Gnome or KDE from the file manager is governed by desktop files and so simply pass the file(s) to open as argument(s) to the executable listed in the `Exec` key. On Windows it's similar, just that desktop files are replaced by registry entries.

Just in case, I have tested it on Ubuntu 23.10 and it works all fine.

File: src/core/control/XournalMain.cpp (hunk 1 above)
Comment (rolandlo) [reply src/core/control/XournalMain.cpp:448]: That was copy-pasted from `on_startup`. I will change both messages simultaneously.

About remote files, see #1269.

Comment (rolandlo) [reply src/core/control/XournalMain.cpp]: Done.

**Comment by Febbe** [comment]
Thank you for the explanation, that is probably the reason, why I did not implement the function back then.

**Comment by rolandlo** [comment]
Thanks for the review @Febbe. Merging in 24 hours if no objections are raised.
