### PR TITLE
Fix bounding box for pressure-sensitive strokes

### LINKED ISSUE #4668: Incorrect bounding box for strokes with varying pressure
**Affects versions :**
 - OS: GNU/Linux, probably others as well
 - Version of Xournal++: https://github.com/xournalpp/xournalpp/commit/517ce512a709d2951e84d7427a7d5399959270f2

**Describe the bug**
Rendering issue in connection to pressure-sensitive strokes. Affects eraser, undo, and redo and possibly other actions.

**To Reproduce**
1. Activate pressure sensitivity and set pressure multiplier to 4, as the effect is less visible at 1.
2. In my test: set the brush size to large and the eraser size to small. Set zoom to maximum.
3. Create a single "stroke" using the stylus, interleave it with button presses to activate the stroke-based eraser without lifting the stylus from the tablet. Stop until a stroke that causes artefacts was deleted.

**Expected behavior**
No artefacts when handling above stroke.

**Screenshots of Problem**
Erasure: https://user-images.githubusercontent.com/31923882/220463326-4ecf8ef7-f472-4a20-b3fa-716ac7b1e9f2.mp4

Redo / undo: https://user-images.githubusercontent.com/31923882/220464807-81d18891-8d19-4b92-982b-92410bac3a45.mp4

Stroke: [bug_stroke.zip](https://github.com/xournalpp/xournalpp/files/10798009/bug_stroke.zip)

**Additional context**
Originally mentioned here: https://github.com/xournalpp/xournalpp/pull/4659#issuecomment-1438169890

### PR DESCRIPTION
**Pull request by hrdl-github**
Fixes #4668.

### CODE REVIEW

File: src/core/model/Stroke.cpp [hunk 1]
```diff
@@ -392,14 +417,16 @@ void Stroke::setLastPressure(double pressure) {
         assert(pressure != Point::NO_PRESSURE);
         Point& back = this->points.back();
         back.z = pressure;
-        updateBounds(Element::x, Element::y, Element::width, Element::height, snappedBounds, back, 0.5 * pressure);
```
Comment (bhennion) [inline src/core/model/Stroke.cpp:395]: Why is this necessary? The last point's pressure is not used in rendering, unless the stroke has exactly one point, in which case you end up calling `updateBounds` from `updateBoundsLastTwoPressures`

File: src/core/model/Stroke.cpp [hunk 2]
```diff
@@ -379,6 +386,24 @@ auto Stroke::getAvgPressure() const -> double {
...
+
+    Point& p = this->points.back();
+    auto const pointCount = this->getPointCount();
+    if (pointCount >= 2) {
+        Point& p2 = this->points[pointCount - 2];
+        double pressure = p2.z;
+
+        updateBounds(Element::x, Element::y, Element::width, Element::height, snappedBounds, p, 0.5 * pressure);
+        updateBounds(Element::x, Element::y, Element::width, Element::height, snappedBounds, p2, 0.5 * pressure);
+    } else if (pointCount == 1) {
```
Comment (bhennion) [inline src/core/model/Stroke.cpp:402]: This case should be totally excluded from `updateBoundsLastTwoPressures` (like with an assert).

File: src/core/model/Stroke.cpp [hunk 3]
```diff
@@ -379,6 +386,24 @@ auto Stroke::getAvgPressure() const -> double {
...
+    }
+
+    Point& p = this->points.back();
+    auto const pointCount = this->getPointCount();
+    if (pointCount >= 2) {
+        Point& p2 = this->points[pointCount - 2];
+        double pressure = p2.z;
+
+        updateBounds(Element::x, Element::y, Element::width, Element::height, snappedBounds, p, 0.5 * pressure);
+        updateBounds(Element::x, Element::y, Element::width, Element::height, snappedBounds, p2, 0.5 * pressure);
```
Comment (bhennion) [inline src/core/model/Stroke.cpp:401]: That's suboptimal: `snappedBounds` gets needlessly updated on the second call: p2 already lies in `snappedBounds`

**Review by bhennion — CHANGES_REQUESTED** [review]
Thanks for the fix! You got to the core of the issue here.

I have a couple of nitpicks (see below)

**Review by bhennion — APPROVED** [review]
LGTM! Thanks for the great job!

Merging in 48 hours unless an objection is raised
