### PR TITLE
Fix gsignals outliving their data in PageTypeSelectionPopover factory

### LINKED ISSUE #7281: Crash in New Page popup: in PageTypeSelectionPopover's call to gtk_widget_set_sensitive
### Operating System/Distribution

Windows 10 22H2

### (Linux only) Desktop Environment

_No response_

### (Linux Only) Display Server

None

### Installation Method

Official Release

### Xournal++ Version

xournalpp 1.3.3 (6b7c1db2 from /)

### libgtk Version

3.24.51

### Steps to Reproduce

Selecting new graph paper from top icon menu

### Crash log

Executing "C:\Program Files\Xournal++\bin\xournalpp"
Xournal++ started with PID: 5016
Exited with error status: 1
    Date: Tue Mar 17 10:34:54 2026

xournalpp 1.3.3 (6b7c1db2 from /)
├──libgtk: 3.24.51
├──glib: 2.86.4
├──cairo:  1.18.4
└──OS info: Windows 10 22H2
  (The GDK backend is probably printed out below)

*** Output: ***

(com.github.xournalpp.xournalpp:5016): xopp-DEBUG: 09:32:45.761: TEXTDOMAINDIR = (NULL), Platform-specific locale dir = C:\Program Files\Xournal++\share\locale, chosen directory = C:\Program Files\Xournal++\share\locale
xopp-INFO: 09:32:46.945: Loading plugins from: C:\Program Files\Xournal++\share\xournalpp\plugins
xopp-INFO: 09:32:47.292: Loading plugins from: C:\Users\erwin\AppData\Local\xournalpp\plugins
(com.github.xournalpp.xournalpp:5016): xopp-DEBUG: 09:32:49.516: Extracted theme info: Name = Adwaita, rootname = Adwaita, dark = false
(com.github.xournalpp.xournalpp:5016): xopp-DEBUG: 09:32:49.547: Theme name: Adwaita
(com.github.xournalpp.xournalpp:5016): xopp-DEBUG: 09:32:49.547: Modified in GtkSettings: false
(com.github.xournalpp.xournalpp:5016): xopp-DEBUG: 09:32:49.547: Theme variant: light
(com.github.xournalpp.xournalpp:5016): xopp-DEBUG: 09:32:49.547: Icon theme: iconsColor
(com.github.xournalpp.xournalpp:5016): xopp-DEBUG: 09:32:50.670: Window moved to monitor "DELL U2515H"
(com.github.xournalpp.xournalpp:5016): xopp-DEBUG: 09:32:50.670: Automatic DPI conf: monitor height 311 mm - DPI = 117.607717
(com.github.xournalpp.xournalpp:5016): xopp-DEBUG: 09:33:50.440: TEXTDOMAINDIR = (NULL), Platform-specific locale dir = C:\Program Files\Xournal++\share\locale, chosen directory = C:\Program Files\Xournal++\share\locale
(com.github.xournalpp.xournalpp:5016): xopp-DEBUG: 09:35:00.925: Automatic DPI conf: monitor height 311 mm - DPI = 117.607717
(com.github.xournalpp.xournalpp:5016): xopp-DEBUG: 09:35:32.909: Automatic DPI conf: monitor height 311 mm - DPI = 117.607717
(com.github.xournalpp.xournalpp:5016): xopp-DEBUG: 09:35:32.937: Extracted theme info: Name = Adwaita, rootname = Adwaita, dark = false
(com.github.xournalpp.xournalpp:5016): xopp-DEBUG: 09:35:32.966: Theme name: Adwaita
(com.github.xournalpp.xournalpp:5016): xopp-DEBUG: 09:35:32.966: Modified in GtkSettings: false
(com.github.xournalpp.xournalpp:5016): xopp-DEBUG: 09:35:32.966: Theme variant: light
(com.github.xournalpp.xournalpp:5016): xopp-DEBUG: 09:35:32.966: Icon theme: iconsColor

*** Cerr: ***

Fontconfig error: Cannot load default config file: No such file: (null)

(com.github.xournalpp.xournalpp:5016): xopp-WARNING **: 09:32:45.761: Settings file C:\Users\erwin\AppData\Local\xournalpp\settings.xml does not exist. Regenerating. 
xopp-Message: 09:32:47.292: Using default latex template in C:\Program Files\Xournal++\share/xournalpp\resources\default_template.tex
xopp-Message: 09:38:32.916: Autosaving to C:\Users\erwin\AppData\Local\Microsoft\Windows\INetCache\xournalpp\autosaves\5016.autosave.xopp
xopp-Message: 09:41:32.915: Autosaving to C:\Users\erwin\AppData\Local\Microsoft\Windows\INetCache\xournalpp\autosaves\5016.autosave.xopp
xopp-Message: 09:44:32.917: Autosaving to C:\Users\erwin\AppData\Local\Microsoft\Windows\INetCache\xournalpp\autosaves\5016.autosave.xopp
xopp-Message: 09:47:32.904: Autosaving to C:\Users\erwin\AppData\Local\Microsoft\Windows\INetCache\xournalpp\autosaves\5016.autosave.xopp
xopp-Message: 09:50:32.915: Autosaving to C:\Users\erwin\AppData\Local\Microsoft\Windows\INetCache\xournalpp\autosaves\5016.autosave.xopp
xopp-Message: 09:53:32.927: Autosaving to C:\Users\erwin\AppData\Local\Microsoft\Windows\INetCache\xournalpp\autosaves\5016.autosave.xopp
xopp-Message: 09:56:32.914: Autosaving to C:\Users\erwin\AppData\Local\Microsoft\Windows\INetCache\xournalpp\autosaves\5016.autosave.xopp
xopp-Message: 09:59:32.914: Autosaving to C:\Users\erwin\AppData\Local\Microsoft\Windows\INetCache\xournalpp\autosaves\5016.autosave.xopp
xopp-Message: 10:02:32.929: Autosaving to C:\Users\erwin\AppData\Local\Microsoft\Windows\INetCache\xournalpp\autosaves\5016.autosave.xopp
xopp-Message: 10:14:32.916: Autosaving to C:\Users\erwin\AppData\Local\Microsoft\Windows\INetCache\xournalpp\autosaves\5016.autosave.xopp
xopp-Message: 10:17:32.915: Autosaving to C:\Users\erwin\AppData\Local\Microsoft\Windows\INetCache\xournalpp\autosaves\5016.autosave.xopp
xopp-Message: 10:20:32.915: Autosaving to C:\Users\erwin\AppData\Local\Microsoft\Windows\INetCache\xournalpp\autosaves\5016.autosave.xopp
xopp-Message: 10:23:32.924: Autosaving to C:\Users\erwin\AppData\Local\Microsoft\Windows\INetCache\xournalpp\autosaves\5016.autosave.xopp
xopp-Message: 10:26:32.917: Autosaving to C:\Users\erwin\AppData\Local\Microsoft\Windows\INetCache\xournalpp\autosaves\5016.autosave.xopp
xopp-Message: 10:29:32.928: Autosaving to C:\Users\erwin\AppData\Local\Microsoft\Windows\INetCache\xournalpp\autosaves\5016.autosave.xopp
xopp-Message: 10:32:32.916: Autosaving to C:\Users\erwin\AppData\Local\Microsoft\Windows\INetCache\xournalpp\autosaves\5016.autosave.xopp

*************************************************************************

[Crash Handler] Crashed 1 time(s) with signal 11
xournalpp 1.3.3 (6b7c1db2 from /)
├──libgtk: 3.24.51
├──glib: 2.86.4
├──cairo:  1.18.4
├──GDK backend: Win32
└──OS info: Windows 10 22H2

Try to get a stacktrace...
Stack trace (most recent call first):
#0  0x00007ff72c02ba85 in Stacktrace::printStacktrace(std::ostream&) at D:/a/xournalpp/xournalpp/src/util/Stacktrace.cpp:15:29
#1  0x00007ff72be62149 in crashHandler at D:/a/xournalpp/xournalpp/src/core/control/CrashHandler.cpp:58:36
#2  0x00007ff72c0a4ef1 in _gnu_exception_handler at D:/W/B/src/mingw-w64/mingw-w64-crt/crt/crt_handler.c:217:5
#3  0x00007ff8bd65ce45 in _C_specific_handler at C:\WINDOWS\SYSTEM32\ntdll.dll
#4  0x00007ff8bd67296e in _chkstk at C:\WINDOWS\SYSTEM32\ntdll.dll
#5  0x00007ff8bd622553 in RtlRaiseException at C:\WINDOWS\SYSTEM32\ntdll.dll
#6  0x00007ff8bd67147d in KiUserExceptionDispatcher at C:\WINDOWS\SYSTEM32\ntdll.dll
#7  0x00007ff81fadc914 in gtk_widget_set_sensitive at C:\Program Files\Xournal++\bin\libgtk-3-0.dll
#8  (inlined)          in operator() at D:/a/xournalpp/xournalpp/src/core/gui/menus/popoverMenus/PageTypeSelectionPopover.cpp:332:13
#9  0x00007ff72bf905cd in _FUN at D:/a/xournalpp/xournalpp/src/core/gui/menus/popoverMenus/PageTypeSelectionPopover.cpp:332:13
#10 0x00007ff875158639 in g_closure_invoke at C:\Program Files\Xournal++\bin\libgobject-2.0-0.dll
#11 0x00007ff87516cf1a in g_param_spec_variant at C:\Program Files\Xournal++\bin\libgobject-2.0-0.dll
#12 0x00007ff87516e4a9 in g_param_spec_variant at C:\Program Files\Xournal++\bin\libgobject-2.0-0.dll
#13 0x00007ff87517410f in g_signal_emit at C:\Program Files\Xournal++\bin\libgobject-2.0-0.dll
#14 0x00007ff87515c282 in g_cclosure_marshal_BOOLEAN__BOXED_BOXEDv at C:\Program Files\Xournal++\bin\libgobject-2.0-0.dll
#15 0x00007ff8751608ca in g_object_notify at C:\Program Files\Xournal++\bin\libgobject-2.0-0.dll
#16 0x00007ff82ece5530 in g_simple_action_set_state at C:\Program Files\Xournal++\bin\libgio-2.0-0.dll
#17 0x00007ff72bf8fa8b in PageTypeSelectionMenuBase::changeSelectionCallback(_GSimpleAction*, _GVariant*, PageTypeSelectionMenuBase*) at D:/a/xournalpp/xournalpp/src/core/gui/menus/PageTypeSelectionMenuBase.cpp:63:30
#18 0x00007ff875158639 in g_closure_invoke at C:\Program Files\Xournal++\bin\libgobject-2.0-0.dll
#19 0x00007ff87516cf1a in g_param_spec_variant at C:\Program Files\Xournal++\bin\libgobject-2.0-0.dll
#20 0x00007ff87516e4a9 in g_param_spec_variant at C:\Program Files\Xournal++\bin\libgobject-2.0-0.dll
#21 0x00007ff87517410f in g_signal_emit at C:\Program Files\Xournal++\bin\libgobject-2.0-0.dll
#22 0x00007ff82ece56d2 in g_simple_action_set_state at C:\Program Files\Xournal++\bin\libgio-2.0-0.dll
#23 0x00007ff82ece3caa in g_action_activate at C:\Program Files\Xournal++\bin\libgio-2.0-0.dll
#24 0x00007ff81f82ce7a in gtk_builder_get_application at C:\Program Files\Xournal++\bin\libgtk-3-0.dll
#25 0x00007ff875158639 in g_closure_invoke at C:\Program Files\Xournal++\bin\libgobject-2.0-0.dll
#26 0x00007ff87516d4b2 in g_param_spec_variant at C:\Program Files\Xournal++\bin\libgobject-2.0-0.dll
#27 0x00007ff87516e4a9 in g_param_spec_variant at C:\Program Files\Xournal++\bin\libgobject-2.0-0.dll
#28 0x00007ff87517410f in g_signal_emit at C:\Program Files\Xournal++\bin\libgobject-2.0-0.dll
#29 0x00007ff81f82f391 in gtk_button_clicked at C:\Program Files\Xournal++\bin\libgtk-3-0.dll
#30 0x00007ff8751588ac in g_closure_invoke at C:\Program Files\Xournal++\bin\libgobject-2.0-0.dll
#31 0x00007ff87516e55d in g_param_spec_variant at C:\Program Files\Xournal++\bin\libgobject-2.0-0.dll
#32 0x00007ff87517410f in g_signal_emit at C:\Program Files\Xournal++\bin\libgobject-2.0-0.dll
#33 0x00007ff81f82d3d4 in gtk_builder_get_application at C:\Program Files\Xournal++\bin\libgtk-3-0.dll
#34 0x00007ff8751588ac in g_closure_invoke at C:\Program Files\Xournal++\bin\libgobject-2.0-0.dll
#35 0x00007ff87516e55d in g_param_spec_variant at C:\Program Files\Xournal++\bin\libgobject-2.0-0.dll
#36 0x00007ff87517410f in g_signal_emit at C:\Program Files\Xournal++\bin\libgobject-2.0-0.dll
#37 0x00007ff81f912b0d in gtk_gesture_long_press_new at C:\Program Files\Xournal++\bin\libgtk-3-0.dll
#38 0x00007ff87515b5fa in g_cclosure_marshal_VOID__BOXEDv at C:\Program Files\Xournal++\bin\libgobject-2.0-0.dll
#39 0x00007ff8751588ac in g_closure_invoke at C:\Program Files\Xournal++\bin\libgobject-2.0-0.dll
#40 0x00007ff87516e55d in g_param_spec_variant at C:\Program Files\Xournal++\bin\libgobject-2.0-0.dll
#41 0x00007ff87517410f in g_signal_emit at C:\Program Files\Xournal++\bin\libgobject-2.0-0.dll
#42 0x00007ff81f90f86a in gtk_glade_catalog_init at C:\Program Files\Xournal++\bin\libgtk-3-0.dll
#43 0x00007ff81f910f1a in gtk_gesture_handles_sequence at C:\Program Files\Xournal++\bin\libgtk-3-0.dll
#44 0x00007ff81f91457b in gtk_gesture_rotate_get_angle_delta at C:\Program Files\Xournal++\bin\libgtk-3-0.dll
#45 0x00007ff81f8d4567 in gtk_event_controller_handle_event at C:\Program Files\Xournal++\bin\libgtk-3-0.dll
#46 0x00007ff81fac819b in gtk_requisition_free at C:\Program Files\Xournal++\bin\libgtk-3-0.dll
#47 0x00007ff81f7e348e at C:\Program Files\Xournal++\bin\libgtk-3-0.dll
#48 0x00007ff8751588ac in g_closure_invoke at C:\Program Files\Xournal++\bin\libgobject-2.0-0.dll
#49 0x00007ff87516db5c in g_param_spec_variant at C:\Program Files\Xournal++\bin\libgobject-2.0-0.dll
#50 0x00007ff87517410f in g_signal_emit at C:\Program Files\Xournal++\bin\libgobject-2.0-0.dll
#51 0x00007ff81fac9da9 in gtk_requisition_copy at C:\Program Files\Xournal++\bin\libgtk-3-0.dll
#52 0x00007ff81f962940 in gtk_lock_button_set_permission at C:\Program Files\Xournal++\bin\libgtk-3-0.dll
#53 0x00007ff81f964a26 in gtk_main_do_event at C:\Program Files\Xournal++\bin\libgtk-3-0.dll
#54 0x00007ff85798f908 in gdk_event_free at C:\Program Files\Xournal++\bin\libgdk-3-0.dll
#55 0x00007ff8579cd600 in gdk_win32_drag_context_get_type at C:\Program Files\Xournal++\bin\libgdk-3-0.dll
#56 0x00007ff82eae2217 in g_clear_list at C:\Program Files\Xournal++\bin\libglib-2.0-0.dll
#57 0x00007ff82eae5786 in g_get_monotonic_time at C:\Program Files\Xournal++\bin\libglib-2.0-0.dll
#58 0x00007ff82eae5edc in g_main_context_iteration at C:\Program Files\Xournal++\bin\libglib-2.0-0.dll
#59 0x00007ff82ecdbf21 in g_application_run at C:\Program Files\Xournal++\bin\libgio-2.0-0.dll
#60 0x00007ff72be63c7c in XournalMain::run(int, char**) at D:/a/xournalpp/xournalpp/src/core/control/XournalMain.cpp:702:32
#61 0x00007ff72be610d8 in __tmainCRTStartup at D:/W/B/src/mingw-w64/mingw-w64-crt/crt/crtexe.c:260:11
#62 0x00007ff72be61435 in WinMainCRTStartup at D:/W/B/src/mingw-w64/mingw-w64-crt/crt/crtexe.c:98:9
#63 0x00007ff8bc907373 in BaseThreadInitThunk at C:\WINDOWS\System32\KERNEL32.DLL
#64 0x00007ff8bd61cc90 in RtlUserThreadStart at C:\WINDOWS\SYSTEM32\ntdll.dll

Trying to emergency save the current open document...
Successfully saved document to "C:\Users\erwin\AppData\Local\xournalpp\emergencysave.xopp"

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by bhennion**
Fix #7281

### CODE REVIEW

File: src/core/gui/menus/popoverMenus/PageTypeSelectionPopover.cpp [hunk 1]
```diff
@@ -325,38 +354,24 @@ GtkWidget* PageTypeSelectionPopover::createPopover() const {
...
-                        selectedIndex == COPY_CURRENT_PLACEHOLDER || selectedIndex < self->types->getPageTypes().size();
-                gtk_widget_set_sensitive(GTK_WIDGET(pageFormatCB), shouldPageFormatSettingsBeEnabled);
-
-                g_simple_action_set_enabled(self->orientationAction.get(),
-                                            shouldPageFormatSettingsBeEnabled && self->selectedPageSize.has_value());
             })),
-            userdataPointerTuple,
-            xoj::util::closure_notify_cb<std::tuple<GtkButton*, const PageTypeSelectionPopover*, GtkComboBox*>>,
-            GConnectFlags(0));
+            GTK_BUTTON(applyToCurrentPageButton));
```
Comment (rolandlo) [inline src/core/gui/menus/popoverMenus/PageTypeSelectionPopover.cpp]: No need for casting here.
```suggestion
            applyToCurrentPageButton);
```

File: src/core/gui/menus/popoverMenus/PageTypeSelectionPopover.cpp [hunk 2]
```diff
@@ -325,38 +354,24 @@ GtkWidget* PageTypeSelectionPopover::createPopover() const {
...
             this->typeSelectionAction.get(), "notify::state",
             G_CALLBACK((+[](GObject* a, GParamSpec*, gpointer pointerTuple) {
-                auto [btn, self, pageFormatCB] =
-                        *static_cast<std::tuple<GtkButton*, const PageTypeSelectionPopover*, GtkComboBox*>*>(
-                                pointerTuple);
+                auto [btn, self] = *static_cast<std::pair<GtkButton*, const PageTypeSelectionPopover*>*>(pointerTuple);
                 xoj::util::GVariantSPtr state(g_action_get_state(G_ACTION(a)), xoj::util::adopt);
                 auto selectedIndex = getGVariantValue<size_t>(state.get());
                 gtk_widget_set_sensitive(GTK_WIDGET(btn), selectedIndex != COPY_CURRENT_PLACEHOLDER ||
                                                                   self->selectedPageSize.has_value());
```
Comment (rolandlo) [inline src/core/gui/menus/popoverMenus/PageTypeSelectionPopover.cpp]: For consistency and simplicity:
```suggestion
                auto [btn, self] = *static_cast<std::pair<GtkWidget*, const PageTypeSelectionPopover*>*>(pointerTuple);
xoj::util::GVariantSPtr state(g_action_get_state(G_ACTION(a)), xoj::util::adopt);
auto selectedIndex = getGVariantValue<size_t>(state.get());
gtk_widget_set_sensitive(btn, selectedIndex != COPY_CURRENT_PLACEHOLDER ||
self->selectedPageSize.has_value());
```

**Review by rolandlo — APPROVED** [review]
LGTM up to nitpicks.

**Comment by bhennion** [comment]
Thanks for the review. Merging once the CI clears.
